### ISSUE TITLE
examples.diffusion.mesh1D No-flux - steady-state doesn't always give zero

### ISSUE THREAD

**Issue by agoncalvescoel** [usnistgov/fipy#1010]
When I run `mesh1D.py` , the other parts of the script run fine, but the part on the figure below gives me different results
![image](https://github.com/usnistgov/fipy/assets/100953718/05673e5b-5b76-4374-8190-bf656308d55a)

The blue line does not appear at all
![image](https://github.com/usnistgov/fipy/assets/100953718/ad1d849c-051e-4b53-9c99-cd24b92e8df9)

And when it uns the validation of numerix, gives me False
![image](https://github.com/usnistgov/fipy/assets/100953718/3e110957-3a19-420a-9a35-610cd296e4b9)

**Comment by guyer** [comment]
So, the code is working properly, but the explanation in the text is not completely correct. Those lines are only tested with PySparse, which does return zero everywhere. Other solvers can return infinity or NaN. Regardless, the solution isn't right, which is the point of the illustration. I'll work on improving the explanation.
