### ISSUE TITLE
Fix CGS solver in pysparse

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#146]
Code examples that work perfectly well with PCG should also work woth CGS and they don't. For example Andrew Reeve's code that is attached. The Trilinos version of CGS also works fine.

 _Imported from trac ticket [#161](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/161),  created by wd15 on 11-19-2008 at 10:05, last modified: 11-24-2008 at 09:58_

**Comment by guyer** [comment]
Fixing PySparse isn't our job
