### ISSUE TITLE
lid driven cavity example Re 1000

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#210]
I'd like to contribute the lid driven cavity for Re 1000 to the fipy flow examples. So this is like the stokes cavity but not in the viscous limit.

In attachment the example and the figures to create the documentation. 

Comparison is made with the Ghia et al 1982 results so as to see how fipy stacks up to that for a flow problem. 

Qualitatively the result is ok, but improvements to fipy are needed to better match the curve. 

I find this example important to also show users what _not_ to expect from fipy.

 _Imported from trac ticket [#306](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/306),  created by benny.malengier@gmail.com on 07-19-2010 at 05:39, last modified: 01-18-2011 at 22:27_

**Comment by wd15** [comment]
Should we close this issue?

**Comment by tkphd** [comment]
Use of the [SIMPLE algorithm](https://en.wikipedia.org/wiki/SIMPLE_algorithm) is neat -- thanks to @bmcage for the contribution!
However, considering the issue has not resurfaced for 9 years, yes, I think this should be closed as a niche example.
