### ISSUE TITLE
Link to matforge live CD

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#211]
Create a link on the fipy home page to the matforge live CD

 _Imported from trac ticket [#307](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/307),  created by wd15 on 08-11-2010 at 11:09, last modified: 01-30-2013 at 13:43_

**Comment by guyer** [comment]
Ancient history
