### ISSUE TITLE
numpy 1.5.1 and masked arrays

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#255]
This code

```
from fipy import *
import numpy
from numpy import ma
m = Grid1D(nx=3)
print type(ma.arange(4) * FaceVariable(mesh=m))
print type(FaceVariable(mesh=m) * ma.arange(4))
```

returns

```
<class 'numpy.ma.core.MaskedArray'>
<class 'fipy.variables.binaryOperatorVariable.binOp'>
```

with numpy 1.5.1. Yikes!

 _Imported from trac ticket [#351](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/351),  created by wd15 on 06-03-2011 at 17:17, last modified: 01-30-2013 at 13:38_

**Comment by guyer** [comment]
Works in numpy 1.10.4
