### ISSUE TITLE
FiPy on IronPython

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#257]
Given that IronPython now has support for numpy (http://www.enthought.com/repo/.iron/), could FiPy run under IronPython?
Has anyone made investigations into this?

 _Imported from trac ticket [#353](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/353),  created by kjosefss@fosterandpartners.com on 07-12-2011 at 06:47, last modified: 06-12-2013 at 14:14_

**Comment by guyer** [comment]
Ancient history
