### ISSUE TITLE
glumpy

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#266]
Add a glumpy viewer maybe? Looks much faster than matplotlib and has 3D.

  http://code.google.com/p/glumpy/

 _Imported from trac ticket [#362](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/362),  created by wd15 on 09-19-2011 at 15:17, last modified: 01-30-2013 at 13:45_

**Comment by tkphd** [comment]
Ancient history
