### ISSUE TITLE
Remove deprecated gist and gnuplot support

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#297]
Gist and Gnuplot support is due for removal in version 3.2. They were deprecated with [r5016](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/changeset/5016/historical), [r5015](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/changeset/5015/historical) and [r5014](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/changeset/5014/historical). 

 

 _Imported from trac ticket [#414](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/414),  created by wd15 on 12-09-2011 at 10:33, last modified: 01-30-2013 at 13:49_

**Comment by guyer** [comment]
Git commits that deprecated these viewers were f8772588, 34a24b0c, and b9379c7c.
