### ISSUE TITLE
`mpirun -np 2 python -Wd setup.py test --trilinos` hanging on sandbox under buildbot

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#305]
Hangs at the chemotaxis tests.

The problem seems to be that when the PYTHONPATH is explicitly set to "." then it hangs otherwise it runs through without issue. The crontab on sandbox sets the PYTHONPATH. I'm worried about simply removing that as python could pick up on the system version of fipy during buildbot runs. Maybe use a virtualenv.

Also reported in issue #264

 _Imported from trac ticket [#425](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/425),  created by wd15 on 01-20-2012 at 13:30, last modified: 01-30-2013 at 13:42_

**Comment by guyer** [comment]
As of #524, there appear to be no parallel hangs in the tests
