### ISSUE TITLE
fipy.test() and fipy/test.py clash

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#336]
Using ipython on the Amazon cloud seems to throw up a clash between fipy.test() and fipy/test.py. The first import of fipy allows fipy.test() to run fine, but subsequent attempts to run fipy.test() 
throws

```
TypeError: 'module' object is not callable
```

 _Imported from trac ticket [#459](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/459),  created by wd15 on 08-17-2012 at 16:28, last modified: 09-09-2013 at 18:53_

**Comment by guyer** [comment]
`fipy.test()` works now. No unexpected failures on multiple runs.
