### ISSUE TITLE
Don't upload packages to PyPi, just add the master url

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#340]
See http://stackoverflow.com/questions/9949420/how-to-configure-setup-py-to-have-pip-install-from-github-master

Perfect for us as the latest commit on master is always a release.

 _Imported from trac ticket [#463](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/463),  created by wd15 on 09-06-2012 at 11:32, last modified: 09-06-2013 at 10:03_

**Comment by guyer** [comment]
As [discussed](https://github.com/gccxml/pygccxml/issues/48) [elsewhere](https://groups.google.com/forum/#!topic/django-developers/YQ36_DCMHVE), `master` isn't really a good choice for [PyPI](https://pypi.org/). We can make `download_url` [version-specific](https://github.com/usnistgov/fipy/releases), but the workflow with [PyPI](https://pypi.org/) isn't clear to me then.

**Comment by guyer** [comment]
Fixed(?) in [3.3](https://github.com/usnistgov/fipy/tree/3.3)

I don't know whether it's working or not. You still have to point twine at a local distribution tarball.
