### ISSUE TITLE
broken Variable negation of bool

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#345]
This seems wrong

```
   >>> print -Variable(False)
   True
   >>> print -(Variable(-1) < 0) * 3 - 2
   -2
   >>> print -False
   0
   >>> print -Variable(True)
   False
   >>> print -True
   -1
```

This is due to numpy making a weird choice here

```
   >>> print -np.array(True)
   False
```

Negation is a mathematical op so should be treated as such. In FiPy,
we do this sort of thing quite frequently

```
   pecletLarge = large - (geomCoeff < 0) * (2 * large)
   pecletLarge = -(geomCoeff < 0) * (2 * large) + large
```

for example. The result changes based on the ordering of the terms in the expression. `__neg__` is different from `__sub__`.

 _Imported from trac ticket [#468](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/468),  created by wd15 on 09-21-2012 at 16:36, last modified: 09-26-2013 at 16:04_

**Comment by guyer** [comment]
NumPy raises an error now:
```python
>>> -np.array(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
```
