### ISSUE TITLE
Numerous tests fail with `Factor is exactly singular` with EPD on Windows

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#348]
Some of the test fails during the test procedure (see the feedback of the consol). Some of the examples diffusion/mesh1D.py are then not working : the runtime error is "the Factor is exactly singular" when running the explicit transient diffusion example.

I'm running fipy 3.0 on python 2.7.3 powered by EDP 7.3.2.

 _Imported from trac ticket [#471](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/471),  created by bacchin on 09-28-2012 at 02:11, last modified: 01-30-2013 at 13:35_

**Comment by guyer** [comment]
* No reports of this in years. 
* All tests currently pass on Windows. 
* EPD is long superceded by Canopy.
