### ISSUE TITLE
Viewers don't inline well in IPython notebook

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#368]
The [http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html IPython notebook ] is capable of inline display of Matplotlib figures via

```
ipython notebook --pylab inine
```

and FiPy viewers do appear when instantiated, but subsequent calls to `viewer.plot()` don't do anything useful. 

It would be nice if there were a way to visualize, or even animate, the viewers within the notebook.

 _Imported from trac ticket [#494](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/494),  created by guyer on 01-29-2013 at 15:45, last modified: 01-30-2013 at 11:00_

**Comment by lucentdan** [comment]
Adding wait=True to clear_output() makes it cleaner.
