### ISSUE TITLE
FaceVariable should not have a "globalValue" method

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#400]
This ticket was prompted by 

  https://www.mail-archive.com/fipy@nist.gov/msg02801.html
  ~~http://thread.gmane.org/gmane.comp.python.fipy/3228~~

There is no easy way to obtain a FaceVariable's global value so the methods concerning global values should be moved out of FaceVariable and MeshVariable into CellVariable. Global value returns nonsense currently for FaceVariable's in parallel. Moreover, "_localNonOverlappingFaceIDs" doesn't do the right thing in parallel other than for 1D as far as I can tell.

 _Imported from trac ticket [#657](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/657),  created by wd15 on 10-17-2013 at 17:08, last modified: 10-18-2013 at 12:38_

**Comment by guyer** [comment]
It turned out that it was possible to have a proper `globalValue` on `FaceVariable`.
