### ISSUE TITLE
Remind users of different types of conservation equations

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#413]
Users may find the behavior of the coefficient to the various terms surprising if they're unfamiliar with looking at different types of conservation equations. This ticket is to add a simple example demonstrating the difference in handling non-uniform mass diffusivity and non-uniform thermal diffusivity within the mesh1D diffusion example.

 _Imported from trac ticket [#670](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/670),  created by raybsmith on 08-18-2014 at 15:28, last modified: 08-18-2014 at 15:28_

**Comment by guyer** [comment]
Fixed by #423
