### ISSUE TITLE
PeriodicGrid3D supports Only 1 axes of periodicity or all 3, not 2

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#414]
_BasePeriodicGrid3D needs additional subclasses to handle periodicity in 2 dimensions (eg. x and y but not z).

 _Imported from trac ticket [#671](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/671),  created by drodgers on 09-07-2014 at 01:33, last modified: 09-07-2014 at 01:56_

**Comment by guyer** [comment]
Fixed by #424
