### ISSUE TITLE
Updates to reflect move to Github

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#416]
- [x] change the .txt files .rst (this should render the pages appropriately)
 - [x] include link to website at top of front page
 - [ ] update FiPy docs to refer to Github and not Matforge
 - [ ] email the mailing list about change with instructions about how to update pointers
 - [ ] Make http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py work correctly.

**Comment by guyer** [comment]
matforge.org is down. The domain is presently up for grabs.
