### ISSUE TITLE
`pip install pysparse` fails with "fatal error: 'spmatrix.h' file not found"

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#435]
The PySparse tarball downloaded by `pip install` is broken such that

```
gcc: pysparse/sparse/src/spmatrixmodule.c

pysparse/sparse/src/spmatrixmodule.c:4:10: fatal error: 'spmatrix.h' file not found

#include "spmatrix.h"

         ^

1 error generated.

pysparse/sparse/src/spmatrixmodule.c:4:10: fatal error: 'spmatrix.h' file not found

#include "spmatrix.h"

         ^
```

 - [x] Get conda recipe working
 - [x] Ensure this ticket is filed against PySparse
 - [x] Wipe hands of it

**Comment by jiaweih** [comment]
`pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse`

This can install **pysparse**, but the same errors would be encountered when importing **pysparse**.

**Comment by guyer** [comment]
What same errors? The errors cited in this issue are build-time errors. There may be import errors on some platforms, but they are unrelated to this issue.

`pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse` works for me.

**Comment by saarahy** [comment]
hi everyone!
i had the same error and i already try with this git installation, but it show me this error:

<code>Command "C:\Python27\python.exe -c "import setuptools, tokenize; __file__='C:\\Python27\\Scripts\\src\\pysparse\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Python27\Scripts\src\pysparse </code>

do you know why?

**Comment by guyer** [comment]
Filed https://sourceforge.net/p/pysparse/bugs/14/

**Comment by ajchc** [comment]
I'm having the same problem as @saarahy:

`Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/antonio/src/pysparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/antonio/src/pysparse/`

This is the final massage, but if I scrollback, the first error appearing is

`svn: E155007: '/home/antonio/src/pysparse' is not a working copy
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    Error while parsing svn version
`

so I'm not sure what is the exact problem...

**Comment by guyer** [comment]
The [pysparse conda-forge feedstock](https://github.com/conda-forge/pysparse-feedstock) is now active, with [downloads available on anaconda](https://anaconda.org/conda-forge/pysparse)
