### ISSUE TITLE
Figure misleading in examples.cahnHilliard.mesh2DCoupled 

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#437]
The figure in http://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.mesh2DCoupled.html is taken from http://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.mesh2D.html, but this example only ever runs a 20x20 mesh out to t=0.05, rather than the 1000x1000 mesh with t=1000 in the figures.

The figures should be consistent with the code, or the code with the figures.

**Comment by oliveirarodolfo** [comment]
:+1:
