### ISSUE TITLE
Use github API to get nicely formatted list of issues

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/fipy#440]
Something that we implemented in our project was to query the github API in order to build a nice RST( or Markdown) list of issues with hyperlinks to the issues in question.  It's not too painful to pull all issues associated with a milestone: https://github.com/CoolProp/CoolProp/blob/master/dev/scripts/milestone2rst.py

**Comment by wd15** [comment]
@ianhbell, thanks for the code snippet. Since we have so many open issues right now that we haven't fixed, I'll just close this, but I'll remember to look it if we need to do some GitHub API interactions for one reason or another. Thanks

**Comment by ianhbell** [comment]
Fair enough!
