### ISSUE TITLE
Mesh3D cellToCellIDs is broken

### ISSUE THREAD

**Issue by pkgw** [usnistgov/fipy#470]
Unless I'm strongly confused, the implementation of `_cellToCellIDs` for `UniformMesh3D` is broken, as demonstrated by a simple example:

```python
>>> import fipy
>>> t = fipy.Grid3D (nx=2, ny=2, nz=2)
>>> print (t._cellToCellIDs)
<<< [[-- 0 -- 2 -- 4 -- 6]
<<<  [1 -- 3 -- 5 -- 7 --]
<<<  [-- -- -2 -1 -- -- 2 3]
<<<  [4 5 -- -- 8 9 -- --]
<<<  [-- -- -- -- 0 1 2 3]
<<<  [4 5 6 7 -- -- -- --]]
```

Note that the middle of the array contains both negative numbers and an 8 and a 9, while the maximum legal index is 7. This codepath gets triggered, leading to an exception, if you try to use an AdvectionTerm on a 3D mesh.

[The function](https://github.com/usnistgov/fipy/blob/develop/fipy/meshes/uniformGrid3D.py#L169) is short but it seems to be implement in an (overly?) tricky way so it's not obvious to me how to fix it.

**Comment by pkgw** [comment]
After some total cargo-cult coding, [this patch](https://gist.github.com/pkgw/59dceaa4eba79f513b41) seems to be what I need to get things to run without crashing. I don't understand if they actually work. 

I'm not making a proper pull request since I'm not sure if these fixes are correct, and test cases should be developed if things were truly broken. It certainly seems to me that the current 3D grid implementation causes crashes, though.

**Comment by guyer** [comment]
Your fix looks right to me. A pull request would be most welcome. Tests that demonstrate the problem would be gravy.
