### ISSUE TITLE
Reviewable.io has read-only access, can't leave comments

### ISSUE THREAD

**Issue by tkphd** [usnistgov/fipy#493]
Pull requests include links to Reviewable.io, encouraging responsible parties to scrutinize the code and leave comments. At the moment, Reviewable.io has read-only access to this repo, so the comments can't propagate from the commentor to the rest of us.

If Reviewable.io integration is desired, someone with administrative access to this repo needs to sign into reviewable.io, open the "Repositories" tab, and flip the switch on usnistgov/fipy to the "On" position.

**Comment by wd15** [comment]
@tkphd, I think I did it...
