### ISSUE TITLE
examples/levelSet/advection/mesh1D.py: advecting twice leads to var.allclose(answer) = False

### ISSUE THREAD

**Issue by cashTangoTangoCash** [usnistgov/fipy#505]
fipy 3.1.3

A Minor Issue

https://github.com/usnistgov/fipy/blob/0a209579835e3245976129581c14d2cda27fcaa2/examples/levelSet/advection/mesh1D.py

examples.levelSet.advection.mesh1D.py

When I run the script, I get False:

> (MYFIPYENV)username@username-desktop:~/Documents/Computer/Software/FiPyNotes/fipy-
>develop$ python
> examples/levelSet/advection/mesh1D.py

>False

The False is the output of line 106:
`print var.allclose(answer) #doctest: +LSM`

I think there is a problem at line 96-100:

>The result can be tested with the following code:
`>>> for step in range(steps):
...     var.updateOld()
...     advEqn.solve(var, dt=timeStepDuration)`

This is a second round of advecting when this script is run in the manner I am running it.  The first round of advecting is at lines 91-93.  Line 192 distanceTravelled assumes just one round of advecting.

I am guessing this is an issue with the script having built-in testing?

Plots also flash by instantly; maybe slow things down with time.sleep?

**Comment by wd15** [comment]
@cashTangoTangoCash, as you noticed, it's run in a different manner depending on whether it's being run as a test of as a script. The bool output isn't important unless you're trying to debug the test. 

If you'd like to see the plots, add a "raw_input()" statement after "viewer.plot()".
