### ISSUE TITLE
Exception while accessing to Gmsh3d.physicalCells

### ISSUE THREAD

**Issue by faxik** [usnistgov/fipy#507]
```python
>>> mesh.physicalCells.keys()
dict_keys(['Pipe_1_1'])

>>> mesh.physicalCells['Pipe_1_1']
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/usr/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    670                 type_pprinters=self.type_printers,
    671                 deferred_pprinters=self.deferred_printers)
--> 672             printer.pretty(obj)
    673             printer.flush()
    674             return stream.getvalue()

/usr/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    381                             if callable(meth):
    382                                 return meth(obj, self, cycle)
--> 383             return _default_pprint(obj, self, cycle)
    384         finally:
    385             self.end_group()

/usr/lib/python3.6/site-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    502         # A user-provided repr. Find newlines and replace them with p.break_()
--> 503         _repr_pprint(obj, p, cycle)
    504         return
    505     p.begin_group(1, '<')

/usr/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    699     """A pprint that just redirects to the normal repr function."""
    700     # Find newlines and replace them with p.break_()
--> 701     output = repr(obj)
    702     for idx,output_line in enumerate(output.splitlines()):
    703         if idx:

/usr/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py in __repr__(self)
    211 
    212         def __repr__(self):
--> 213             return self._getRepresentation()
    214 
    215         def __reduce__(self):

/usr/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/binaryOperatorVariable.py in _getRepresentation(self, style, argDict, id, freshen)
     96                 return self._name
     97             else:
---> 98                 return "(" + operatorClass._getRepresentation(self, style=style, argDict=argDict, id=id, freshen=freshen) + ")"
     99 
    100     return binOp

/usr/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py in _getRepresentation(self, style, argDict, id, freshen)
    187                     stack.append(self.op.__code__.co_names[counter])
    188                 elif opcode.opname[bytecode] == 'LOAD_FAST':
--> 189                     stack.append(__var(_popIndex()))
    190                 elif opcode.opname[bytecode] == 'CALL_FUNCTION':
    191                     args = []

/usr/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py in __var(i)
    106 
    107             def __var(i):
--> 108                 v = self.var[i]
    109                 if style == "__repr__":
    110                     result = repr(v)


%debug
ipdb> self.var
[CellVariable(value=array([1, 3, 1, ..., 2, 2, 2]), mesh=Gmsh3D()), 1]

ipdb> type( self.var )
<class 'list'>
```

For some reason, `self.var` is not consistent with `__var`.

Please, advise.

**Comment by faxik** [comment]
[cube_grid_rect_parametric.geo.txt](https://github.com/usnistgov/fipy/files/841809/cube_grid_rect_parametric.geo.txt)

**Comment by faxik** [comment]
Small test to reproduce
[test-holes.geo.txt](https://github.com/usnistgov/fipy/files/841872/test-holes.geo.txt)

**Comment by faxik** [comment]
The issue exists both on master and development branches.

**Comment by jlhsage** [comment]
I've converted FiPy from the github master to python 3.6 with gmsh, and only about 20 out of 525 tests are giving errors.  Of those 20 errors almost all of them involve a self.var assignment that looks like it may be related to your inconsistency.   I found through tests that the line 108 in 'operatorVariable.py' is trying to index an 'self.var' with an integer of 30000, but self.var is a list containing only one item, the CellVariable.

I wonder if the list needs to be dereferenced before its indexed, like 'self.var[0][i]'?  Here's the error output that I get on many of the remaining test errors from 'python acoustics.py':

Traceback (most recent call last):
  File "acoustics.py", line 70, in <module>
    vi = Viewer((q[0], q[1]))
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/viewers/matplotlibViewer/__init__.py", line 113, in MatplotlibViewer
    return Matplotlib1DViewer(vars=vars, title=title, axes=axes, **kwlimits)
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/viewers/matplotlibViewer/matplotlib1DViewer.py", line 91, in __init__
    self.axes.legend([var.name for var in self.vars], loc=legend)
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/viewers/matplotlibViewer/matplotlib1DViewer.py", line 91, in <listcomp>
    self.axes.legend([var.name for var in self.vars], loc=legend)
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py", line 230, in _getName
    name = self._getRepresentation(style="name")
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py", line 189, in _getRepresentation
    stack.append(__var(_popIndex()))
  File "/home/jlh/wrk/anaconda3/lib/python3.6/site-packages/FiPy-3.1.3.dev138+gecbe868f-py3.6.egg/fipy/variables/operatorVariable.py", line 108, in __var
    v = self.var[i]
IndexError: list index out of range

**Comment by bragostin** [comment]
I have the exact issue today. Any workaround found since April?

**Comment by guyer** [comment]
I cannot reproduce the original report with either FiPy 3.1.3 or with `master`.
