### ISSUE TITLE
Grid3D and grad are causing IndexError

### ISSUE THREAD

**Issue by oatNeil** [usnistgov/fipy#508]
The following code works fine:
>>> from fipy import *
>>> nx=ny=5
>>> dx=dy=0.025
>>> m=Grid2D(nx=nx, ny=ny, dx=dx, dy=dy)
>>> r=CellVariable(mesh=m, value=1.)
>>> print r.grad

However, when I change it to Grid3D it fails. The following code gives an error:
>>> from fipy import *
>>> nx=ny=nz=5
>>> dx=dy=dz=0.025
>>> m=Grid3D(nx=nx, ny=ny, nz=nz, dx=dx, dy=dy, dz=dz)
>>> r=CellVariable(mesh=m, value=1.)
>>> print r.grad

This is the error:
IndexError: an index can only have a single ellipsis ('...')

r.faceGrad gives the same error. In 2D, r.faceGrad[0] and r.faceGrad[1] work fine. But the error always occurs in 3D.
Am I doing something wrong? Or is this a bug?

**Comment by wd15** [comment]
@oatNeil, It seems like [uniformGrid3D.py](../tree/develop/fipy/meshes/uniformGrid3D.py) has places with two sets of ellipsis in an index, which doesn't make sense to me and probably was never a good idea. The latest version of Numpy (1.12) doesn't seem to allow this so you're getting an error. The short term solution is to switch to version 1.11 of Numpy. That will only throw a deprecation warning.

**Comment by oatNeil** [comment]
@wd15 , Thank you so much for your quick response.

I installed numpy version 1.11, so when I entered

>>> import numpy as np
>>> np.__version__

'1.11'

Then when I tested the previous Grid3D code, 

>>> from fipy import *
>>> nx=ny=nz=5
>>> dx=dy=dz=0.025
>>> m=Grid3D(nx=nx, ny=ny, nz=nz, dx=dx, dy=dy, dz=dz)
>>> r=CellVariable(mesh=m, value=1.)
>>> print r.grad

it gave me a different error: 
IndexError: axis 1 out of bounds [0, 1)

The Grid2D works fine, like before.

Is fipy using the 1.11 version of numpy? If not, how do I force it to use the 1.11 version? Or is this a new problem altogether?

Thanks again for your help.

**Comment by wd15** [comment]
@oatNeil, I created a Dockerfile with an environment with fipy and numpy 1.11.3. The code snippet above seems to work, see https://gist.github.com/wd15/0df919c420954fe5b02480c81b82b6c5.

The Dockerfile might help you figure out how our environments differ if it is more than simply numpy and fipy versions.

**Comment by oatNeil** [comment]
Thanks for your help I'll use this.

**Comment by guyer** [comment]
Back-installing numpy 1.11 is only a workaround. We need to fix the underlying error.

**Comment by raviapatel** [comment]
Any luck on solution of this error??

**Comment by raviapatel** [comment]
Another error in same file is related to setting 2D mesh if  I put define fipy.Grid2D(dx=dx, dy=dy, Lx=Lx, Ly=Ly) i get error RuntimeError: Factor is exactly singular and if I do mesh = fipy.Grid2D(dx=dx, dy=dy, nx=Lx/dx, ny=Ly/dy) it works fine
cheers
Ravi

**Comment by profgerto** [comment]
I run into the same issue. I run FiPy through python 3.6.  Setting dx and dy to non-integer numbers (e.g. 0.25 instead of 1) seems to have fixed the problem for me.

**Comment by guyer** [comment]
Looks like this got fixed around FiPy 3.2.
