### ISSUE TITLE
Unable to use conda for installing FiPy in Windows

### ISSUE THREAD

**Issue by nehaljwani** [usnistgov/fipy#509]
```
(root) C:\Users\nwani>conda create -n fipy_new -c guyer -c conda-forge fipy=3.1.2
Fetching package metadata ...............
Solving package specifications:


PackageNotFoundError: Dependencies missing in current win-64 channels:
  - fipy 3.1.2* -> gmsh
  - fipy 3.1.2* -> pysparse
  - fipy 3.1.2* -> trilinos

Close matches found; did you mean one of these?

    pysparse: pycparser, parse, sqlparse

(and similarly for the other packages)
```

```
(root) C:\Users\nwani>conda create -n fipy_new -c guyer -c conda-forge fipy
Fetching package metadata ...............
Solving package specifications:


PackageNotFoundError: Dependencies missing in current win-64 channels:
  - fipy -> gmsh
  - fipy -> pysparse
  - fipy -> trilinos

Close matches found; did you mean one of these?

    pysparse: pycparser, parse, sqlparse

(and similarly for the other packages)
```

It seems that the conda packages `gmsh`, `pysparse` and `trilinos` haven't been made available for the Windows platform in the conda channel `guyer`

**Comment by wd15** [comment]
@nehaljwani, the following link has instructions for using FiPy in a Docker instance.

https://gist.github.com/wd15/0df919c420954fe5b02480c81b82b6c5

It might be easier to use Docker on your Windows machine rather than trying to run FiPy natively.

**Comment by guyer** [comment]
pysparse and gmsh are now available on guyer channel. 
pytrilinos isn't, but the trilinos developers are responsible for the feedstock on conda-forge; a windows build seems unlikely.
