### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Dogeek** [usnistgov/fipy#517]
I tried installing fipy on mymachine. I have all the required libraries installed, but I'm running Python 3.6.1 (x86).

This library **supposedly** supports Python 3, with **supposedly** specialized installation instructions for python 3. Supposedly, because NONE of that is actually true. 7 years of python 3, and you can't make a proper port. 

So : 

- [ ] Add python 3 as the default, and let go of python 2
- [ ] In the meantime, add actual detailed instructions in the INSTRUCTIONS.txt / wiki / readme.rst because those instructions can't be found anywhere.

I tried using 2to3 to make it compatible to no avail, and  I'm not inthe mood for porting an entire library to 3 on my own because developers can't do their f-ing job. If you stopped maintaining it, say so.

/rant

**Comment by guyer** [comment]
We're sorry you feel that way
