### ISSUE TITLE
fipy with pysparse is not working "TypeError: must be numpy.ndarray, not binOp"

### ISSUE THREAD

**Issue by alpxp** [usnistgov/fipy#522]
fipy with pysparse is not working for me since recently (not exactly sure which update is responsible for this, everything worked fine several month ago). Running the code with --scipy is OK. The error I get with pysparse is the following:

> File "/usr/local/lib/python2.7/site-packages/fipy/terms/term.py", line 213, in solve
    solver._solve()
  File "/usr/local/lib/python2.7/site-packages/fipy/solvers/pysparse/pysparseSolver.py", line 103, in _solve
    self._solve_(self.matrix, array, self.RHSvector)
  File "/usr/local/lib/python2.7/site-packages/fipy/solvers/pysparse/linearLUSolver.py", line 102, in _solve_
    LU.solve(errorVector, xError)
TypeError: must be numpy.ndarray, not binOp

The environment is macos 10.12.6
> Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
import fipy, pysparse
fipy.__version__
'3.1.3'
pysparse.__version__
'1.3-dev'

I should mention that I had to install pysparse with:
`pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse`
because of this issue https://github.com/usnistgov/fipy/issues/435
the only version which can be installed via pip directly is "1.1.1.dev0". However, the problem there is exactly the same.

**Comment by wd15** [comment]
@alpxp, this is not a solution, but the following Dockerfile worked for me recently, https://gist.github.com/wd15/85e7a8353d1454a9c8a6beb8629b591a. It installs PySparse from the guyer channel not from the PySparse repository

**Comment by alpxp** [comment]
@wd15, thank you for the suggestion. I followed the docker script, however the error is the same. The code still works fine with the "--scipy" flag.

> Python 2.7.13 |Anaconda custom (x86_64)| (default, Sep 21 2017, 17:38:20) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fipy, pysparse
>>> fipy.__version__
'3.1.3.dev138+gecbe868f'
>>> pysparse.__version__
'1.3-dev'
>>> fipy.__file__
'/Users/alpxp/anaconda2/tmp_src/fipy/fipy/__init__.pyc'
>>> pysparse.__file__
'/Users/alpxp/anaconda2/lib/python2.7/site-packages/pysparse/__init__.pyc'

**Comment by wd15** [comment]
@alpxp, thanks to @guyer, you should be able to get a working version of FiPy using,

     $ conda install --channel guyer --channel conda-forge python=2 fipy nomkl

that works in parallel.

**Comment by alpxp** [comment]
It turned out that fipy is working ok. I have an outdated/incorrect equation setup (as explained in #529 ), which for some reasons works in scipy, but not in pysparse. But I guess it is rather a problem of writing the terms correctly.
