### ISSUE TITLE
Can A Source Term Be Set by a lookup table

### ISSUE THREAD

**Issue by terryphi** [usnistgov/fipy#527]
Hi,

I have a table with X,Y,Z,t coordinates and values of a source term.

Is there a way I ccan get FiPy to look up the value of the source term for each cell during each itteration?

**Comment by guyer** [comment]
Probably easiest in your iteration loop to just explicitly assign the values, e.g.,

```python

x, y, z = mesh.cellCenters

mysource = fp.CellVariable(mesh=mesh)
  :
eq = fp.TransientTerm() == ... + mysource
  :
t = 0
for step in range(steps):
    mysource.setValue(lookup_in_table(x, y, z, t))
      :
    eq.solve(..., dt=dt)
    t += dt
```
