### ISSUE TITLE
scipy 1.0.0 incompatibilities

### ISSUE THREAD

**Issue by ohazi** [usnistgov/fipy#528]
There are some backwards incompatible changes in scipy 1.0.0, which was released on Oct 25. 

Specifically:
> The following deprecated keywords have been removed in scipy.sparse.linalg: **drop_tol** from **splu**, and xtype from bicg, bicgstab, cg, cgs, gmres, qmr and minres.

(from https://docs.scipy.org/doc/scipy//reference/release.1.0.0.html)

As a result, I'm seeing the following failure:
```
  solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ohazi/test.py", line 158, in thermal_diffusion_1d
    eq.solve(var=phi, dt=time)
  File "/usr/local/lib/python2.7/site-packages/fipy/terms/term.py", line 213, in solve
    solver._solve()
  File "/usr/local/lib/python2.7/site-packages/fipy/solvers/scipy/scipySolver.py", line 61, in _solve
    self.var[:] = numerix.reshape(self._solve_(self.matrix, self.var.ravel(), numerix.array(self.RHSvector)), self.var.shape)   
  File "/usr/local/lib/python2.7/site-packages/fipy/solvers/scipy/linearLUSolver.py", line 64, in _solve_
    permc_spec=3)
TypeError: splu() got an unexpected keyword argument 'drop_tol'
```

**Comment by guyer** [comment]
Thanks for letting us know. We'll work up a solution.

**Comment by alpxp** [comment]
I solved this by commenting out line 61 in fipy/solvers/scipy/linearLUSolver.py file:
```
LU = splu(L.matrix.asformat("csc"), diag_pivot_thresh=1.,
                                            #drop_tol=0.,
                                            relax=1,
                                            panel_size=10,
                                            permc_spec=3)
```

**Comment by ohazi** [comment]
Duplicate of #531

**Comment by guyer** [comment]
Oops!

**Comment by irbin-b** [comment]
> For anybody reading in 2018, the issue is actually solved in the development branch (not by me, just to be clear) but not in the version you get when installing via pip. You will have to clone from git, checkout development and build with python setup.py install

Does this solution work for python 3?

**Comment by AbsoluteStratos** [comment]
Because the github repo appears to be Python 2 and I'm using Python 3, I found that on a conda install (v 3.1.3) just manually editing line 61-ish of:
`/anaconda3/envs/fipy/lib/python3.6/site-packages/fipy/solvers/scipylinearLUSolver.py`
such that drop_tol is commented out (as seen in @alpxp comment). Seems this was deprecated in [scipy](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.linalg.splu.html) or just doesn't do anything.

**Comment by awa5114** [comment]
Are there any plans to update this library to python 3?

**Comment by guyer** [comment]
> Are there any plans to update this library to python 3? 

Yes

> Also could you provide instructions on how to get the development branch?

Like [this](https://www.ctcms.nist.gov/fipy/documentation/GIT.html)?
