### ISSUE TITLE
2D anisotropic convection-diffusion

### ISSUE THREAD

**Issue by alpxp** [usnistgov/fipy#529]
Would someone be so kind as to help me to arrange a 2D anisotropic convection-diffusion equation within the new fipy3 formulations. I have a code which runs well in fipy2. However It gives errors in fipy3 (with pysparse, the old version is still working well with scipy, see #522).

It is a simple convection-diffusion equation with space-dependent coefficients. So here is the gist of the version that worked in fipy2 and gives error #522 in fipy3 with pysparse:
```
mesh = fp.Grid2D(dx=dx, dy=dy, nx=p_size, ny=c_size)
mesh = mesh + [[0.001], [-1.0]]
x        = mesh.x; y = mesh.y
f = fp.CellVariable(mesh=mesh, value=0.0)

G = scipy.special.erf(x)
conv_x   = [-1.0, 0.0]                * (y + fp.numerix.sqrt(1.0 + x ** 2))
conv_y   = [0.0, -1.0]                * ((1.0 - y ** 2) / p)
D_x      = [[[1.0, 0.0], [0.0, 0.0]]  * G / x]
D_y      = [[[0.0, 0.0], [0.0, 1.0]]  * (x+y)]
eq = fp.TransientTerm() == (
                                                       fp.DiffusionTerm(coeff=D_y)+
                                                       fp.DiffusionTerm(coeff=D_x)+
                                                       fp.PowerLawConvectionTerm(coeff=conv_x)+
                                                       fp.PowerLawConvectionTerm(coeff=conv_y))

BCs = (fp.FixedFlux(faces=mesh.getFacesTop(), value=0.),
       fp.FixedFlux(faces=mesh.getFacesBottom(), value=0.),
...
eq.solve(var=f, boundaryConditions=BCs, dt=dt)
```
I simplified the coefficients as in the original code they are more complex and time-dependent, which is not relevant here.
So:
1) How do I write D_ and conv_ coefficients now. I understand that thay have to be fp.Variable now, but which one Cell/Face? Does it depend on "f = fp.CellVariable"? What would x and y be then? CellFaces/Centers?
(I have to say that I managed to write the D_ coefficient in such a way that fipy ran, however I'm not sure that is correct: "D_x = ([[1.0, 0.0], [0.0, 0.0]]  * G / x,)"   )
2) Since "FixedFlux=0" boundary condition was depreciated how do I reconcile the coefficients with f.constrain() at the boundary now?
3) I know I'm supposed to use "fp.numerix" for math. However numerix does not have erf. Is this ok G = scipy.special.erf(x)?
4) After this shift "mesh = mesh + [[0.001], [-1.0]]", I can't access "mesh.shape" property. Otherwise the mesh seem woking ok. Is this the correct way to generate a nonuniform mesh with an arbitrary origin?

**Comment by wd15** [comment]
I commented out the boundary conditions and everything seems to run with 73d780cd37d9. I have not idea what the answer should be. It just didn't give an error.

1. The `D_` and `conv_` seem to work and have the correct shape. They are both cell centered.

2. I used `f.faceGrad.constrain(0, mesh.exteriorFaces)` and it seemed to work. If this doesn't do it, then try implementing https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#applying-fixed-flux-boundary-conditions which will force the issue.

3. I think it's working okay. `x` doesn't change so there isn't a need to preserve it as a variable.

4. Works for me.

My code:

```
import fipy as fp
import scipy.special

p = 1.0
dt = 1.0
p_size = 10
c_size = 10
dx = 1.0
dy = 1.0
mesh = fp.Grid2D(dx=dx, dy=dy, nx=p_size, ny=c_size)
mesh = mesh + [[0.001], [-1.0]]
x = mesh.x
y = mesh.y
f = fp.CellVariable(mesh=mesh, value=0.0)

G = scipy.special.erf(x)
conv_x = [-1.0, 0.0] * (y + fp.numerix.sqrt(1.0 + x ** 2))
conv_y = [0.0, -1.0] * ((1.0 - y ** 2) / p)
D_x = [[[1.0, 0.0], [0.0, 0.0]] * G / x]
D_y = [[[0.0, 0.0], [0.0, 1.0]] * (x+y)]
eq = fp.TransientTerm() == (fp.DiffusionTerm(coeff=D_y) +
                            fp.DiffusionTerm(coeff=D_x) +
                            fp.PowerLawConvectionTerm(coeff=conv_x) +
                            fp.PowerLawConvectionTerm(coeff=conv_y))

f.faceGrad.constrain(0, mesh.exteriorFaces)

eq.solve(var=f, dt=dt)
```

**Comment by alpxp** [comment]
Is this working with 'pysparse'? 
This exact code gives me an error from #522 when I run it with --pysparse:
```
Traceback (most recent call last):
  File "./test_2017.py", line 25, in <module>
    eq.solve(var=f, dt=dt)
  File "/Library/Python/2.7/site-packages/fipy/terms/term.py", line 213, in solve
    solver._solve()
  File "/Library/Python/2.7/site-packages/fipy/solvers/pysparse/pysparseSolver.py", line 103, in _solve
    self._solve_(self.matrix, array, self.RHSvector)
  File "/Library/Python/2.7/site-packages/fipy/solvers/pysparse/linearLUSolver.py", line 102, in _solve_
    LU.solve(errorVector, xError)
TypeError: must be numpy.ndarray, not binOp

```
This is with 'pysparse.__version__ ='1.3-dev'' installed from a normal pip with `pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse` from #435 

I saw that instructions https://www.ctcms.nist.gov/fipy/INSTALLATION.html#requiredpackages were updated to recommend conda. I installed everything using conda (taking into account #525 ), i.e.:
```
conda install --force openblas=0.2.19 --channel guyer --channel conda-forge
conda install --channel guyer --channel conda-forge pysparse
conda install --channel guyer --channel conda-forge fipy
```
The error is almost exactly the same except a small difference in the last line:
`TypeError: argument 1 must be numpy.ndarray, not binOp
`
I also tried this code on a linux machine:
```
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fipy, pysparse
>>> fipy.__version__
'3.1'
>>> pysparse.__version__
'1.2-dev' 
```
with exactly the same error.

I wanted to point out that the code indeed runs ok in all three environments with "--scipy" key. But it becomes much slower... So I wanted to make it run with pysparse again.

**Comment by wd15** [comment]
On Wed, Nov 8, 2017 at 1:10 PM, alpxp <notifications@github.com> wrote:
>
> Is this working with 'pysparse'?

It does for me.

> This is with 'pysparse.version ='1.3-dev'' installed from a normal pip with pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse from #435

I'm also using "1.3-dev".

> I saw that instructions https://www.ctcms.nist.gov/fipy/INSTALLATION.html#requiredpackages were updated to recommend conda. I installed everything using conda (taking into account #525 ), i.e.:
>
> conda install --force openblas=0.2.19 --channel guyer --channel conda-forge
> conda install --channel guyer --channel conda-forge pysparse
> conda install --channel guyer --channel conda-forge fipy

I followed those instructions in a clean Conda environment and it
seems to work (no error).

> The error is almost exactly the same except a small difference in the last line:
> TypeError: argument 1 must be numpy.ndarray, not binOp
> I also tried this code on a linux machine:
>
> Python 2.7.9 (default, Jun 29 2016, 13:08:31)
> [GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import fipy, pysparse
> >>> fipy.__version__
> '3.1'
> >>> pysparse.__version__
> '1.2-dev'

That's not "1.3-dev"? If I follow the Conda instrcutions that you listed, I get,

>>> import fipy
>>> fipy.__version__
'3.1.3'
>>> import pysparse
>>> pysparse.__version__
'1.3-dev'
>>> pysparse.__path__
['/home/wd15/miniconda/envs/alpxp/lib/python2.7/site-packages/pysparse']
>>> fipy.__path__
['/home/wd15/miniconda/envs/alpxp/lib/python2.7/site-packages/fipy']

Maybe check that you're importing from the right paths.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
> Is this working with 'pysparse'?

It does for me.

> This is with 'pysparse.version ='1.3-dev'' installed from a normal pip with pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse from #435

I'm also using "1.3-dev".

> I saw that instructions https://www.ctcms.nist.gov/fipy/INSTALLATION.html#requiredpackages were updated to recommend conda. I installed everything using conda (taking into account #525 ), i.e.:
>
> conda install --force openblas=0.2.19 --channel guyer --channel conda-forge
> conda install --channel guyer --channel conda-forge pysparse
> conda install --channel guyer --channel conda-forge fipy

I followed those instructions in a clean Conda environment and it
seems to work (no error).

> The error is almost exactly the same except a small difference in the last line:
> TypeError: argument 1 must be numpy.ndarray, not binOp
> I also tried this code on a linux machine:
>
> Python 2.7.9 (default, Jun 29 2016, 13:08:31)
> [GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import fipy, pysparse
> >>> fipy.__version__
> '3.1'
> >>> pysparse.__version__
> '1.2-dev'

That's not `1.3-dev`? If I follow the Conda instructions that you listed, I get,

    >>> import fipy
    >>> fipy.__version__
    '3.1.3'
    >>> import pysparse
    >>> pysparse.__version__
     '1.3-dev'
    >>> pysparse.__path__
    ['/home/wd15/miniconda/envs/alpxp/lib/python2.7/site-packages/pysparse'] 
    >>> fipy.__path__
    ['/home/wd15/miniconda/envs/alpxp/lib/python2.7/site-packages/fipy']


Maybe check that you're importing from the right paths.
