### ISSUE TITLE
drop_tol argument to scipy.sparse.linalg.splu is gone

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#531]
As explained [on the mailing list](https://www.mail-archive.com/fipy@nist.gov/msg04096.html), the `drop_tol` argument to `scipy.sparse.linalg.splu` was deprecated and is now gone.

See [v0.19.1 `scipy.sparse.linalg.splu` docs](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/generated/scipy.sparse.linalg.splu.html)

**Comment by DarioPanada** [comment]
Just wanted to report that I did a clean install of FiPy via pip (pip install fipy) and the issue remains. Commenting out line 61 of linearLUSolver.py fixed it as per comment, but seems like the pre-fix code is still being distributed via pip? @guyer ?

**Comment by guyer** [comment]
@DarioPanada We have not yet pushed a new release

**Comment by DarioPanada** [comment]
@guyer fair enough, I'm new to the project so will have to familiarize with a lot of things. However, as it stands, Grid3D objects are unusable without manually editing the code

**Comment by pya** [comment]
How about a bug.fix release 3.1.4?
I had to delete the annoying line for bunch of installations already.

**Comment by guyer** [comment]
@DarioPanada I missed this
> Grid3D objects are unusable without manually editing the code

What do Grid3D objects have to do with scipy `splu`?

**Comment by guyer** [comment]
@pya We're trying to get a release out (although it will be another few weeks, as I'm leaving on vacation). 

- A "release" (even a "bug-fix release") is non-trivial.
- Checking out the develop branch on the other hand...

**Comment by DarioPanada** [comment]
@guyer I encountered the issue when trying to solve using a Grid3D environment. It might be 2D and 1D grids are affected too, I didn't try. Hence, why I restricted my comment to Grid3D
