### ISSUE TITLE
pip or conda installation don't make clear where to get examples

### ISSUE THREAD

**Issue by misterwazlib** [usnistgov/fipy#533]
Hello,

I'm new to FiPY and I tried installing it using pip install. However after the installation process is completed, I can't find the "Examples" folder in the directory. Is it normal or have I gotten it wrong? How do I find and run the examples codes otherwise?

Thanks for your help!

Dio

**Comment by wd15** [comment]
@misterwazlib, if you "pip install" FiPy, then you won't get the "Examples" directory. You can only get that by cloning the repository or downloading a tarball. 

Just a warning, but I'm not sure how well "pip install" actually works for FiPy. I would recommend installing using Conda with

    $ conda install --channel guyer fipy

@guyer, does the above now work from your Conda channel.

**Comment by misterwazlib** [comment]
Hi @wd15 ,

thanks for your reply. I tried your recommendations but the installation failed.

![image](https://user-images.githubusercontent.com/34139043/33571235-b961cdde-d92f-11e7-91bf-6d0d842483dc.png)

 Is there perhaps another channel I could try?

**Comment by guyer** [comment]
Please try
```
conda install --channel guyer --channel conda-forge fipy nomkl
```
(see https://www.ctcms.nist.gov/fipy/INSTALLATION.html#recommended-method)
