### ISSUE TITLE
inclusive license

### ISSUE THREAD

**Issue by tkphd** [usnistgov/fipy#555]
Harmonize LICENSE with https://www.nist.gov/director/licensing

**Comment by toddrme2178** [comment]
What is the reason this is marked as "wontfix"?  The license doesn't seem to match any of the licenses provided by the NIST, or any other commonly-used open-source license I can find.  I would like to package this for openSUSE, but this is very difficult when the software uses a non-standard license.  It is marked on PyPi as being "public domain", but although IANAL the last paragraph seems to add requirements on top of it being in the public domain.

**Comment by guyer** [comment]
@toddrme2178: The short answer is that I don't know. I certainly don't know why I bothered marking `wontfix` 6 months after @tkphd closed the issue.

Our "license" certainly doesn't agree with what the current NIST language, although it certainly did at one time. I am investigating.
