### ISSUE TITLE
Cylindrical grid

### ISSUE THREAD

**Issue by GJBoth** [usnistgov/fipy#562]
When instantiating a 2d cylindrical mesh, I can only call 'CylindricalGrid2D'; it works, but I can't find any trace of this in the code. CylindricalGrid2D.py says this is depecrated, so where does this call too?

3 further questions:
1) If i create an offset 1D cylindrical mesh, would this create a ring like geometry in the radial direction?
If not,
1) How hard would it be to modify the 2dcylindericalmesh to something accomodating a 2d ring?
2) If not too hard, where would I start? The code is not very clear to me.

**Comment by guyer** [comment]
0. `CylindricalGrid2D` is a factory function defined [here](https://github.com/usnistgov/fipy/blob/654426c7d472712b628af057ec493d55b9812fbf/fipy/meshes/factoryMeshes.py#L195). The deprecated code in `fipy/meshes/cylindricalGrid2D.py` reflects an older architecture of FiPy that we should purge altogether now.

1. Yes
