### ISSUE TITLE
Wrong facevalue when using Neumann BC

### ISSUE THREAD

**Issue by profgerto** [usnistgov/fipy#563]
Using harmonic or arithmetic facevalue to determine the value of the solution on a boundary with Neumann boundary conditions does not give back the right result; it seems to return the cellvalue of its cell.

**Comment by wd15** [comment]
@profgerto, FiPy doesn't extrapolate to the boundaries mainly because it's not needed for FiPy's internals. See this,

http://fipy.nist.narkive.com/RzOHy0p5/incorrect-face-value-for-neumann-boundaries

**Comment by guyer** [comment]
And this:

https://gist.github.com/guyer/6b7699531f75b353f49a0cf36d683aa4

Yes, this needs to go into the documentation: #560
