### ISSUE TITLE
Support for GPU solvers using pyamgx

### ISSUE THREAD

**Issue by shwina** [usnistgov/fipy#566]
The NVIDIA [AmgX](https://github.com/NVIDIA/AMGX) library provides GPU-accelerated sparse solvers. I'm working on [pyamgx](https://github.com/shwina/pyamgx/), a Python interface to AmgX.

Here is a demo of how `pyamgx` can be used to accelerate FiPy:

https://github.com/shwina/pyamgx/blob/master/examples/FiPy/diffusion.ipynb

TL; DR: For the simple cases of 2D steady-state and transient diffusion, the GPU-accelerated AmgX library can provide upto 3x speedup over SciPy/PyAMG.

Using `pyamgx`, it would be trivial to add AmgX to the list of sparse packages supported by FiPy.

Do you think this addition would be welcome to FiPy?

Any feedback is appreciated! Thanks!

**Comment by guyer** [comment]
Yes! This contribution would be most welcome.

**Comment by tkphd** [comment]
Really nice demonstration code. Thanks for bringing pyamgx to our attention, @shwina. Looking forward to your pull request!
