### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by vrossum** [usnistgov/fipy#588]
Hi

Sorry for these beginner questions, but I wonder if someone can help me with installing on Debian.
> conda create --name fipy --channel guyer --channel conda-forge fipy nomkl
> conda activate fipy

complete without error.
But when I try to run an example, it can't find a solver

> python fipy/fipy-develop/examples/diffusion/mesh1D.py
fipy/lib/python3.6/site-packages/fipy/solvers/__init__.py:116: UserWarning: Could not import any solver package
.... ModuleNotFoundError: No module named 'pysparse'
During handling of the above exception, another exception occurred:
... ModuleNotFoundError: No module named 'PyTrilinos'

I thought that fipy would default to use the Scipy solver.

Pysparse seems unsupported and has issues like reported in
https://sourceforge.net/p/pysparse/mailman/message/33117282/

Many thanks in advance,

**Comment by guyer** [comment]
Unfortunately, in the course of making the conda packages supporting FiPy fully functional across platforms, the installation instructions for FiPy became out of date. A new release of FiPy entails making sure everything works right and making everything work right sometimes entails rendering the instructions obsolete. I don't know how to prevent this other than to minimize how long things are out of sync (which I did not succeed in doing this time).

Because of something broken in conda, the `fipy` recipe does not install FiPy's prerequisites on linux. Please use:
```
conda create --name <FIPYENV> --channel guyer --channel conda-forge python=2.7 numpy scipy gmsh pysparse mpi4py matplotlib mayavi fipytrilinos weave
```

**Comment by vrossum** [comment]
Thanks.
Actually, fipy itself needs to be added to that list, but then it works.

**Comment by guyer** [comment]
@vrossum: True enough. I'd pulled that from our Travis recipe where we get the fipy code from github.

**Comment by ACamposG** [comment]
I tried the recipe above, including fipy package, but I got some error during execution, below the whole installation process verbose:

campos26@bicephalous:~$ conda create --name fippy27 --channel guyer --channel conda-forge python=2.7 numpy scipy gmsh pysparse mpi4py matplotlib mayavi fipytrilinos weave fipy
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/campos26/miniconda3/envs/fippy27

  added / updated specs: 
    - fipy
    - fipytrilinos
    - gmsh
    - matplotlib
    - mayavi
    - mpi4py
    - numpy
    - pysparse
    - python=2.7
    - scipy
    - weave


The following NEW packages will be INSTALLED:

    apptools:                      4.4.0-py27_1002                       conda-forge
    atk:                           2.25.90-hb9dd440_1002                 conda-forge
    backports:                     1.0-py_2                              conda-forge
    backports.functools_lru_cache: 1.5-py_1                              conda-forge
    backports_abc:                 0.5-py_1                              conda-forge
    binutils_impl_linux-64:        2.31.1-h6176602_1                     conda-forge
    binutils_linux-64:             2.31.1-h6176602_3                     conda-forge
    blas:                          1.1-openblas                          conda-forge
    bsddb:                         1.0-py27_1                                       
    bzip2:                         1.0.6-h14c3975_1002                   conda-forge
    ca-certificates:               2018.11.29-ha4d7672_0                 conda-forge
    cairo:                         1.16.0-ha4e643d_1000                  conda-forge
    certifi:                       2018.11.29-py27_1000                  conda-forge
    configobj:                     5.0.6-py_0                            conda-forge
    curl:                          7.64.0-h646f8bb_0                     conda-forge
    cycler:                        0.10.0-py_1                           conda-forge
    db:                            5.3.28-1                                         
    dbus:                          1.13.0-h4e0c4b3_1000                  conda-forge
    envisage:                      4.7.1-py_0                            conda-forge
    expat:                         2.2.5-hf484d3e_1002                   conda-forge
    fipy:                          3.1.3-py27_11                         guyer      
    fipytrilinos:                  12.10.1-np112py27_1                   guyer      
    fontconfig:                    2.13.1-h2176d3f_1000                  conda-forge
    freeimage:                     3.17.0-0                              conda-forge
    freetype:                      2.9.1-h94bbf69_1005                   conda-forge
    functools32:                   3.2.3.2-py_3                          conda-forge
    future:                        0.17.1-py27_1000                      conda-forge
    futures:                       3.2.0-py27_1000                       conda-forge
    gcc_impl_linux-64:             7.3.0-habb00fd_1                      conda-forge
    gcc_linux-64:                  7.3.0-h553295d_3                      conda-forge
    gdk-pixbuf:                    2.36.12-h49783d7_1002                 conda-forge
    gettext:                       0.19.8.1-h9745a5d_1001                conda-forge
    glib:                          2.58.2-hf63aee3_1001                  conda-forge
    gmp:                           6.1.2-hf484d3e_1000                   conda-forge
    gmsh:                          3.0.6-he2a7a22_2                      conda-forge
    gobject-introspection:         1.56.1-py27h2da5eee_1002              conda-forge
    graphite2:                     1.3.13-hf484d3e_1000                  conda-forge
    gstreamer:                     1.14.4-h66beb1c_1001                  conda-forge
    gtk2:                          2.24.31-hb68c50a_1001                 conda-forge
    gxx_impl_linux-64:             7.3.0-hdf63c60_1                      conda-forge
    gxx_linux-64:                  7.3.0-h553295d_3                      conda-forge
    harfbuzz:                      2.3.1-h6824563_0                      conda-forge
    hdf4:                          4.2.13-h9a582f1_1002                  conda-forge
    hdf5:                          1.10.4-nompi_h11e915b_1105            conda-forge
    icu:                           58.2-hf484d3e_1000                    conda-forge
    jpeg:                          9c-h14c3975_1001                      conda-forge
    jsoncpp:                       1.8.4-h6bb024c_1001                   conda-forge
    kiwisolver:                    1.0.1-py27h6bb024c_1002               conda-forge
    krb5:                          1.16.3-hc83ff2d_1000                  conda-forge
    libcurl:                       7.64.0-h01ee5af_0                     conda-forge
    libedit:                       3.1.20170329-hf8c457e_1001            conda-forge
    libffi:                        3.2.1-hf484d3e_1005                   conda-forge
    libgcc-ng:                     7.3.0-hdf63c60_0                      conda-forge
    libgfortran:                   3.0.0-1                               conda-forge
    libgfortran-ng:                7.2.0-hdf63c60_3                      conda-forge
    libiconv:                      1.15-h14c3975_1004                    conda-forge
    libnetcdf:                     4.6.2-hbdf4f91_1001                   conda-forge
    libogg:                        1.3.2-h14c3975_1001                   conda-forge
    libpng:                        1.6.36-h84994c4_1000                  conda-forge
    libssh2:                       1.8.0-h1ad7b7a_1003                   conda-forge
    libstdcxx-ng:                  7.3.0-hdf63c60_0                      conda-forge
    libtheora:                     1.1.1-h14c3975_1001                   conda-forge
    libtiff:                       4.0.10-h648cc4a_1001                  conda-forge
    libuuid:                       2.32.1-h14c3975_1000                  conda-forge
    libvorbis:                     1.3.5-h14c3975_1001                   conda-forge
    libxcb:                        1.13-h14c3975_1002                    conda-forge
    libxml2:                       2.9.8-h143f9aa_1005                   conda-forge
    lz4-c:                         1.8.1.2-0                             conda-forge
    matplotlib:                    2.2.3-py27h8a2030e_1                  conda-forge
    matplotlib-base:               2.2.3-py27h60b886d_1                  conda-forge
    mayavi:                        4.6.2-py27h18b3941_1                  conda-forge
    mpi:                           1.0-mpich                             conda-forge
    mpi4py:                        3.0.0-py27hf046da1_1005               conda-forge
    mpich:                         3.2.1-h1c2f66e_1008                   conda-forge
    ncurses:                       6.1-hf484d3e_1002                     conda-forge
    numpy:                         1.12.1-py27_blas_openblash24bf2e0_201 conda-forge [blas_openblas]
    occt:                          7.3.0-hb84612a_1001                   conda-forge
    openblas:                      0.2.20-8                              conda-forge
    openssl:                       1.0.2p-h14c3975_1002                  conda-forge
    pango:                         1.40.14-h4ea9474_1004                 conda-forge
    pcre:                          8.41-hf484d3e_1003                    conda-forge
    pip:                           19.0.3-py27_0                         conda-forge
    pixman:                        0.34.0-h14c3975_1003                  conda-forge
    pthread-stubs:                 0.4-h14c3975_1001                     conda-forge
    pyface:                        6.0.0-py_1                            conda-forge
    pygments:                      2.3.1-py_0                            conda-forge
    pyparsing:                     2.3.1-py_0                            conda-forge
    pyqt:                          5.6.0-py27h13b7fb3_1008               conda-forge
    pysparse:                      1.3.dev-py27h3010b51_1002             conda-forge
    python:                        2.7.15-h938d71a_1006                  conda-forge
    python-dateutil:               2.8.0-py_0                            conda-forge
    pytrilinos:                    12.10.1-py27h7127e17_2                conda-forge
    pytz:                          2018.9-py_0                           conda-forge
    qt:                            5.6.2-hce4f676_1013                   conda-forge
    readline:                      7.0-hf8c457e_1001                     conda-forge
    scipy:                         1.1.0-py27_blas_openblash7943236_201  conda-forge [blas_openblas]
    setuptools:                    40.8.0-py27_0                         conda-forge
    singledispatch:                3.4.0.3-py27_1000                     conda-forge
    sip:                           4.18.1-py27hf484d3e_1000              conda-forge
    six:                           1.12.0-py27_1000                      conda-forge
    sqlite:                        3.26.0-h67949de_1000                  conda-forge
    subprocess32:                  3.5.3-py27h14c3975_0                  conda-forge
    tbb:                           2019.3-h6bb024c_1000                  conda-forge
    tk:                            8.6.9-h84994c4_1000                   conda-forge
    tornado:                       5.1.1-py27h14c3975_1000               conda-forge
    traits:                        5.0.0-py27h14c3975_0                  conda-forge
    traitsui:                      6.0.0-py_1                            conda-forge
    vtk:                           8.1.2-py27h8cc7ba1_1200               conda-forge
    weave:                         0.16.0-py27h8619c78_1000              conda-forge
    wheel:                         0.33.1-py27_0                         conda-forge
    xorg-fixesproto:               5.0-h14c3975_1002                     conda-forge
    xorg-inputproto:               2.3.2-h14c3975_1002                   conda-forge
    xorg-kbproto:                  1.0.7-h14c3975_1002                   conda-forge
    xorg-libice:                   1.0.9-h14c3975_1004                   conda-forge
    xorg-libsm:                    1.2.3-h4937e3b_1000                   conda-forge
    xorg-libx11:                   1.6.7-h14c3975_1000                   conda-forge
    xorg-libxau:                   1.0.9-h14c3975_0                      conda-forge
    xorg-libxdmcp:                 1.1.2-h14c3975_1007                   conda-forge
    xorg-libxext:                  1.3.3-h14c3975_1004                   conda-forge
    xorg-libxfixes:                5.0.3-h14c3975_1004                   conda-forge
    xorg-libxi:                    1.7.9-h14c3975_1002                   conda-forge
    xorg-libxmu:                   1.1.2-h14c3975_1002                   conda-forge
    xorg-libxrender:               0.9.10-h14c3975_1002                  conda-forge
    xorg-libxt:                    1.1.5-h14c3975_1002                   conda-forge
    xorg-renderproto:              0.11.1-h14c3975_1002                  conda-forge
    xorg-xextproto:                7.3.0-h14c3975_1002                   conda-forge
    xorg-xproto:                   7.0.31-h14c3975_1007                  conda-forge
    xz:                            5.2.4-h14c3975_1001                   conda-forge
    zlib:                          1.2.11-h14c3975_1004                  conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: | dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id

done
#
# To activate this environment, use
#
#     $ conda activate fippy27
#
# To deactivate an active environment, use
#
#     $ conda deactivate

campos26@bicephalous:~$ 

Now,  after activating the new environment, and when trying to import fipy from python shell I got an error message:

ImportError: dynamic module does not define init function (initmultiarray)

I guess it is related with the execution error, how can I fix it?  I have tried to install the packages one by one and get the same error. Please help.

**Comment by guyer** [comment]
Sorry for the delay in responding to this. Those instructions  are obsolete and  I've been struggling to get the conda installation working robustly. Your getting this error because the particular version of numpy that was installed, 1.12, is too old. As to why, I don't know, but probably because of my obsolete `fipytrilinos` recipe.

As  of now you should do
```
conda create -n <FIPYENV> --channel conda-forge python=2.7 fipy
```
which should give you a clean environment with an up-to-date numpy.

**Comment by ACamposG** [comment]
Thanks John, I appreciate your help.
