### ISSUE TITLE
No module named pyAMGSolver

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#590]
[edit: I was mixing up `pyAMG` (ancient) and `pyamgx` (new)]

`fipy.solvers.pyAMG.smoothedAggregationSolver` [makes an undefined import](https://github.com/usnistgov/fipy/blob/develop/fipy/solvers/pyAMG/smoothedAggregationSolver.py#L53).

I can't tell whether `SmoothedAggregationSolver` needs a different base class, if there's something missing from the module, or if this bit of code isn't functional.

**Comment by wd15** [comment]
@guyer, I can't really remember. Maybe there were redundancies between the pyamg and scipy solver classes so I was trying to merge them? I probably just overlooked the SmoothedAggregationSolver. I'll try and fix it then.

**Comment by wd15** [comment]
@guyer, actually, I don't think the SmoothedAggregationSolver is needed since there is SmoothedAggregationPreconditioner which is actually what is used. I'm just going to delete it.
