### ISSUE TITLE
Can't run basic test or examples

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#603]
Hello,
I successfully installed FiPy on windows but I can't run any of the examples. I ran the script "test.py" in "examples" folder and I get this at the end:

Exception raised:
    Traceback (most recent call last):
      File "C:\anaconda3\envs\FiPy-3.1.3\lib\doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest reactiveWetting.liquidVapor2D[52]>", line 25, in <module>
        residual = coupledEqn.sweep(dt=dt)
      File "C:\anaconda3\envs\FiPy-3.1.3\lib\site-packages\fipy\terms\term.py",
line 254, in sweep
        solver._solve()
      File "C:\anaconda3\envs\FiPy-3.1.3\lib\site-packages\fipy\solvers\scipy\sc
ipySolver.py", line 61, in _solve
        self.var[:] = numerix.reshape(self._solve_(self.matrix, self.var.ravel()
, numerix.array(self.RHSvector)), self.var.shape)
      File "C:\anaconda3\envs\FiPy-3.1.3\lib\site-packages\fipy\solvers\scipy\li
nearLUSolver.py", line 64, in _solve_
        permc_spec=3)
    TypeError: splu() got an unexpected keyword argument 'drop_tol'

----------------------------------------------------------------------
Ran 192 tests in 36.426s

FAILED (failures=65, errors=3)

What could be wrong ? Maybe it's not using the right version of Python ? For the install command on windows, I had to specify "python=2.7" for it to install without error. Please help !
Thanks

**Comment by guyer** [comment]
This issue (#531) has been fixed on our develop branch. We're not quite ready to push out a release on that, but hopefully very soon. In the meantime, you can [get the latest code with git](https://www.ctcms.nist.gov/fipy/documentation/GIT.html).

**Comment by guyer** [comment]
@dtwright03:

* What operating system are you running?
* What working directory are you in when you run the script?
  - `pwd`
* Did you install your clone or are you running from within the repository directory?
* What branch are you on?
  - `git status`

**Comment by dtwright03** [comment]
**Windows 10
**Everything located in anaconda base directory (I removed my virtual environment due to difficulties within my office network, seem to be getting closer with everything in the base dir)
**Clone installed with `pip setup.py install` (I tried a conda install, but it removed anaconda during install..)
**On branch master

**Comment by guyer** [comment]
Please switch to branch `develop` and reinstall.
