### ISSUE TITLE
Anisotropy example: Contour plot displaying in legend of figure !?

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#610]
Hi,
When running the anisotropy example in Fipy-3.1.3 (installed with conda on ubuntu 18.04), the contour plot of the dendrite is squeezed inside the legend part of the figure on top of the Delta T legend, and does not display within the figure image as expected :

![figure_1](https://user-images.githubusercontent.com/33491656/47953982-f1c9a000-df84-11e8-8ee4-b5a4095e9f3d.png)

What could be causing this ? Do I need to update to the developer branch version ?

**Comment by guyer** [comment]
Yes, this issue has been fixed on the `develop` branch.
I believe commit b2ab0725 is what made the difference.

**Comment by oliverstefanov** [comment]
Indeed applying this change makes it work just fine, thanks!
