### ISSUE TITLE
The coefficient cannot be a FaceVariable ??

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#611]
Hi,
I'm trying to develop some phase field models involving anisotropy, thus involving the calculation of a phase field angle w.r.t. some axis.

In a first model, I'm calculating theta as arctan2(phase.faceGrad[1],phase.faceGrad[0]), which lets me calculate an anisotropic diffusion coefficient. The equation is smthg like TransientTerm = DiffusionTerm(coeff=D(theta), var=phase) + other terms

So far, so good, this works just fine.

BUT on another model, using the same approach, I get the following type error (even when removing extra terms) :

File "/home/.../fipy-develop/lib/python2.7/site-packages/FiPy-unknown-py2.7.egg/fipy/terms/cellTerm.py", line 74, in __init__
    raise TypeError, "The coefficient can not be a FaceVariable."
TypeError: The coefficient can not be a FaceVariable.

In this case, it works only if I use theta = arctan2(phase.grad[1],phase.grad[0])...even using the exact same (simplified) phase equation...and the diffusion coeff is otherwise calculated exactly the same way...strange uh?

I tried with fipy3.1.3 and fipy-develop and i get the same result.

Any idea of what is going on ?

For variables like diffusion coefficients, quantities like theta should be calculated at Faces rathers than Cell centers, right? So the first equation for theta is "more correct"?

**Comment by oliverstefanov** [comment]
Ok so I found the issue. In the second case, I had included a theta dependent coefficient for the transient term, thus requiring theta to be a cell variable...

**Comment by guyer** [comment]
Glad you figured it out.
