### ISSUE TITLE
How to define a spatially varying source term?

### ISSUE THREAD

**Issue by risewisun** [usnistgov/fipy#616]
I want use Fipy to solve an electric field problem. In this issue, the charge in some area is zero, in other area is varyed with solved potential. So I need define a  spatially varying source term. But the sample files didn't contain this type. So I hope to get some suggest! Wait for your help!

**Comment by wd15** [comment]
Here is an example of a spatially varying source term.

```
import fipy
mesh = fipy.Grid1D(nx=100, Lx=1.)
eq = fipy.DiffusionTerm() + mesh.x
var = fipy.CellVariable(mesh=mesh)
var.faceValue.constrain(0, where=mesh.exteriorFaces)
eq.solve(var)
print(var)
print(mesh.x / 6. - mesh.x**3 / 6.)
```

FiPy source terms can be a function of spatial location defined by `mesh.x` or `mesh.y` for a 2D problem.

**Comment by guyer** [comment]
Please reopen if you still have questions
