### ISSUE TITLE
Adaptive Mesh Refinement with FiPy ?

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#618]
Has there been any attempts out there to perform some Adaptive Mesh Refinement with FiPy, particularly for phase field modelling where the mesh is refined near the interface ? 

I'd be interested to know how it can be best implemented. Could this be approached with Gmsh scripting in FiPy?

**Comment by guyer** [comment]
We've made occasional attempts at this, but nothing fruitful. Using gmsh to regenerate the mesh and then reinterpolating the data is hopelessly inefficient (I've done it for quasi-static problems). I'll try to dig up some examples, even though I don't recommend this path.

Properly, FiPy should be integrated with libmesh or some other dedicated adaptive mesher; I'd like this to happen, but thus far, the fundamental architectures of FiPy and the meshers I've looked at are just too dissimilar.

**Comment by oliverstefanov** [comment]
Ok i see thanks. Regarding mesh libraries, I came across the Paramesh library recently, coded in F90 and made to extend existing code to perform AMR. You probably already know about it, but if not it might be worth looking at

**Comment by guyer** [comment]
Thanks for the link. I don't recall whether that's one I considered or not.

**Comment by oliverstefanov** [comment]
You're welcome.

Do you think I need adaptive meshing to be able to accurately simulate phase field model like the well-known Echebarria model (https://journals.aps.org/pre/abstract/10.1103/PhysRevE.70.061604) on a small scale with a good desktop computer in reasonable time ?

I have a fipy code for this model, i think the implementation is finally correct, but i still struggle to obtain satisfying results such as beautiful dendrites, as found in the literature. Not sure if it's a problem with solidification parameters / noise level, or if it's due to the mesh. Indeed  I read that adaptive meshing helps getting nicely defined microstructure, which gets smeared on a more uniform mesh.

It seems you contributed to a publication using this model so you might have some insight?

**Comment by guyer** [comment]
FiPy was developed for phase field in the first place and has successfully done so, including on desktop computers. I don't think we've ever implemented the Echebarria model, but we've certainly done other dendrite problems (the publications that I was on using that model used a code my postdoc brought with him from his work with Plapp and Karma).

Adaptivity certainly can help with phase field problems, and dendrite especially, where you have a lot of interface area, but not much interface volume. Adaptivity brings its own algorithmic and computational challenges, though; if you're not careful, you just reproduce the Stefan problem that phase field methods are intended to avoid.

I would recommend first that you systematically test your implementation against the predictions of the Echebarria paper (which doesn't show any "beautiful dendrites" of it's own, but rather characterizes a lot of convergence and scaling issues that are important to get right). We're all tempted to rush ahead to the problem we really want to do, but in my experience that's a good way to wander around not being sure what's going on. The systematic steps are boring, but critical.

Finally, dendrites are hard to get right: https://doi.org/10.1016/j.commatsci.2018.03.015

**Comment by oliverstefanov** [comment]
Thank you very much for your input and for the link. Maybe I'll restart with the model in that paper as it is a bit simpler than Echebarria's, and compare their benchmarks with results from fipy solvers. Indeed I've wandered around quite a bit with various quantitative PF models without ever being fully certain that the implementation and parameters are correct. And simulation results being dependent on the solver certainly complicates things...
If you have a link to some paper or, even better, some code using FiPy for solidification problems (besides the fipy examples included with the code), I'd gladly take it. Most papers I found thus far used another framework or some in-house code

**Comment by wd15** [comment]
I've solved the dendrite benchmark ([spec](https://pages.nist.gov/pfhub/benchmarks/benchmark3.ipynb/) and [results](https://pages.nist.gov/pfhub/simulations/3a.1/)) using FiPy. The code is [here](https://gist.github.com/wd15/7e06a3141a6fbf317b1daf39ef1b0fbb). There are also plenty of other uploads for the dendrite benchmark, however, the code might not be necessarily available for all of them.

**Comment by oliverstefanov** [comment]
Ok thank you very much for the links, it's very helpful ! I wasn't aware of the PFHub page

**Comment by wd15** [comment]
Feel free to try some of the benchmarks and upload your results.

**Comment by oliverstefanov** [comment]
Noted. I looked at your dendrite code, it's nicely written. I learned about the use of pipe, lambda, toolz (still a bit confused on this one), and functions to build the equations etc...Is there a specific reason to do it this way (performance? elegance?) instead of a more crude, straightforward approach ?

Also I see you chose GMRES as a solver. I was using standard PCG in my codes but it seems GMRES is a better choice indeed for these problems.

**Comment by guyer** [comment]
It's written that way because @wd15 has an unhealthy obsession with functional programming. None of it is necessary.

**Comment by wd15** [comment]
On Thu, Feb 7, 2019 at 6:03 AM oliverstefanov <notifications@github.com> wrote:
>
> Noted. I looked at your dendrite code, it's nicely written. I learned about the use of pipe, lambda, toolz (still a bit confused on this one), and functions to build the equations etc...Is there a specific reason to do it this way (performance? elegance?) instead of a more crude, straightforward approach ?

It's just a style of programming. It shouldn't influence performance.

> Also I see you chose GMRES as a solver. I was using standard PCG in my codes but it seems GMRES is a better choice indeed for these problems.

It might be for the dendrite problem as the matrix might be asymmetric
(Jon, is that correct?). I don't think PCG works for asymmetric
matrices.

-- 
Daniel Wheeler

**Comment by guyer** [comment]
There's no convection, but there's an anisotropic diffusion coefficient, so I'd assume the matrix is asymmetric, but don't know for sure.

**Comment by oliverstefanov** [comment]
> It's written that way because @wd15 has an unhealthy obsession with functional programming. None of it is necessary.

I see, I always wondered what functional programming was about. Now I have a good example !

Regarding the solver, I observe that PCG usually runs on PF models with anisotropy, unlike LU. But this is strange since, as you said, one would think that the anisotropic diffusion should break the symmetry of the matrix.

Maybe I have issues in my implementation, although I'd expect at least the anisotropic diffusion term to be correct as I followed the approach from the anisotropy.py demo. And I note that this demo also uses the default PCG solver despite the anisotropy.

Or maybe the preconditionner makes the overall matrix symmetric? Doubtful though

Or the matrix of the system is in fact symmetrical despite anisotropy...Not sure how to check that for sure

**Comment by guyer** [comment]
Please reopen if you still have questions
