### ISSUE TITLE
Unstable steady state equation for Monod kinetics

### ISSUE THREAD

**Issue by matthsims** [usnistgov/fipy#649]
I would like to solve a steady-state diffusion reaction equation for biomass substrate utilization with a source term that looks like: `- q * B * phi / (phi + K)`, where `B` is the biomass, `q` is a rate, and `K` is the half saturation constant (Monod kinetics). For now, I am trying to solve this in one dimension.

For a minimal example, I have:

``` python
from fipy import CellVariable, Grid1D,Viewer, TransientTerm, DiffusionTerm
from fipy.tools import numerix

size, dl, q = 100, 3e-6, 14.1
Ds, Ks = 1e-4, 5.8e-4
order = 2
dt = dl ** 2 / (2 * Ds)

mesh = Grid1D(dx=dl, nx=size)
phi_s = CellVariable(name='substrate', mesh=mesh, hasOld=True)
B = CellVariable(name='biomass', mesh=mesh)

B.value[-10:] = 1000
phi_s.constrain(1, mesh.facesLeft)
reactions = - q * B * (phi_s / (phi_s + Ks))

phi_s.setValue(numerix.linspace(1, 0, size))
equation = DiffusionTerm(coeff=Ds) + reactions == 0
for steps in range(3):
    res = equation.sweep(var=phi_s)
    while res > 1e-4:
        print(phi_s.value[::20])
        res = equation.sweep(var=phi_s)
    phi_s.updateOld()
```
After the first set of sweeps, the value for phi_s goes below zero, which shouldn't happen. As phi approaches zero, that term should go to zero rather than going negative.

Is there a way to force the CellVariable to be positive. Otherwise, I'd guess I'm not quite solving this correctly, do you have any suggestions?

edit: Sorry, hit return when I was composing the message elsewhere. Closed for now, opening when it is prepared.
edit 2: Opened.

**Comment by guyer** [comment]
The  reason `phi_s` goes below zero is  because you've listed your reaction term explicitly, so it  has the strength of the initial value, rather than the strength of the instantaneous solution. I've posted the changes I made to [this gist](https://gist.github.com/guyer/aa70cb08ac386f1d64f1f93f4890e54d/revisions).

The primary changes I made were:
- change the explicit reaction term to an `ImplicitSourceTerm`
- removed time stepping since this is quasistatic

With these changes, `phi_s` remains non-negative and I get
```
[0.9997228  0.98863477 0.97754673 0.9664587  0.95537066]
[0.99716442 0.88374118 0.77031795 0.65689472 0.54347148]
[0.99808044 0.9212981  0.84451575 0.76773341 0.69095107]
[0.99768502 0.90508596 0.81248689 0.71988782 0.62728876]
[0.99784399 0.91160353 0.82536307 0.73912262 0.65288216]
[0.99777813 0.90890326 0.8200284  0.73115353 0.64227867]
[0.99780508 0.91000842 0.82221176 0.7344151  0.64661844]
[0.997794   0.90955382 0.82131364 0.73307347 0.64483329]
[0.99779855 0.90974043 0.82168232 0.7336242  0.64556609]
[0.99779668 0.90966376 0.82153085 0.73339794 0.64526502]
```

**Comment by matthsims** [comment]
Thank you, I've put together a solver that nicely fits my needs. Great piece of software.

**Comment by guyer** [comment]
Happy to help
