### ISSUE TITLE
Issues Scaling Colorbar with Datamin and Datamax Args

### ISSUE THREAD

**Issue by kdreyer3196** [usnistgov/fipy#662]
When I run the code for "examples.diffusion.mesh20x20" (using Python 3.7) the viewer has a color bar scaled from -1 to 1, despite the line of code where the datamin and datamax are specified, i.e.,
viewer = Viewer(vars=phi, datamin=0., datamax=1.)

Any insights on how to scale the color bar effectively?
![Diffusion_20x20](https://user-images.githubusercontent.com/52251969/62240846-7d018600-b39d-11e9-8535-4164a6fa99a8.png)

**Comment by guyer** [comment]
I can't reproduce this behavior, but I do get warnings that some of the matplotlib arguments have changed recently.

please post the result of:
```
python -c "import matplotlib; print(matplotlib.__version__); print(matplotlib.get_backend())"
```

**Comment by tkphd** [comment]
If the simulation was generating data on [0, 1], the output would be as you expect. You can experiment with this by setting the `datamin` and `datamax` values to different values: as long as the data falls within the range, the provided values are used. But if real data falls out of range, the colorbar is re-scaled to capture it.

The colorbar is scaling to the actual data, which spans `[-1, 1]`. Since the data falls below 0, the viewer appropriately ignores the `datamin` value in this case in order to show the simulation output. Since there's no "obvious" alternative way to represent data that has fallen outside of the provided range, this behavior (ignoring what the user provided) is the most-correct available.

**Comment by tkphd** [comment]
Confirmed, on Debian 9 and conda-installed FiPy 3.3: the colorbar appears to ignore the specified visualization limits.

```
fipy/viewers/matplotlibViewer/matplotlibViewer.py:229: MatplotlibDeprecationWarning:
The set_norm function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_norm instead.
  self._cb.set_norm(value)
fipy/viewers/matplotlibViewer/matplotlibViewer.py:240: MatplotlibDeprecationWarning: 
The set_norm function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_norm instead.
  self._cb.set_norm(self.viewer.norm)
```

```bash
$ python -c "import matplotlib; print(matplotlib.__version__); print(matplotlib.get_backend())"
3.1.1
Qt5Agg
```

**Comment by kdreyer3196** [comment]
@guyer  thank you for the quick response. I'm getting the following output for that code: 
3.1.1
Qt5Agg

Looks like @tkphd is having the same problem and running the same version of matplotlib

**Comment by Tigraan** [comment]
Notice that the colorbar is incorrect, but the colormap used in the main graphic is correct, so there might be a workaround to extract the scale information and plot the correct colormap without touching the source code.

Incomplete investigation of the problem:

The default comes from `AbstractMatplotlibViewer.__init__()` which [initializes a `_ColorBar` without specifying the `vmin` or `vmax` arguments](https://github.com/usnistgov/fipy/blob/master/fipy/viewers/matplotlibViewer/matplotlibViewer.py#L119), hence the scale falls back to the default (-1, 1). (Tested by changing `self.colorbar = _ColorBar(viewer=self)` to `self.colorbar = _ColorBar(viewer=self, vmin=-3.0)` and observing both the change in the final plot for the examples and the values in `self.viewer.norm`.)

After digging around in the source, the `datamin` and `datamax` seem to be correctly passed to `fipy.viewers.matplotlibViewer.AbstractMatplotlibViewer.__init__()`. In turn, this initializes the attribute `fipy.viewers.viewer.AbstractViewer.limits`. I am not sure what happens next but the default color bar bounds do not seem to be overriden anywhere; I guess [`matplotlib2DViewer`](https://github.com/usnistgov/fipy/blob/master/fipy/viewers/matplotlibViewer/matplotlib2DViewer.py) should do it?
