### ISSUE TITLE
datamin/datamax argument ignored by viewer

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#663]
Hi,

Similarly to issue #662 the datamin/datamax argument is not accounted for by matplotlib on a new install of fipy 3.3 with python 3.6.9 using conda in Win7.

So whenever i use the viewer, the data range is set to [-1, 1] 

I am getting the following warning from matplotlib, not sure if it is related:

C:\..\Anaconda3\envs\fipy-3.3\lib\site-packages\fipy\viewers\matplotlibViewer\matplotlib
Viewer.py:229: MatplotlibDeprecationWarning:
The set_norm function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_norm instead.
  self._cb.set_norm(value)

Do i have to go back to using fipy with python 2 ?

**Comment by NeversayEverLin** [comment]
Hi, I am running into the similar situation. Do you have any solution yet?

**Comment by oliverstefanov** [comment]
Thanks this fix works for me as well
