### ISSUE TITLE
Gmsh file import Error

### ISSUE THREAD

**Issue by NeversayEverLin** [usnistgov/fipy#664]
I tried to write a .msh file by use of python and then create a .msh file. The .msh file can be opened by Gmsh.exe perfectly. However, when I tried to import .msh by using Fipy to make it as the mesh of my simulation, it failed. I used Gmsh2D('my_file.msh'). Then it always generated a error:
[WinError32] the process cannot access the file because it is being used by another processor: ....\\tmpxxElements. 

Meanwhile, it also generate errors say that there is a line exceed range. 
[script.txt](https://github.com/usnistgov/fipy/files/3539213/script.txt)

Do any suggestion? Thanks a lot. 
<img width="658" alt="errors" src="https://user-images.githubusercontent.com/18692481/63661542-06338f00-c789-11e9-8361-0b76c04576ee.PNG">

**Comment by NeversayEverLin** [comment]
By the way, I use Fipy 3.3 and Gmsh 4.1 version.

**Comment by NeversayEverLin** [comment]
I check the python API file in Gmsh, the version is said to be 4.5; However, when I open .msh file by TXT and the MeshFormat is shown to be 4.1. So I am confused. But Gmsh.exe I used is the latest version downloaded from official path.

**Comment by guyer** [comment]
* Please share t1.msh with us
* What is `from fipy.gmsh_raw import gmsh_func`? There is no such module as `gmsh_raw` in FiPy.

________________________________________

**Comment by NeversayEverLin** [comment]
Thaks Guyer. I have made it successfully run by a similar way. It looks that we can still use Gmsh v4 while setting the output format to older version of gmsh. In my case, I simply add a command in Python script: 
gmsh_func.option.setNumber("Mesh.MshFileVersion", 3.0) 
and also at last, when try to save the gmsh, set the format with extension as .msh2. Then using Gmsh2D() in Fipy to call it. 
These procedures make it sure that the Fipy can generate the same Mesh as gmsh file. For further test of using the generated mesh for some real physical model, I am still working on it. 

Meanwhile, there is always an error generation about gmsh version. Since we are using gmsh version 4, Fipy will check the version of gmsh by communicating with Gmsh and therefore, the version of gmsh will always be 4.x since we are using Gmsh v4. Therefore, I simply change the version parameter in gmshMesh.py of Fipy and forced it to be a constant, like '3.0'. Then all problems are solved. Yes, it is a general practice that Fipy should check the version of gmsh to make it compatible with Fipy. However, if we know exactly what version we are running and whether or not it works, we can ignore the version check while it is bad for any further updates. 

I hope that in the future, the Fipy can be generally acceptable with Gmsh 4. And now GMSH 4 has provided a gmsh.py for developer. 

Thanks a lot.
