### ISSUE TITLE
Source in the middle of domain

### ISSUE THREAD

**Issue by fazaghifari** [usnistgov/fipy#665]
Hi,
I have a diffusion problem like this where the equation only consists of a diffusion term and a source term.
![image](https://user-images.githubusercontent.com/26693799/64505390-f033db80-d2fd-11e9-80b1-78a71a529fab.png)

1. "M" is the region within the main domain where the source comes from. Intuitively, I would put a coefficient 1 if the cell is inside M and 0 otherwise. But I didn't see any documentation to implement this kind of source. So how do I define this kind of problem?

2. The diffusion coefficient for each cell may differ from each other. What should I do to define this?

3. Also, I would like to know how do I calculate the average value inside region "N"?

Thank you.

**Comment by NeversayEverLin** [comment]
I think I can answer parts of your questions. 
1, for source defined in a specific position, you may define a CellVariable as your source first. Then, you set your boundary condition of your CellVariable, with some conditions like:
T = cellVariable(name='xxx',value=0.)
T.constrain(1,where = abs(x-3)<0 & abs(y-3)<0) # 3 is just an example, you can set it to your width and height of your source region . 

2, Similar, you can define your diffusion coefficient as a CellVariable, and following the same methods to define your diffusion coefficients and then input it as your DiffusionTerm coeff. 

3, Currently, I can only know that you can extract all your value of variable and then do averaging by yourself. I don't think Fipy can do anything as your expectation. You'd better try to use the solved and output data to do your own job. 

Hope those can help you.

**Comment by fazaghifari** [comment]
> I think I can answer parts of your questions.
> 1, for source defined in a specific position, you may define a CellVariable as your source first. Then, you set your boundary condition of your CellVariable, with some conditions like:
> T = cellVariable(name='xxx',value=0.)
> T.constrain(1,where = abs(x-3)<0 & abs(y-3)<0) # 3 is just an example, you can set it to your width and height of your source region .
> 
> 2, Similar, you can define your diffusion coefficient as a CellVariable, and following the same methods to define your diffusion coefficients and then input it as your DiffusionTerm coeff.
> 
> 3, Currently, I can only know that you can extract all your value of variable and then do averaging by yourself. I don't think Fipy can do anything as your expectation. You'd better try to use the solved and output data to do your own job.
> 
> Hope those can help you.

Ok, I get the idea of using `cellVariable` to specify the value for each cell, but how do I define the equation? As I know, according to this [example](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh20x20.html), we have to define the equation as the following:
`eq = TransientTerm() == DiffusionTerm(coeff=1)`
or in my case it could be:
`eq = DiffusionTerm(coeff=something) + ImplicitSourceTerm(coeff=somethingelse)`
So, do I have to change `somethingelse` into `T`, where `T` is the specific cells that produce the source?  Or is there another approach for this problem?

Thanks

**Comment by NeversayEverLin** [comment]
> > I think I can answer parts of your questions.
> > 1, for source defined in a specific position, you may define a CellVariable as your source first. Then, you set your boundary condition of your CellVariable, with some conditions like:
> > T = cellVariable(name='xxx',value=0.)
> > T.constrain(1,where = abs(x-3)<0 & abs(y-3)<0) # 3 is just an example, you can set it to your width and height of your source region .
> > 2, Similar, you can define your diffusion coefficient as a CellVariable, and following the same methods to define your diffusion coefficients and then input it as your DiffusionTerm coeff.
> > 3, Currently, I can only know that you can extract all your value of variable and then do averaging by yourself. I don't think Fipy can do anything as your expectation. You'd better try to use the solved and output data to do your own job.
> > Hope those can help you.
> 
> Ok, I get the idea of using `cellVariable` to specify the value for each cell, but how do I define the equation? As I know, according to this [example](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh20x20.html), we have to define the equation as the following:
> `eq = TransientTerm() == DiffusionTerm(coeff=1)`
> or in my case it could be:
> `eq = DiffusionTerm(coeff=something) + ImplicitSourceTerm(coeff=somethingelse)`
> So, do I have to change `somethingelse` into `T`, where `T` is the specific cells that produce the source? Or is there another approach for this problem?
> 
> Thanks

Simpy what you need to do is adding a mask in your source term expression. Suppose you have a source term as phi*sin(a)+3*t, then you may try (ImplicitsourceTerm(coeff=sin(a))+3*t)*mask, where mask is the condition of your confined area. 

Another option, I would prefer, it is that you can define the source term by your self and make it as a CellVariable where you can always set your value or constrain as you did in other variables. This will give you a more clear self-conscious control of your code. 

Best
