### ISSUE TITLE
Retrieve value of a CellVariable

### ISSUE THREAD

**Issue by NeversayEverLin** [usnistgov/fipy#666]
I define a 2D mesh and following the mesh to define a 2D CellVariable as:
x,y = mesh.cellCenters 
phi = CellVariable(name=r'\delta T',mesh=mesh,value=x+y)

Then, I tried to obtain the value of phi by using:
data = phi.value 

As expected, the value of phi should be a 2D data array. However, this operation only return a data array with only one dimension. So I am wondering why this case happens? How can I obtain a right dimensional data? 

Thanks a lot.

**Comment by wd15** [comment]
Returning a 1D array is the correct behavior. There is no assumption in the variable value array ordering or dimension about how the cells are connected. It is nominally an unstructured FV solver so the cells can be connected in many different ways. The index of the variable value array determines which cell the value is associated with and in turn the mesh determines the topology with arrays like `_cellToCellIDs` and `cellFaceIDs`. For example, for the `i`th cell. The x position of that cell is `mesh.cellCenters[0, i]`, the value held at that cell is `phi[i]` and neighboring cells indices are given by `mesh.cellToCellIDs[:, i]`.

However, if you do need a 2D array there is some internal assumptions used by Grid2D about the ordering of the mesh. Basically you can do a reshape of the values to get a 2D array [like this](https://github.com/usnistgov/fipy/blob/master/fipy/viewers/matplotlibViewer/matplotlib2DGridViewer.py#L96).
