### ISSUE TITLE
PhysicalGroup in mesh

### ISSUE THREAD

**Issue by NeversayEverLin** [usnistgov/fipy#668]
I am working with a simulation running into some problems about confusion of mesh. 
I created a geometric shape with a small circle inside the center of a rectangular area. Then I define the several PhysicalGroup and set parts of them with a corresponding PhysicalName. For example, 'circle' define the PhysicalGroup contain the circular area; 'rect' define the area within rectangular area while exclude the circle; 'circle-boundary' define the boundary of circle; 'rec-boundary' defines the boundary of the whole rectangular area (including circles), e.g. the four straight line forming rectangular area. 
Now, I import the mesh and print out mesh.physicalCells, it will give me a dictionary with the Physical Name defined above, such as {'circle': {cellVariables....}, 'rec': {cellVariable...}...}. Therefore, I can know the physical Name of all my defined area. I tried to set a different value and it works. 

However, when it comes to boundary, the physical name and groups confused me. If I use xxx.constrain(0., where = mesh.exteriorFaces), what is the the exact exteriorFaces means? It means the whole computation region's exteriorFaces? or the exteriorFaces corresponding to those different physical cells? e.g., for my case I have four different physical cells, does that mean I will have four group of exteriorFaces when I call mesh.exteriorFaces? 

Furthermore, how can I get access to each physical cell's exteriorFaces? Supposing that I want to define the boundary condition of 'circ' to be zero. Can I do something like calling mesh.physicalCells['circ'].exteriorFaces?? I tried this, actually, that it failed. But I am wondering if there is a way for this purpose? 

Thanks a lot.

**Comment by guyer** [comment]
`mesh.exteriorFaces` are the faces on the exterior of the *entire* mesh (specifically, the faces that only have a cell on one side). There is no way to ask FiPy for the `.exteriorFaces` of a group of `.physicalCells`.  It is easier and better to define and name the logical boundaries of interest using Gmsh.
