### ISSUE TITLE
Zero flux boundary setting in Fipy 

### ISSUE THREAD

**Issue by NeversayEverLin** [usnistgov/fipy#674]
I am working on simulation of heat transfer equation. The simulation case is that there is a center heat source (with a Gaussian shape and a defined waist in dimension of 0.2 μm) and simulation region is simply a rectangular with a dimension of 40 μm × 800 μm. Simulation is under 2D. Since the heat source is relatively low, therefore I could assume either of following two boundary condition:
i) zero output heat flux 
ii) fixed temperature boundary (say I only care about relative temperature rise, so let it be zero) 

However, during solving the equations, the definition of boundary condition leading to large difference, I am wondering how to define a right way of zero output heat flux? 
I append my code to see if anyone has a good solution to my definition of boundary condition:

```python
# the defined variable is phi (not shown here). HeatSource is also a defined CellVariable

alpha.constrain(0.,where = mesh.exteriorFaces)  # this is diffusion coefficient
exteriorFlux = FaceVariable(mesh=mesh,name=r'external flux',value=0.0,rank=1)
eqI = (TransientTerm(coeff=1)== DiffusionTerm(coeff=alpha) + HeatSource+(mesh.exteriorFaces*exteriorFlux).divergence) 

timeStepDuration = 1/(50*f)  # f is just a parameter to control time step
steps = int(50/4) 
Center_phi = np.zeros((1,steps))
t = np.zeros((1,steps))
for step in range(steps):
    print('Now at Step {0:.1f} of {1:.1f}'.format(step,steps))
    t[0,step] = time.value
    phi.updateOld()
    Center_phi[0,step] = np.max(phi.value)
    eqI.solve(var=phi,dt=timeStepDuration)
    time.setValue(time.value+timeStepDuration) 
```

By doing so, the temperature rise is going up to 2000 K, which is ridiculous, I am not sure what happening to my boundary condition. I also simply using `phi.faceGrad.constrain(((0.,),(0.,)), where=mesh.exteriorFaces)` as zero flux output boundary condition but lead to same results. I also tried boundary condition as `phi.constrain(0.,where = mesh.exteriorFaces)` but still goes unreasonable results. Thanks for help.

**Comment by guyer** [comment]
Format code

**Comment by tkphd** [comment]
[added python tag to highlight syntax in OP]

**Comment by wd15** [comment]
It might be helpful if you posted a full version of your working code and link to the equation math that you're trying to solve.

Just looking at the equation, the `exteriorFlux` is zero so the last term in the equation isn't needed. That then just leaves the `HeatSource` to change the value of `phi`. Without knowing the value of `HeatSource` I can't say anything about the likely outcome other than `phi` will just keep increasing / decreasing.

**Comment by guyer** [comment]
- As a cell-centered finite volume code, FiPy's boundaries are no-flux by default. I've added [an issue](https://github.com/usnistgov/fipy/issues/676) to make this clearer in the documentation.
- With no-flux boundaries and a constant source of heat from `HeatSource`, I would expect the temperature to rise without bound.

**Comment by matthijsnuus** [comment]
I'm having similar problems with my model. Still not sure how to fix it either. Have you managed to solve it yet?

**Comment by guyer** [comment]
@matthijsnuus Please post a problem statement and some code so that we can try to help

**Comment by matthijsnuus** [comment]
@guyer I am quite new to this platform, hope you meant making a new issue. Here's the link with the code: https://github.com/usnistgov/fipy/issues/713

**Comment by guyer** [comment]
@matthijsnuus New issue is great, thanks. I'll take a look and respond there.

**Comment by matthijsnuus** [comment]
@guyer great, thanks!
