### ISSUE TITLE
Feasibility of fipy for nonlocal interactions?

### ISSUE THREAD

**Issue by joelmiller** [usnistgov/fipy#675]
I've got a physical model that has some nonlocal interactions (captured by a spatial integral).  Is it feasible to use fipy for something like that?
 
In my case the equation looks something like  (for now let's assume it's a single spatial dimension)

d theta(x,t)/ dt =    f(theta(x,t))          +              integral   g(theta(xhat - x, t)) w(xhat-x)  dx

where w is a weighting function.  In appropriate limits for w, the integral corresponds to diffusion, but I need to have nonlocal interactions.

See equation 2a of
[Analytic models for SIR disease spread on random spatial networks](https://academic.oup.com/comnet/article/6/6/948/4931473)
to get an idea of what I'm looking at.

**Comment by guyer** [comment]
You should be able to use [`.cellVolumeAverage()`](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.variables.html#fipy.variables.cellVariable.CellVariable.cellVolumeAverage) for this. This method calculates $\int_V \phi dV / \int_V dV$, so you'll want to multiply by system volume, e.g.,
```python
volumes = fp.CellVariable(mesh=mesh, value=mesh.cellVolumes)
int_phi = phi.cellVolumeAverage * volumes.sum()
```

Note that functions like $theta(xhat - x)$ will need to be calculated NxN, so will be really slow, consume large amounts of memory, or both. Probably this could be made somewhat more efficient by using a chunking scheme, similar to what we use in [`numerix.nearest()`](https://github.com/usnistgov/fipy/blob/422d382fe4c75e888c5e6b6e2987643efc8e7015/fipy/tools/numerix.py#L463), but I'd need to spend some time thinking about it. Jetlag and backlog of work prevent me from doing that right away, but please continue asking questions if you need help.
