### ISSUE TITLE
Python3 and PyTrilinos

### ISSUE THREAD

**Issue by raviapatel** [usnistgov/fipy#696]
Dear Developers,
Thanks for this wonderful and flexible FV package. I was wondering if fipy supports pytrilinos in python3 if i manage to compile pytrilinos myself?
regards
Ravi

**Comment by guyer** [comment]
It should, but it's not something we've tested

**Comment by guyer** [comment]
[PETSc support](https://github.com/usnistgov/fipy/pull/659), including with Py3k, should be released very soon

**Comment by raviapatel** [comment]
Thats cool. Waiting for new release then.
