### ISSUE TITLE
Reconstructing split output VTK files after MPI Run

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#709]
Hi, I understand that when we do an MPI run, it splits the domain into subsections which when using the default Fipy viewer we can see the domain being split up as the equations are being solved. When I use the VTK viewer to output VTK snapshots, this results in the VTK files being split as well (but only one file is being outputted so the actual file is half the size it should be)
Is there a way to reconstruct the whole file or is there an another strategy to output the data. My current timestepping and sweeping implementation is as follows: 
```
while elapsed < duration: 
    elapsed += dt
    timestep += 1
    x_a.updateOld()
    mu_AB.updateOld()
    res = 1e+10
    while res > 1e-10:
        res = eq.sweep(dt=dt, solver=solver)
        print ("sweep!")
    print (elapsed)
    end = time.time()
    print(end-start)
    if (timestep % time_stride ==0):
        vw = VTKCellViewer(vars=(x_a, mu_AB))
        vw.plot(filename="%s_output.vtk" %elapsed)
```

**Comment by guyer** [comment]
You can write out separate files on each process:
```python
from fipy.tools import parallelComm
  :
  :
        vw.plot(filename="%s_output.%d.vtk" % (elapsed, parallelComm.procID))

**Comment by pavaninguva** [comment]
Hi, that is great, thanks so much for the help!!! How do I go about merging the VTK files into one file. Simply appending the files is not so straightforward since there is overlap with the data in each file.

**Comment by guyer** [comment]
Generally speaking, I would say you don't merge them into a single file. Most of the VTK viewers (VisIt, ParaView, Mayavi, ...) have the ability to take in multiple data streams and render them all. For HPC, it's often infeasible to have everything in one file.

**Comment by pavaninguva** [comment]
I see. I have not been able to do that properly, but I ended up using the Clip, Append and CleantoGrid filters in Paraview to stitch together a crude solution. Thanks for your help!
