### ISSUE TITLE
Zero flux boundary going "out of bounds" (updated with full working code) 

### ISSUE THREAD

**Issue by matthijsnuus** [usnistgov/fipy#713]
UPDATED CODE (FULL WORKING VERSION) 

Hey, 

I'm dealing with some issues regarding a constant flux input on my heatflow model. As been posted before (https://github.com/usnistgov/fipy/issues/674) I was hoping to find the answer there but didn't seem to have been solved yet. 
The problem with my code is that if I put a constant flux coming in from one side the heat doesn't seem to propagate but the outer end where the flux is being supplied just reaches values that are out of bounds.

https://pastebin.com/raw/pGhP4nG1

**Comment by matthijsnuus** [comment]
@guyer I can send you an explanation or cleaner version of the code as well. If that helps. Basically I tried both the ".faceGrad.constrain([fluxRight], mesh.facesRight)" and the other way to implement it within the equation by adding the diffusion term into it.

**Comment by guyer** [comment]
The comment in your script says `fluxRight` has units of `(J/yr) / m^2`, but the flux in your equation is `$D\nabla T$` or `D * T.faceGrad`, which has units of `m * K / yr`. If I divide `fluxRight` by `dens * cp`, I get the correct units and the solution looks more like your analytical value.

The changes I made are [here](https://gist.github.com/guyer/c44dbcb041c649917a6393ec2c856ada/revisions).

**Comment by matthijsnuus** [comment]
@guyer thanks for the fix. It seems to work accordingly indeed. Do you have a suggestion on how I could adjust the equation so that it accepts heatflow-flux in W/m^2?

**Comment by guyer** [comment]
Simplistically, change your equation to
```python
eqI = (TransientTerm(coeff=dens * cp) == DiffusionTerm(coeff=k) + (mesh.facesRight * fluxRight).divergence)
```

I believe this form is more correct representation of the heat equation and that the spatially varying `dens` and `cp` should not appear inside the divergence of the `DiffusionTerm`. I'm not positive, though, as most derivations are not very careful and immediately assume that the coefficients are all uniform in space. 

If you consider the time-rate-of-change of internal energy, then conservation says that the time-rate-of-change of the heat energy density, `dens * cp * T` goes like minus the divergence of the heat flux `k * T.faceGrad`.

**Comment by matthijsnuus** [comment]
Cheers! This helped me a lot.

**Comment by matthijsnuus** [comment]
@guyer managed to solve the problem completely with your help. Just needed some unit adjustment in the end. Thank you so much.
