### ISSUE TITLE
 RuntimeWarning: invalid value encountered in log   return self.op(self.var[0].value)

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#715]
Hi

The simulation would run fine for the first couple of timesteps, then what would happen is that the following error message pops up and the output files from then on become unusable (plus the file size is about half which seems to me that one of the variables is no longer being solved): 

The trace is as follows: 
```
713.2477543354034
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
sweep!
25.0
887.920652627945
sweep!
/home/kpi15/miniconda3/envs/fipy34/lib/python3.7/site-packages/fipy/variables/unaryOperatorVariable.py:36: RuntimeWarning: invalid value encountered in log
  return self.op(self.var[0].value)
sweep!
30.0
927.737086057663
/home/kpi15/miniconda3/envs/fipy34/lib/python3.7/site-packages/fipy/variables/variable.py:1204: RuntimeWarning: invalid value encountered in less
  return self._BinaryOperatorVariable(lambda a, b: a<b, other)
/home/kpi15/miniconda3/envs/fipy34/lib/python3.7/site-packages/fipy/variables/variable.py:1286: RuntimeWarning: invalid value encountered in greater_equal
  return self._BinaryOperatorVariable(lambda a, b: a>=b, other)
sweep!
35.0
938.3502547740936
```

FYI, I print out the time taken for each timestep and also print the string ("sweep!) at each sweep for my own checking

**Comment by guyer** [comment]
You solution is evolving at some location to a value <= 0, hence "`RuntimeWarning: invalid value encountered in log`". Everything after that is a consequence of this.

Figuring this out is very much the art of numerically solving PDEs and is quite dependent on your equations and what you're trying to do with them.

Some things that can affect this:
- solver
- sweep tolerance
- time step
- convection scheme
- non-conservative equations
- ...

**Comment by pavaninguva** [comment]
I see, that makes sense. I shall use this opportunity to make sense of that and explore the various settings. Thanks!

**Comment by pavaninguva** [comment]
Hi! So sorry! I wanted to ask if there is a way to clip or bound the values within the Fipy environment? Would overwriting them potentially do the trick as well?

**Comment by guyer** [comment]
Yes, you can explicitly reassign any values that go out of bounds. That's basically a double-obstacle potential. It's better if your equations enforce the constraints, but explicit bounding should work.

**Comment by pavaninguva** [comment]
I see. Could I clarify how would I go about accessing and reassigning values that go out of bounds syntaxwise? From a numerics standpoint, my guess is that I need to assign cell values of $ \leq 0 + \epsilon$ to 0 to prevent the solver from ever seeing a negative value?

**Comment by guyer** [comment]
Should be something like
```python
for step in steps:
    for sweep in sweeps:
        res = eq.sweep(...)
        var.setValue(0., where=var < 0.)
```
