### ISSUE TITLE
Attribute Error: 'CellVariable' object has no attribute '_'error, fipy, python

### ISSUE THREAD

**Issue by Minjun-Bae** [usnistgov/fipy#720]
Hello all,

I am a python beginner, who is using window10.

I have been trying to practice some examples from the article, 'FiPy: Partial Differential Equation with Python'.

In an attempt to reproduce their simulations, I found that every time I try to get access an attribute by using the attribute reference syntax form, `AttributeError: 'CellVariable' object has no attribute '___'` error.

Below is my code, which I followed the exact same procedure with the code the article provided.
```python
from fipy import * 
dx = dy = 0.025 
nx = ny = 500 
mesh = Grid2D(dx=dx, dy=dy, nx=nx, ny=ny) 
dt = 5e-4 
phase = CellVariable(name=r’$\phi$’, mesh=mesh, hasOld=True) 
dT = CellVariable(name=r’$\Delta T$’,mesh=mesh, hasOld=True) 
DT = 2.25 
heatEq = (TransientTerm() == DiffusionTerm(DT) + (phase - phase.getOld()) / dt)
```

And I am getting error such as:

```
AttributeError Traceback (most recent call last)
in 
----> 1 heatEq = (TransientTerm() == DiffusionTerm(DT) + (phas - phas.getOld()) /dt)

AttributeError: 'CellVariable' object has no attribute 'getOld''
```

I thought the problem might come from the way anaconda installs things. For this reason, I uninstall and reinstalled the ipython and related files by using pip.
The problem still remains existent.

If anybody could help me with this issue, it would be very much appreciated.

Please let me know if I could provide more information regarding this.

Thanks in advance.

**Comment by tkphd** [comment]
Syntax-highlighting code blocks

**Comment by guyer** [comment]
Welcome to FiPy! That [article](https://www.ctcms.nist.gov/cgi-bin/redirect.py?url=http://dx.doi.org/10.1109/MCSE.2009.52) is eleven years old and FiPy’s syntax has evolved quite a bit since then (in this case, use the property `phase.old` instead of the method `phase.getOld()`.

The [examples on our website](https://www.ctcms.nist.gov/fipy/examples/README.html) are up-to-date.

**Comment by Minjun-Bae** [comment]
Thank you for the fast response, Mr. Guyer. 
It is such an honor to have your comment in my post. I enjoyed many publications of yours, especially the phase-field modeling of electrochemistry. 

I will look through those examples, and come back with more questions.
Please take care.


> Welcome to FiPy! That [article](https://www.ctcms.nist.gov/cgi-bin/redirect.py?url=http://dx.doi.org/10.1109/MCSE.2009.52) is eleven years old and FiPy’s syntax has evolved quite a bit since then (in this case, use the property `phase.old` instead of the method `phase.getOld()`.
> 
> The [examples on our website](https://www.ctcms.nist.gov/fipy/examples/README.html) are up-to-date.

**Comment by guyer** [comment]
@Minjun-Bae That's very flattering, thank you
