### ISSUE TITLE
Gmsh 2D mesh creat

### ISSUE THREAD

**Issue by shayanmazloom** [usnistgov/fipy#723]
hi 
how can i prevent showing following infos to save process time!?
 "
Info    : [  0 %] Meshing curve 1 (Line)
Info    : [ 10 %] Meshing curve 2 (Line)
Info    : [ 10 %] Meshing curve 3 (Line)
Info    : [ 10 %] Meshing curve 4 (Line)
Info    : [ 10 %] Meshing curve 5 (Line)
Info    : [ 20 %] Meshing curve 6 (Line)
Info    : [ 20 %] Meshing curve 7 (Line)
....
"
and how can i just run 2d meshing

**Comment by guyer** [comment]
That output is generated by Gmsh and I don't think we have any way to silence it. I also doubt that it's taking much time. 1D meshing is done by Gmsh in the course of 2D meshing. That's just the way that it works.

**Comment by shayanmazloom** [comment]
> That output is generated by Gmsh and I don't think we have any way to silence it. I also doubt that it's taking much time. 1D meshing is done by Gmsh in the course of 2D meshing. That's just the way that it works.

i need to generate meshes for 20 times in program :).so each 0.01s is important to me!

**Comment by wd15** [comment]
Gmsh does have a verbosity (e.g. `gmsh -v 2`) setting if you can run Gmsh independently from FiPy. See https://gmsh.info/doc/texinfo/gmsh.html#Running-Gmsh-on-your-system

**Comment by guyer** [comment]
You've profiled and determined that those 0.2 s are your bottleneck?
