### ISSUE TITLE
Radioactive heat production in heat flow code

### ISSUE THREAD

**Issue by matthijsnuus** [usnistgov/fipy#727]
Hi, 
I have created a heatflow code that based on RMS with the real temperature curve found in a borehole finds the best value for the heat flux. However I noticed my values are off by more than 20mW/m^2. Mostly due to not implementing radioactive heat production within the individual layers. 
Anyone has an idea how I can implement radioactive heat production in each cell? In my code I read an excel sheet that assigns a type of rock to each cell to which specific properties are added, I have the values for the radioactive heat production, it's just a matter of implementing it in the code that is the problem for me now. 
Thanks!

https://pastebin.com/raw/CZSF5LAF

**Comment by matthijsnuus** [comment]
Is it possible to, in stead of using facesRight, let a heatflux be generated from within the mesh, i.e. calling an interior cell in the mesh and giving it a flux value?

**Comment by guyer** [comment]
Radioactive rock is not a flux of heat, it is a *source* of heat. Simply explicitly add a CellVariable that contains the value of this source in W/m**3.

On May 8, 2020, at 6:04 AM, matthijsnuus <notifications@github.com<mailto:notifications@github.com>> wrote:



Is it possible to, in stead of using facesRight, let a heatflux be generated from within the mesh, i.e. calling an interior cell in the mesh and giving it a flux value?

**Comment by matthijsnuus** [comment]
Can that be implemented within the equation?

**Comment by guyer** [comment]
Yes. Simply explicitly add a CellVariable that contains the value of this source in W/m**3.

**Comment by matthijsnuus** [comment]
@guyer thanks! I managed to implement it.
