### ISSUE TITLE
Impossible to build documentation

### ISSUE THREAD

**Issue by faxik** [usnistgov/fipy#730]
The advertised way of building documentation does not work. It seems that it requires a very outdated version of Sphinx.

```bash
python3 setup.py build_docs --pdf
```
I have tried to monkey-patch setup.py, but couldn't advance much, as I don't fully understand the documentation build process.

**Comment by guyer** [comment]
I've just confirmed that the docs build fine with Python 3.8.2 and Sphinx 3.0.3 ([released Apr 26, 2020](https://www.sphinx-doc.org/en/master/changes.html#release-3-0-3-released-apr-26-2020))

**Comment by faxik** [comment]
First of all, thank you for the ultra-fast reply. 
I will examine the CI scripts and my environment and will let you know.

I have tried the default Python of Ubuntu 20.04 with a clean venv. The only difference might be the way sphinx is installed/configured.

**Comment by faxik** [comment]
```bash
pip freeze

alabaster==0.7.12
ApiDoc==1.4.0
attrs==19.3.0
autodoc==0.5.0
Babel==2.8.0
backcall==0.1.0
beautifulsoup4==4.9.0
bleach==3.1.5
blockdiag==2.0.1
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
cloudpickle==1.4.1
cycler==0.10.0
dask==2.16.0
decorator==4.4.2
defusedxml==0.6.0
distributed==2.16.0
docutils==0.16
entrypoints==0.3
FiPy==3.4.1
funcparserlib==0.3.6
future==0.18.2
HeapDict==1.0.1
idna==2.9
imagesize==1.2.0
ipython==7.14.0
ipython-genutils==0.2.0
jedi==0.17.0
Jinja2==2.7.3
jsonschema==2.4.0
jupyter-client==6.1.3
jupyter-core==4.6.3
kiwisolver==1.2.0
latexcodec==2.0.0
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
msgpack==1.0.0
nbconvert==5.6.1
nbformat==5.0.6
numpy==1.18.4
numpydoc==0.9.2
oset==0.1.3
packaging==20.3
pandas==1.0.3
pandocfilters==1.4.2
parso==0.7.0
pbr==5.4.5
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pkg-resources==0.0.0
prompt-toolkit==3.0.5
psutil==5.7.0
ptyprocess==0.6.0
pybtex==0.22.2
pybtex-docutils==0.2.2
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==3.11
pyzmq==19.0.1
requests==2.23.0
scipy==1.4.1
six==1.14.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
soupsieve==2.0
Sphinx==3.0.3
sphinxcontrib-apidoc==0.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-bibtex==1.0.0
sphinxcontrib-blockdiag==2.0.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-jupyter==0.5.6
sphinxcontrib-mermaid==0.4.0
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
tblib==1.6.0
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
traclinks @ file:///home/faxik/programs/traclinks
traitlets==4.3.3
urllib3==1.25.9
waitress==1.4.3
wcwidth==0.1.9
webcolors==1.11.1
webencodings==0.5.1
WebOb==1.8.6
WebTest==2.0.35
zict==2.0.0
```

**Comment by faxik** [comment]
Jonathan,

Thank you for the help and the link to the CI logs. I was missing some LaTeX packages and mistakingly ran 2to3 as I used to before. May I suggest to include a list of essential packages and `requirements.txt` for documentation building?

After installing the required packages the generation finishes and produces PDF, while there are a lot of warnings that I didn't spot in the CI logs.

I'm attaching the log and closing the issue since it is resolved for me. 
[build_docs.log](https://github.com/usnistgov/fipy/files/4636960/build_docs.log)

**Comment by guyer** [comment]
The instructions are [here](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#manual). I fail to see how a `requirements.txt` would help very much.
