### ISSUE TITLE
I keep getting AttributeError: 'DummyComm' object has no attribute 'epetra_comm

### ISSUE THREAD

**Issue by ACamposG** [usnistgov/fipy#740]
I installed a fresh copy of fipy in a linux-based machine using:

conda create --name <MYFIPYENV> --channel conda-forge python=<PYTHONVERSION> fipy

Then I also installed Gmsh, trilinos and pytrilinos by:

conda install -c conda-forge python-gmsh 
conda install -c conda-forge trilinos
conda install -c conda-forge pytrilinos

I am able to call trilinos solvers within python like this:
(fpy2) campos26@bicephalous:~/stress$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fipy.solvers.trilinos.linearLUSolver import LinearLUSolver
>>> from fipy.solvers.trilinos.linearGMRESSolver import LinearGMRESSolver
>>> from fipy.solvers.trilinos.preconditioners.jacobiPreconditioner import JacobiPreconditioner
  
Seems everything is ok, regarding installation.

But, when I run my script, I keep getting the following error:

File "/home/campos26/anaconda2/envs/fpy2/lib/python2.7/site-packages/fipy/matrices/trilinosMatrix.py", line 581, in __init__
    comm = mesh.communicator.epetra_comm
AttributeError: 'DummyComm' object has no attribute 'epetra_comm'

Could you please help me?

Thanks 
Alfonso

**Comment by guyer** [comment]
If I had to guess, you are invoking FiPy such that it thinks the solvers to use are something other than Trilinos and then you are manually telling it to use Trilinos anyway. FiPy doesn't work that way. If you want Trilinos, then invoke FiPy with either the [`--trilinos`](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#cmdoption-trilinos) flag or set the [`FIPY_SOLVERS`](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#envvar-FIPY_SOLVERS) environment variable to `trilinos`.

**Comment by guyer** [comment]
Further, I don't know what you did, but you did not do this:
```
conda create --name --channel conda-forge python= fipy
```
There are at least two errors in that statement. Please post what you actually did.

**Comment by ACamposG** [comment]
I used the following:

conda create --name fpy2 --channel conda-forge python=2.7 fipy

**Comment by ACamposG** [comment]
I included the flag --trilinos, and it worked.

In previous versions I did not have to calle that flag. 

Thanks a lot John, really appreciate your quick and accurate response.

**Comment by guyer** [comment]
If you only had the Trilinos solvers installed, then those would be used automatically.  

Until FiPy 3.4 (released in February), launching FiPy in parallel with `mpirun` would automatically invoke the Trilinos solvers. Now it could invoke either PETSc or Trilinos, with a preference for PETSc.

**Comment by guyer** [comment]
Note, there is no need for these commands:
```
conda install -c conda-forge python-gmsh
conda install -c conda-forge trilinos
conda install -c conda-forge pytrilinos
```
FiPy does not depend on the `python-gmsh` or `trilinos` packages. It depends on the `gmsh` and `pytrilinos` packages. Both are installed automatically when you install the `fipy` package from `conda-forge`.

**Comment by ACamposG** [comment]
Ok, I'll keep that in mind. Thanks again.
