### ISSUE TITLE
1D semiconductor device simulation using fipy

### ISSUE THREAD

**Issue by dxshi-t** [usnistgov/fipy#746]
I am trying to solve the following set of coupled pdes using fipy:
**dn/dt = Dn(E) * d2n/dx2 + velocity_n (E)dn/dx+S(p,n,E,t) 
dp/dt = Dp(E) * d2p/dx2 + velocity_p (E)dp/dx+S(p,n,E,t) 
d2potential/dx2 = -q/epsilon * (p-n)**
where ElectricField= -grad.potential 

I have functions written for Dn(E), the DiffusionTerm coefficient, and velocity_n(E), the ConvectionTerm. I implement them with the following snippet: 
  
```python
Nion_equation=TransientTerm(coeff=1., var=Nion)== ConvectionTerm(coeff=velocity_n, var=Nion) +DiffusionTerm(coeff=D_n, var=Nion)+emisn-Recn+photogen+n_impactgen
```
  
I have declared velocity_n and Dn as FaceVariables. 
But it always warns me the coeffitient can not be a FaceValue.Following are the detailed information. 
  
The velocity_n and D_n are defined as FaceValues with the following statements: 
  
```python
velocity_n = FaceVariable(mesh=mesh, rank=1) 
D_n = FaceVariable(mesh=mesh, rank=1)
```
  
And I give the numeraical expressions of the two coefficient: 
  
```python
velocity_n[0]=1000*electricfield[0].arithmeticFaceValue*(1+(10*electricfield[0].arithmeticFaceValue/(1260+electricfield[0].arithmeticFaceValue))**4)**(-1/4)+      1.91*10**7*(electricfield[0].arithmeticFaceValue/257000)**5.7/(1+(electricfield[0].arithmeticFaceValue/257000)**5.7)

  
D_n[0]=f*velocity_n[0]/electricfield[0].arithmeticFaceValue
```

 Where the electricfield is the negative gradient of the potential, and I have define the potential as the CellVariable. The relevant statements are: 
  
```python
potential = CellVariable(mesh=mesh, name='Potential',hasOld=True)
electricfield=-potential.grad
```

As for the source terms, I define them as the function of electricfied, n and p.
The code has been attached below:
```python
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

from fipy import Variable, FaceVariable, CellVariable, Grid1D, ExplicitDiffusionTerm, TransientTerm, DiffusionTerm, \
    Viewer, ImplicitSourceTerm, ConvectionTerm

from fipy.tools import numerix

from fipy.variables.faceGradVariable import _FaceGradVariable

def simulation(left_bias, right_bias):
    q = 1.602e-19  
    kb = 1.38e-23  
    epsilon_r=9
    epsilon = epsilon_r * 8.854e-14  # Permittivity C/V*cm
    T=300
    f = kb * T / q
    #-----------------------------------------------------------------------
    #------------------------Geometry and mesh------------------------------
    #-----------------------------------------------------------------------
    def mesh_1d(length, cell_num):
        '''
        creat a 1D grid
        '''
        dx = length / cell_num  # Width of each mesh cell
        mesh=Grid1D(dx=dx, nx=cell_num) 
        return mesh
    length=0.06
    cell_num=10
    mesh= mesh_1d(length,cell_num)
    #-----------------------------------------------------------------------
    #------------------------Description of the variables------------------------------
    #----------------------------------------------------------------------- 
    p_initial = np.zeros(cell_num)
    n_initial = np.zeros(cell_num)
    Pion = CellVariable(mesh=mesh, name='Positive ion Charge Density', value=p_initial,hasOld=True,elementshape=(cell_num,))
    Nion = CellVariable(mesh=mesh, name='Negative ion Charge Density', value=n_initial,hasOld=True,elementshape=(cell_num,)) 
    potential = CellVariable(mesh=mesh, name='Potential',hasOld=True)
    potential[0]=(left_bias-right_bias)
    velocity_n = FaceVariable(mesh=mesh, rank=1)
    velocity_p = FaceVariable(mesh=mesh, rank=1)  
    D_n = FaceVariable(mesh=mesh, rank=1)
    D_p = FaceVariable(mesh=mesh, rank=1)
    electricfield=-potential.grad

    velocity_n[0]=1000*electricfield[0].arithmeticFaceValue*(1+(10*electricfield[0].arithmeticFaceValue/(1260+electricfield[0].arithmeticFaceValue))**4)**(-1/4)+ \
        1.91*10**7*(electricfield[0].arithmeticFaceValue/257000)**5.7/(1+(electricfield[0].arithmeticFaceValue/257000)**5.7) #velocity is the function of the electric field
    velocity_p[0]=17*electricfield[0].arithmeticFaceValue/(1+(17*electricfield[0].arithmeticFaceValue/(6.63*10**6))**1.75)**(1/1.75)
    D_n[0]=f*velocity_n[0]/electricfield[0].arithmeticFaceValue
    D_p[0]=f*velocity_p[0]/electricfield[0].arithmeticFaceValue
    
    v_n=CellVariable(mesh=mesh, name='Negative ion Charge velocity',hasOld=True) 
    v_p=CellVariable(mesh=mesh, name='positive ion Charge velocity',hasOld=True ) 

    v_n.setValue=1000*electricfield[0]*(1+(10*electricfield[0]/(1260+electricfield[0]))**4)**(-1/4)+ \
        1.91*10**7*(electricfield[0]/257000)**5.7/(1+(electricfield[0]/257000)**5.7)
    v_p.setValue=17*electricfield[0]/(1+(17*electricfield[0]/(6.63*10**6))**1.75)**(1/1.75) 
    #-----------------------------------------------------------------------
    #------------------------Description of recombination-----------------------------
    #-----------------------------------------------------------------------    
    # the recombination part 
    degen_fac=2 
    density=10**18 
    sign=1.9*10**(-15) 
    sigp=1*10**(-15)
    ni=1.9**(-10)
    en=degen_fac*sign*v_n.arithmeticFaceValue*ni*numerix.exp(1.2/0.026) 
    ep=1/degen_fac*sigp*v_p.arithmeticFaceValue*ni*numerix.exp(-1.2/0.026) 
    F_tA=(v_n.arithmeticFaceValue*sign*Nion.arithmeticFaceValue+ep)/(v_n.arithmeticFaceValue*sign*v_p.arithmeticFaceValue*sigp*Pion.arithmeticFaceValue+ep+en) 
    N_ionized=density*F_tA 
    Recn=(sign*v_n.arithmeticFaceValue*density)*(density-N_ionized)
    Recp=(sigp*v_p.arithmeticFaceValue*density)*N_ionized 
    emisn=en*N_ionized 
    emisp=ep*(density-N_ionized) 
    
    #-----------------------------------------------------------------------
    #------------------------Description of impact ionization-----------------------------
    #-----------------------------------------------------------------------    
    tE=1*10**(-13) 
    Ei_n=0.5  
    Ei_p=3.4-0.5
    e=1 
    lameda_E_n=v_n.arithmeticFaceValue*tE  
    a_n=numerix.exp(-Ei_n/(e*(electricfield[0].arithmeticFaceValue)*lameda_E_n)+0.0001)/(lameda_E_n+0.0001)   
    lameda_E_p=v_p.arithmeticFaceValue*tE   
    a_p=numerix.exp(-Ei_p/(e*(electricfield[0]).arithmeticFaceValue*lameda_E_p)+0.0001)/(lameda_E_p+0.0001)   
    n_impactgen=Nion.arithmeticFaceValue*a_n*v_n.arithmeticFaceValue
    p_impactgen=Pion.arithmeticFaceValue*a_p*v_p.arithmeticFaceValue

    #-----------------------------------------------------------------------
    #------------------------Description of photogeneration-----------------------------
    #----------------------------------------------------------------------- 
    time=Variable()
    
    def get_photogeneration(time):
        
        a=0.25
        beta=20*10**(-9) 
        y=0.0001
        h=6.62607015*10**(-34) 
        c=3*10**8  
        tG=5*10**(-9)/1.177
        I0=2*10**6/0.06/0.06 
        I=I0*numerix.exp(-2*(time/tG)**2)
        lamada=532*10**(-10) 
        photogen_rate=I*lamada*(a+beta*y*I+beta*I)*numerix.exp(-a*y)/(h*c*(1+beta*I*y)**2)
        return photogen_rate
        pass
    photogen=get_photogeneration(time)
    
    '''
        TransientTerm = dVar/dt 
    ConvectionTerm = dVar/dx 
    DiffusionTerm = d^2Var/dx^2
    '''

    # Poisson's Equation

    potential_equation = DiffusionTerm(coeff=1., var=potential)==-(q/epsilon)*(Pion - Nion)
    

    Pion_equation=TransientTerm(coeff=1., var=Pion)==ConvectionTerm(coeff=velocity_p, var=Pion)  \
        +DiffusionTerm(coeff=D_p, var=Pion)+photogen+ emisp-Recp+p_impactgen

    Nion_equation = TransientTerm(coeff=1., var=Nion) == ConvectionTerm(coeff=velocity_n,var=Nion) \
        +DiffusionTerm(coeff=D_n, var=Nion)+photogen+emisn-Recn+n_impactgen
               
    #boundery condition
    # Boundary conditions can be applied only to CellVariables. Direchlet Boundaries can easily be applied by using
    # the CellVariable.constrain method with a value and a definition of where. mesh.facesLeft or Right apply the
    # boundary condition to the furthest left and furthest right cell. One can also use a Boolean array where True
    # values define where to apply the boundary conditon.
            
    potential.constrain(left_bias, where=mesh.facesLeft)
    potential.constrain(right_bias, where=mesh.facesRight)

    # coupling three equations to solve together
    eq = Pion_equation & Nion_equation & potential_equation
    # Iterate through a number of steps to solve equations with a set timestep
    # Set up time stepping
    dt = 10^(-11) 
    duration =20*10^(-9) 
    time_stride = 10^(-10) 
    timestep = 0 
    elapsed =0 

    # Initialising the viewer
    if __name__ == "__main__":
        viewer = Viewer(vars(Nion))

    # start the time 
    start = time.time()    # Time stepping
    while elapsed < duration: 
        elapsed += dt
        timestep += 1
        Nion.updateOld()
        Pion.updateOld()
        potential.updateOld()
        v_n.updateOld()
        v_p.updateOld()
        D_p.updateOld()
        D_p.updateOld()
        photogen.setvalue=get_photogeneration(elapsed)
        
        res = 1e4
        while res > 1e-10:
            res = eq.sweep(dt=dt)
            print ("sweep")
            print (res)
            print (elapsed)
            end = time.time()
            print (end-start)
            if (timestep % time_stride ==0):
                print ("Beep")
                if __name__ == '__main__':
                    viewer.plot()
    if __name__ == '__main__':
        input("Press <return> to proceed...")
        import fipy.viewers
        NionViewer = fipy.viewers.make(vars = (Nion,))
        PionViewer = fipy.viewers.make(vars = (Pion,))
        
        NionViewer.plot()
        PionViewer.plot()
        
simulation(1000,0)
```

But it doesn’t work, and always warned me: The coefficient can not be a FaceVariable. 
  
What is happening? Have I not set this up correctly? What examples could Iuse to iron this out?

**Comment by guyer** [comment]
Format code

**Comment by guyer** [comment]
more code formatting

**Comment by guyer** [comment]
This script has a ***lot*** of problems, but the specific `TypeError: The coefficient can not be a FaceVariable.` arises because  `Recn`, `Recp`, `emisn`, and `emisp` are all defined in terms of `N_ionized`, which is defined in terms of `F_tA`, which is defined in terms of `v_n.arithmeticFaceValue`, `Nion.arithmeticFaceValue`, `v_p.arithmeticFaceValue`, and `Pion.arithmeticFaceValue`. As a result, `Recn`, `Recp`, `emisn`, and `emisp` are all `FaceVariables`, but you use them as sources, so they must be `CellVariables`. The solution is to remove all of these uses of `.arithmeticFaceValue`; there is no need for it.

Similarly for `lameda_E_n`, `a_n`, `lameda_E_p`, `a_p`, `n_impactgen`, and `p_impactgen`, remove the uses of `.arithmeticFaceValue`.

You can leave the use of `.arithmeticFaceValue` in  the definitions of `velocity_n`, `velocity_p`, `D_n`, and `D_p`.

Some  other problems you will quickly encounter:
- Don't declare `Pion` and `Nion` with `elementshape=(cell_num,)`. The `elementshape=` parameter is an advanced use and you should not use it unless you're following directly from one of our few examples that use it.  What you've done will create a variable that has `cell_num` distinct values *at every single cell*, so instead of creating a variable with 10 cells that has 10 distinct values, you've made a variable with 10 cells that has 100 distinct values.
- If you want to use the Python [`time`](https://docs.python.org/3/library/time.html) package for `start = time.time()` and `end = time.time()`, then you need to give another name to the `Variable` tracking solution time.
- `fipy.viewers.make` has not been a valid syntax for at least 8 years. Where did you see it used?
- Expressions like `2*10**6` don't mean what you think they do. Often they will work, but often they will give you very large integers (because 10 is an integer). Scientific notation in Python is obtained with `2e6`, `6.62607015e-34`, etc.
- Expressions like `20*10^(-9)` ***really*** don't mean what you think they do. The `^` operator in Python is a bitwise exclusive or, so `10^(-11)` equals `-1`. Again, scientific notation in Python is obtained with `2e6`, `6.62607015e-34`, etc.

Once you get through all of that, you will find that the semiconductor drift-diffusion equations are miserable to solve. See #731 for some guidance on how you can improve solutions, but understand that while FiPy has been used to solve them, we don't have any robust examples.

**Comment by dxshi-t** [comment]
> This script has a _**lot**_ of problems, but the specific `TypeError: The coefficient can not be a FaceVariable.` arises because `Recn`, `Recp`, `emisn`, and `emisp` are all defined in terms of `N_ionized`, which is defined in terms of `F_tA`, which is defined in terms of `v_n.arithmeticFaceValue`, `Nion.arithmeticFaceValue`, `v_p.arithmeticFaceValue`, and `Pion.arithmeticFaceValue`. As a result, `Recn`, `Recp`, `emisn`, and `emisp` are all `FaceVariables`, but you use them as sources, so they must be `CellVariables`. The solution is to remove all of these uses of `.arithmeticFaceValue`; there is no need for it.
> 
> Similarly for `lameda_E_n`, `a_n`, `lameda_E_p`, `a_p`, `n_impactgen`, and `p_impactgen`, remove the uses of `.arithmeticFaceValue`.
> 
> You can leave the use of `.arithmeticFaceValue` in the definitions of `velocity_n`, `velocity_p`, `D_n`, and `D_p`.
> 
> Some other problems you will quickly encounter:
> 
> * Don't declare `Pion` and `Nion` with `elementshape=(cell_num,)`. The `elementshape=` parameter is an advanced use and you should not use it unless you're following directly from one of our few examples that use it.  What you've done will create a variable that has `cell_num` distinct values _at every single cell_, so instead of creating a variable with 10 cells that has 10 distinct values, you've made a variable with 10 cells that has 100 distinct values.
> * If you want to use the Python [`time`](https://docs.python.org/3/library/time.html) package for `start = time.time()` and `end = time.time()`, then you need to give another name to the `Variable` tracking solution time.
> * `fipy.viewers.make` has not been a valid syntax for at least 8 years. Where did you see it used?
> * Expressions like `2*10**6` don't mean what you think they do. Often they will work, but often they will give you very large integers (because 10 is an integer). Scientific notation in Python is obtained with `2e6`, `6.62607015e-34`, etc.
> * Expressions like `20*10^(-9)` _**really**_ don't mean what you think they do. The `^` operator in Python is a bitwise exclusive or, so `10^(-11)` equals `-1`. Again, scientific notation in Python is obtained with `2e6`, `6.62607015e-34`, etc.
> 
> Once you get through all of that, you will find that the semiconductor drift-diffusion equations are miserable to solve. See #731 for some guidance on how you can improve solutions, but understand that while FiPy has been used to solve them, we don't have any robust examples.
Thank you very much Sir, for such a nice and elaborate answer. But after I rectify the code,  a new prolem induced. It always warns me: diffusion coefficient tensor is not an appropriate shape for this mesh.
I debugged it and found it running to:
`        while res > 1e-10:
            res = eq.sweep(dt=dt)`
it start to error. but I don't konw why.
Could you tell me how I could work this out? 
Any hint would be greatly appreciated!
Thank you in advance!
Daixing

The new code has been attached below:
`import numpy as np
from fipy import *
from matplotlib import pyplot as plt
from fipy.tools import numerix
from fipy.variables.faceGradVariable import _FaceGradVariable

def simulation(left_bias, right_bias):
    q = 1.602e-19  
    kb = 1.38e-23  
    epsilon_r=9
    epsilon = epsilon_r * 8.854e-14  # Permittivity C/V*cm
    T=300

    f = kb * T / q  # Einstein Relation V，
    #-----------------------------------------------------------------------
    #------------------------Geometry and mesh------------------------------
    #-----------------------------------------------------------------------
    def mesh_1d(length, cell_num):
        '''
        creat a 1D grid
        '''
        dx = length / cell_num
        mesh=Grid1D(dx=dx, nx=cell_num) 
        return mesh
    
    length=0.06
    cell_num=10
    mesh= mesh_1d(length,cell_num)
    #-----------------------------------------------------------------------
    #------------------------Description of the variables------------------------------
    #----------------------------------------------------------------------- 
    p_initial = np.zeros(cell_num)
    n_initial = np.zeros(cell_num)
    Pion = CellVariable(mesh=mesh, name='Positive ion Charge Density', value=p_initial,hasOld=True)
    Nion = CellVariable(mesh=mesh, name='Negative ion Charge Density', value=n_initial,hasOld=True) 
    potential = CellVariable(mesh=mesh, name='Potential',hasOld=True)
    potential[0]=(left_bias-right_bias)
    velocity_n = FaceVariable(mesh=mesh, rank=1)
    velocity_p = FaceVariable(mesh=mesh, rank=1)  
    D_n = FaceVariable(mesh=mesh, rank=1)
    D_p = FaceVariable(mesh=mesh, rank=1)
    v_n=CellVariable(mesh=mesh, name='Negative ion Charge velocity',hasOld=True) 
    v_p=CellVariable(mesh=mesh, name='positive ion Charge velocity',hasOld=True)    
    electricfield=-potential.grad
   
    velocity_n=1e3*electricfield*(1+(10*electricfield/(1260+electricfield))**4)**(-1/4)+ \
        1.91e7*(electricfield[0]/2.57e5)**5.7/(1+(electricfield/2.57e5)**5.7) #速度是电场的函数
    velocity_p=17*electricfield/(1+(17*electricfield[0]/(6.63e6))**1.75)**(1/1.75)
    D_n=f*velocity_n/electricfield
    D_p=f*velocity_p/electricfield
    v_n.steValue=1e3*electricfield[0]*(1+(10*electricfield[0]/(1260+electricfield[0]))**4)**(-1/4)+ \
        1.91e7*(electricfield[0]/2.57e5)**5.7/(1+(electricfield[0]/2.57e5)**5.7) 
    v_p.steValue=17*electricfield[0]/(1+(17*electricfield[0]/(6.63e6))**1.75)**(1/1.75)                                                        

    #-----------------------------------------------------------------------
    #------------------------Description of recombination-----------------------------
    #-----------------------------------------------------------------------    
    degen_fac=2 
    density=1e18
    sign=1.9e-15 
    sigp=1e-15
    ni=1.9e-10
    en=degen_fac*sign*v_n*ni*numerix.exp(1.2/0.026)
    ep=1/degen_fac*sigp*v_p*ni*numerix.exp(-1.2/0.026) 
    F_tA=(v_n*sign*Nion+ep)/(v_n*sign*v_p*sigp*Pion+ep+en)
    N_ionized=density*F_tA 
    Recn=(sign*v_n*density)*(density-N_ionized) 
    Recp=(sigp*v_p*density)*N_ionized 
    emisn=en*N_ionized 
    emisp=ep*(density-N_ionized)
    
    #-----------------------------------------------------------------------
    #------------------------Description of impact ionization-----------------------------
    #-----------------------------------------------------------------------    
    tE=1e-13 
    Ei_n=0.5  
    Ei_p=3.4-0.5
    e=1.
    lameda_E_n=v_n*tE   
    a_n=numerix.exp(-Ei_n/(e*(electricfield[0])*lameda_E_n))/lameda_E_n  
    lameda_E_p=v_p*tE  
    a_p=numerix.exp(-Ei_p/(e*(electricfield[0])*lameda_E_p))/lameda_E_p 
    n_impactgen=Nion*a_n*v_n
    p_impactgen=Pion*a_p*v_p

    #-----------------------------------------------------------------------
    #------------------------Description of photogeneration-----------------------------
    #-----------------------------------------------------------------------
    time=Variable()
    def get_photogeneration(time):
        a=0.25 
        beta=20e-9 
        y=0.0001 
        h=6.62607015e-34 
        c=3e8 
        tG=5e-9/1.177 
        I0=2e6/0.06/0.06
        I=I0*numerix.exp(-2*(time/tG)**2)
        lamada=532e-10
        photogen_rate=I*lamada*(a+beta*y*I+beta*I)*numerix.exp(-a*y)/(h*c*(1+beta*I*y)**2)
        return photogen_rate
        pass
    photogen=get_photogeneration(time)
    

    '''
    TransientTerm = dVar/dt
    ConvectionTerm = dVar/dx 
    DiffusionTerm = d^2Var/dx^2
    '''
    potential_equation = DiffusionTerm(coeff=1., var=potential)==-(q/epsilon)*(Pion - Nion)

    Pion_equation=TransientTerm(coeff=1., var=Pion)== ConvectionTerm(coeff=velocity_p, var=Pion) \
        +DiffusionTerm(coeff=D_p, var=Pion)+photogen+p_impactgen +emisp-Recp

    Nion_equation=TransientTerm(coeff=1., var=Nion) == ConvectionTerm(coeff=velocity_n, var=Nion) \
        +DiffusionTerm(coeff=D_n, var=Nion)+photogen+n_impactgen +emisn-Recn
          
    #boundery condition
    # Boundary conditions can be applied only to CellVariables. Direchlet Boundaries can easily be applied by using
    # the CellVariable.constrain method with a value and a definition of where. mesh.facesLeft or Right apply the
    # boundary condition to the furthest left and furthest right cell. One can also use a Boolean array where True
    # values define where to apply the boundary conditon.
           
    potential.constrain(left_bias, where=mesh.facesLeft)
    potential.constrain(right_bias, where=mesh.facesRight)

    eq = Pion_equation & Nion_equation & potential_equation
    
    # Iterate through a number of steps to solve equations with a set timestep 
    dt = 1e-11
    duration =20e-9 
    timestep = 0 
    elapsed =0 
    
    viewer1=Matplotlib1DViewer(vars=Pion, axes=plt.subplot(3, 1, 1))
    viewer2=Matplotlib1DViewer(vars=Nion, axes=plt.subplot(3, 1, 2))
    viewer3=Matplotlib1DViewer(vars=potential, axes=plt.subplot(3, 1, 3))
    plt.tight_layout()

    while elapsed < duration: 
        elapsed += dt
        timestep += 1
        Nion.updateOld()
        Pion.updateOld()
        photogen.setvalue=get_photogeneration(elapsed)
        res = 1e4
        while res > 1e-10:
            res = eq.sweep(dt=dt)
            print ("sweep")
            print (res)
            print (elapsed)          
            viewer1.plot()
            viewer2.plot()
            viewer3.plot()
        
simulation(1000, 0)
`

**Comment by guyer** [comment]
You have defined `D_n` and `D_p` as rank 1 vectors. Diffusivity is scalar (it can also be tensor, but not in your case).
