### ISSUE TITLE
Robin boundary condition for 1D non-linear reactive transport problem

### ISSUE THREAD

**Issue by eugenio-pino** [usnistgov/fipy#751]
Hi everybody,
I'm running into some issues with Robin BCs for a 1D, two coupled equations non-linear problem. I'm attaching the script and images with both problem description (switch C_1 -> u, C_2 -> v) and error encountered.

I've followed [the procedure in Using FiPy](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#applying-robin-boundary-conditions) since both equations are linear in both advection and diffusion, but the runtime error I'm encountering is attached, and is about a dimension mismatch and a truedivide error. Moreover, if I use a simple Dirichlet condition I obtain close, but not equal results (look at the red functions in the expected plot), so I effectively have to give the actual Robin conditions a shot.

How can I proceed from here?

[monod.zip](https://github.com/usnistgov/fipy/files/5107624/monod.zip)

Thank you in advance,
Eugenio Pino

**Comment by guyer** [comment]
I would not expect a Robin condition to hold the boundary at 1. The Robin condition couples the value with the gradient at the boundary, but places no restriction on their individual values.

You are using the Robin formulation as though the boundary *flux* is specified, but the relevant sentences in your `boundary_condition.png` file are:
> The ... inflow concentration $C_2$ of bacteria is 0.1. We assume that the ... inflow concentration [of $C_1$] is fixed at 1.

These do not describe the boundary flux, rather the boundary value. 

If I remove the Robin constraint and leave just the Dirichlet condition
```diff
diff --git a/linear_retardation_distinct_monod_non-linear_robin.py b/linear_retardation_distinct_monod_non-linear_robin.py
index 926d45c..953483e 100644
--- a/linear_retardation_distinct_monod_non-linear_robin.py
+++ b/linear_retardation_distinct_monod_non-linear_robin.py
@@ -26,11 +26,8 @@ final_time = 0.6 # yr
 exact_timestep = 0.01
 
 # parameters
-mask = mesh.facesLeft
 V = FaceVariable(mesh = mesh, value = 1.1, rank = 1)
-V.setValue(0., where = mask)
 D = FaceVariable(mesh = mesh, value = 1e-3)
-D.setValue(0., where = mask)
 lambda_1 = 16.
 lambda_2 = 0.25
 K = 0.5
@@ -70,16 +67,14 @@ monod_kinetics_global_equation_u = \
     TransientTerm(var = u, coeff = R1) == \
         -PowerLawConvectionTerm(var = u, coeff = V) \
         +DiffusionTerm(var = u, coeff = D) \
-        -ImplicitSourceTerm(var = u, coeff = R1 * r_u) \
-        +(u_inj * mask * mesh.faceNormals).divergence
+        -ImplicitSourceTerm(var = u, coeff = R1 * r_u)
 
 monod_kinetics_global_equation_v = \
     TransientTerm(var = v, coeff = R2) == \
         -PowerLawConvectionTerm(var = v, coeff = V) \
         +DiffusionTerm(var = v, coeff = D) \
         +ImplicitSourceTerm(var = v, coeff = R2 * 0.5 * r_v) \
-        -ImplicitSourceTerm(var = v, coeff = R2 * lambda_2) \
-        +(v_inj * mask * mesh.faceNormals).divergence
+        -ImplicitSourceTerm(var = v, coeff = R2 * lambda_2)
 monod_kinetics_global_equation = \
     monod_kinetics_global_equation_u & monod_kinetics_global_equation_v
 ##################
```
then I get a solution very much like in your `expected_plot.png`:
![linear_retardation_monod_kinetics-double-plot](https://user-images.githubusercontent.com/1830725/91056791-65beb780-e5f4-11ea-841a-51a5de43d69c.png)

**Comment by eugenio-pino** [comment]
Thank you for your time, now that closes the issue.
Eugenio
