### ISSUE TITLE
Imposing a space-and-time-dependent function as boundary conditions

### ISSUE THREAD

**Issue by eugenio-pino** [usnistgov/fipy#753]
I have a rather complicated, space-and-time dependent analytical form for a boundary condition
![Screenshot from 2020-09-01 00-48-26](https://user-images.githubusercontent.com/56413199/91776038-e8470880-ebec-11ea-8d4d-b9395a13de7d.png)

When using the FiPy embedded mesh the solution is simple even if unefficient: at each time-step release the CellVariable, define a Constrain applying the function to a numpy.linspace array and  constrain it back again.
When instead using gmsh I can no more use a linspace array: I understand how to do it for the time variable, [as it was done here
](https://stackoverflow.com/a/56244350/5794332), but how about the space dependence? Should I define a space-dependent mask? If so, how? Fortunately, at least this Dirichlet BC is on the left side, which is uniform.

[Here is the code without gmsh](https://pastebin.pl/view/94fd1010)
[Here is the gmsh mesh](https://pastebin.pl/view/13ef130f), which by the way is non-uniform on one direction

**Comment by guyer** [comment]
I don't think it's necessary to release and reapply the constraints. I've rewritten your code (plus a bunch of fixes that kept it from running in the first place) to define the constraint in terms of a `Variable` condition that depends on `t` and `Z`: https://pastebin.pl/view/7b287e5b

Simplistically, define
```python
t = Variable(value=0.)
Z = mesh.faceCenters[0]
```
then write your constraint in terms of these, but multiply the whole expression by `(Z <= v * t)`. To avoid negative square roots, I multiply by the discriminant in there, too. This does result in a divide-by-zero when `Z == v * t`, but it appears harmless; you could add a small epsilon in the denominator if you wanted to avoid that.

**Comment by eugenio-pino** [comment]
Thank you.
In your code I see `Z = mesh.faceCenters[1]` written instead. It is the one that leads to the right output, but in the documentation it is not detailed: it does contain the y coordinate of all faces ordered left to right, bottom to top. Right? Printing output like `print(Grid2D(nx = 5, dx = 1, ny = 3, dy = 1).faceCenters[1])` seemed to confirm this. 
Then I guess that the function is lazily evaluated at these `faceCenters` and then actually evaluated when the `where = mesh.facesLeft` kicks in.

**Comment by guyer** [comment]
Ah, yes, that was a typo above (fixed now).
`faceCenters` appears not have its own docstring, but its use is illustrated [here](https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#applying-spatially-varying-boundary-conditions) and in many of the examples, including [`examples.diffusion.mesh1D`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh1D.html), [`examples.diffusion.mesh20x20`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh20x20.html), and [`examples.diffusion.circle`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.circle.html).

We make no promises about the ordering of `faceCenters`, other than the ordering is self-consistent (the ordering of `faceCenters` will agree with the ordering of the `facesLeft` mask).

The expression is lazily evaluated, as you say, and will be reevaluated whenever one of its dependent `Variables` changes; in this case `Z` never changes, but `t` does.

**Comment by eugenio-pino** [comment]
Thank you for your time!
