### ISSUE TITLE
fit pde solution to data

### ISSUE THREAD

**Issue by Arianna31221** [usnistgov/fipy#754]
Hi!

 I have solved a pde (second Fick's law with non-uniform diffusivity) .

I now would like to estimate the diffusion coefficient in one of the layers by fitting solutions of the pde to the measurements.

I am new to Fipy, and would greatly appreciate any suggestions you may have on how to proceed!

Many thanks in advance!

**Comment by wd15** [comment]
This is a cross post from [Stackoverflow](https://stackoverflow.com/questions/63691613/fit-pde-solution-to-data). I've posted a suggestion there.

**Comment by guyer** [comment]
Interesting problem. As @wd15 suggests on [StackOverflow](https://stackoverflow.com/q/63691613/2019542), `scipy.optimize` has useful routines.

I put together a [notebook](https://gist.github.com/guyer/0685c118b013f13feb1f3987ec9b9d6f) that combines the example code from [`scipy.optimize.curve_fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) with our steady-state diffusion example with non-uniform-diffusivity in [`examples.diffusion.mesh1D`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh1D.html).

**Comment by Arianna31221** [comment]
Thank you @wd15 for suggesting to look at  scipy.optimize !

@guyer , thanks for putting together the example code from scipy.optimize.curve_fit with fipy steady-state diffusion example : that's exactly what I was looking for!

Thank you both for your quick response.
