### ISSUE TITLE
QUESTION: Where are the unittests? Why is the coverage 0%?

### ISSUE THREAD

**Issue by agy-why** [usnistgov/fipy#756]
Dear developers,

After looking at the flags you publish in the readme, I found that fipy has a coverage of 0%. Therefore I had a look at the source, and I could not find unittests? The only tests I could find were obscure import tests and similar technical tests, but no real unittests suite nor a functional-test suite. Are they publish else where?

I wish you a nice evening,

Yori

**Comment by guyer** [comment]
FiPy runs doctests, invoked from [`fipy/tests/test.py`](https://github.com/usnistgov/fipy/blob/master/fipy/tests/test.py). The tests themselves are in the docstrings of the code and in the [`examples/`](https://github.com/usnistgov/fipy/blob/master/examples/) directory.

I'm not aware that we link to any report of test coverage. Where are you seeing this?

**Comment by agy-why** [comment]
Dear Guyer,

Yeah thanks I found it out yesterday while looking at the source of the classes, not just the `test.py`

the coverage set to zero can be found here: https://app.codacy.com/manual/tkphd/fipy/dashboard (followed code quality B)

I think this need to be changed somehow, fipy is well tested.

I wish you a nice day,

Yori

**Comment by guyer** [comment]
Ah, but that doesn't say coverage is zero. It says that coverage isn't being looked at.

**Comment by guyer** [comment]
Coverage is addressed in #410
