### ISSUE TITLE
Contact Heat Resistance

### ISSUE THREAD

**Issue by stakehr** [usnistgov/fipy#757]
I'm new to fipy.
I would like to solve the heat transfer problem involving contact resistance. I tried to write the code with reference to the manual, but it doesn't work, so please let me know.
https://www.ctcms.nist.gov/fipy/documentation/USAGE.html#internal-fixed-gradient
the code is below

```python
from fipy import CellVariable, FaceVariable, Viewer, meshes, Grid2D
from fipy import DiffusionTerm, TransientTerm, ImplicitSourceTerm

mesh = Grid2D(Lx=0.1,Ly=0.003, dx=0.001,dy=0.001)
T = CellVariable(mesh=mesh,value=1200.)
viewer = Viewer(vars=T)
mask = mesh.cellCenters.value[0] > 0.05
T[mask] = 350.
viewer.plot()

T.constrain(1200, mesh.facesLeft)
T.constrain(350., mesh.facesRight)

k=340.  # [J/m.K.s]
rho=8920.  # [kg/m3]
cp = 380.  # [J/kg.K]
alpha0 = k/cp/rho  # [m2/s]
alpha = FaceVariable(mesh=mesh, value=alpha0)
h = 5000.  # [J/m2.K]

largevalue = 1e+10
mask = (mesh.faceCenters[0] == 0.05)
deltaT = T[mesh._adjacentCellIDs[0][mask]] - T[mesh._adjacentCellIDs[1][mask]]
gradient = FaceVariable(mesh=mesh,value=0.)
gradient[mask] = h/k*deltaT


alpha[mask.value] = 0.
eqn = TransientTerm() == DiffusionTerm(coeff=alpha)\
        +DiffusionTerm(coeff=largevalue * mask)\
          -ImplicitSourceTerm(mask*largevalue*gradient*mesh.faceNormals).divergence

for i in range(20):
  deltaT = T[mesh._adjacentCellIDs[0][mask]] - T[mesh._adjacentCellIDs[1][mask]]
  gradient = h/k*deltaT
  eqn.solve(T,dt=0.02)
  viewer.plot()
```

①
When I run it, I get the following error "TypeError: The coefficient can not be a FaceVariable." 
The manual says "The mask variable would typically be a FaceVariable Boolean constructed using the face center values", so I don't think the mask is a problem, how can I fix it?

②
Assuming I get through question①, ImplicitSourceTerm Class have divergence method ??
I didn't know how to use it. 
If it's not available, is there any other way to solve the contact thermal resistance?

**Comment by wd15** [comment]
There are a few things that are messed up here:
 
 - I think you meant to write `mask * largevalue * gradient` nd not `masklargevaluegradient`.
 - The coefficient for ImplicitSourceTerms must either take single valued floats or cell variables. They don't take face variables.
 - You can't take the divergence of an `ImplicitSourceTerm`.

I think that you've put the `.divergence` operator in the wrong place. If you use `-ImplicitSourceTerm((mask * largevalue * gradient * mesh.faceNormals).divergence)` then it runs.
