### ISSUE TITLE
Status of sphericalUniformGrid1D

### ISSUE THREAD

**Issue by bennygit** [usnistgov/fipy#759]
Hello, 

I used the sphericalUniformGrid1D for simulations and it seems to be working good and my tests showed that the results are in agreement with known analytical solutions of my simplified problem. 
To use it I added the corresponding python file name to the __init__.py file so that it can be found inside the fipy package. 

What is the official status of that grid? I think it is working fine. Will it be officially implemented in near future?

Thanks!

**Comment by wd15** [comment]
I'm confused. The file `sphericalUniformGrid1D.py` is in `fipy/meshes`, which has an `__init__.py`. See, https://github.com/usnistgov/fipy/tree/master/fipy/meshes. Are you looking at a very old version of FiPy without the same structure as master?

**Comment by bennygit** [comment]
Thank you very much. Just a simple manual update did the trick. It is working like a charm now.
