### ISSUE TITLE
Equations on Website don't show right

### ISSUE THREAD

**Issue by NicoC0D3S** [usnistgov/fipy#762]
Hi all, 
I got an issue concerning your website, all the equations don't show right for me. Is this a known issue or am I the only one? Do you have any suggestions on how to fix this? I'm using firefox, but I already tried it on different browsers and different systems.
Regards Nico

Example: https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.coupled.html
![grafik](https://user-images.githubusercontent.com/72972489/97679578-b68bda00-1a95-11eb-837f-7f3156a8113b.png)

**Comment by guyer** [comment]
I recently pushed a new set of docs to fix something else and apparently broke this. Thanks for reporting.
