### ISSUE TITLE
With regards to 2D diffusion example, accessing mesh

### ISSUE THREAD

**Issue by matthijsnuus** [usnistgov/fipy#765]
Hey all, 

I'm trying to use the 2D diffussion (20x20) example as a little set up for a magma chamber model set up. I was wondering if there's an easy way to access the mesh with regards to setting up initial temperatures in the middle of the mesh. The example shows how to change boundary conditions on the boundaries of the mesh and shows how to change the entire initial condition to a certain temperature, but not how to change specific parts of the mesh to a certain initial temperature. 
Could somehow help me with this? 

I assume it has to be implemented in the value part of this CellVariable?
phi = CellVariable(name = "solution variable",
                   mesh = mesh,
                   value = -8.)

Thanks in advance.

**Comment by guyer** [comment]
You can assign the values parametrically, e.g.,
```python
x, y = mesh.cellCenters
phi.setValue(???, where=(x - cx)**2 + (y - cy)** < r**2)
```
You can do this at any time before you try to solve using these values; it doesn't have to be when the variable is declared.

This is illustrated in [`examples.diffusion.mesh1D`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh1D.html), [`examples.diffusion.electrostatics`](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.electrostatics.html), and [`examples.phase.impingement.mesh20x20`](https://www.ctcms.nist.gov/fipy/examples/phase/generated/examples.phase.impingement.mesh20x20.html), among others.

**Comment by matthijsnuus** [comment]
@guyer thanks for the help. The problem has been resolved
