### ISSUE TITLE
Fipy Two Coupled PDEs

### ISSUE THREAD

**Issue by MEskandari47** [usnistgov/fipy#766]
Hi,
I gonna solve two coupled equations with fipy library. I write program according to Fipy documentations, but equations didn't be solved. The description of equations is in the PDF file below.
[TTM.pdf](https://github.com/usnistgov/fipy/files/5615941/TTM.pdf)

Thanks all for any suggestion and help.
I have solved equations in 1D. My Python code is shown as below:

```python
from fipy import *
import matplotlib.pyplot as plt
Lx=1.#mm
nx=50
T_e_t0=300 #Kelvin
G=1E17  #W/m^3/K
t_p=10  #fs
d=13  #optical penetration in nm
l_b=15  #balestic length in nm
w_0=6  #beam waist in um
R=0.95  #reflectivity
J=30000  #Fluence J/m^2
gamma=70.87  #J/m^3/K^2
C_l=3.46E6  #J/m^3/K
T_F=8.12E4  #K
timeStepDuration=0.001*t_p
K_0=377  #W/m/K
eta=0.139

m=Grid1D(nx=nx, dx=Lx/nx)
x = m.cellCenters[0]
time = Variable(0.)
S=((0.94*(1-R)*J)/(t_p*(d+l_b)))*numerix.exp(-2.77*(time/t_p)**2)*numerix.exp(-2*(x/w_0)**2)
#print(S)

T_e=CellVariable(name="Electron Temperature", mesh=m, value=T_e_t0, hasOld=True)
T_l=CellVariable(name="Phonon Temperature", mesh=m, value=T_e_t0, hasOld=True)

theta_e=T_e/T_F
theta_l=T_l/T_F
K_e=K_0*(((theta_e**2+0.16)**(5/4))*(theta_e**2+0.44)*theta_e/((theta_e**2+0.092)**(1/2))*(theta_e**2+eta*theta_l))

eq_e=TransientTerm(coeff=gamma*T_e, var=T_e)==DiffusionTerm(coeff=K_e, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_e)+ImplicitSourceTerm(coeff=G, var=T_l)+S
eq_l=TransientTerm(coeff=C_l, var=T_l)==ImplicitSourceTerm(coeff=G, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_l)
eq=eq_e & eq_l


T_i = Viewer(vars=(T_e, T_l))
results_T_e = []
results_T_l = []
t_list=[]
steps=(int(3*t_p/timeStepDuration))
#print(steps)
for t in range(0, 10):
    T_e.updateOld()
    T_l.updateOld()
    res=1e+3
    while res > 0.1:
        res=eq.sweep(dt=timeStepDuration)
        print(res)
    #res=eq.solve(dt=timeStepDuration)
    time.setValue(time + timeStepDuration)
    #print(time)
    if __name__=='__main__':
        T_i.plot()
```

**Comment by guyer** [comment]
A few things to look at: 
- At the beginning of the run, you should see several warnings
  ```
  UserWarning: sweep() or solve() are likely to produce erroneous results when `var` does not contain floats.
  ```
  To address this, change the initial temperature to `T_e_t0=300.0 #Kelvin`
- FiPy does not report scaled residuals, so there is no magic to 0.1 (FiPy reports Mx - b). I recommend sweeping 10 or more times and watching the residual to understand the convergence of your particular equations. The behavior of the first few timesteps can be very different from the solution once it starts to evolve.
- I would take a close look at units. For example, 
  - S divides J (in J/m^2) by (d+l_b) (in nm) and t_p (in fs), but K_0 is in W/m/K and your mesh is in mm. That looks to me like S will be in units of 1e21 J/(m^3.s), but the diffusion term will be in units of 1e6 J/(m^3.s)

  If I increase the magnitude of S by many orders of magnitude, I can observe *something* happening.

**Comment by MEskandari47** [comment]
Thank you so much.
I have played with values and something starts to happen. so you're right about units.
I wanna solve these equations in 15 picoseconds and source term, S depends to time.
I wanna investigate electron an lattice temperature respect to time but `plt.plot(t_list,results_T_l)
plt.show()` doesn't work.

My modified code has shown below:
`from fipy import *
import matplotlib.pyplot as plt
Lx=1.#mm
dx=1.0e-6 #um
nx=Lx/dx
T_e_t0=300.0 #Kelvin
G=1E17  #W/m^3/K
t_p=10e-15  #fs
d=13e-9  #optical penetration in m
l_b=15e-9  #balestic length in m
w_0=6e-6  #beam waist in m
R=0.95  #reflectivity
J=30000  #Fluence J/m^2
gamma=70.87  #J/m^3/K^2
C_l=3.46E6  #J/m^3/K
T_F=8.12E4  #K
timeStepDuration=10*t_p
K_0=377.0  #W/m/K
eta=0.139

m=Grid1D(nx=nx, dx=Lx/nx)
x = m.cellCenters[0]
time = Variable(0.)
S=((0.94*(1-R)*J)/(t_p*(d+l_b)))*numerix.exp(-2.77*(time/t_p)**2)*numerix.exp(-2*(x/w_0)**2)


T_e=CellVariable(name="Electron Temperature", mesh=m, value=T_e_t0, hasOld=True)
T_l=CellVariable(name="Phonon Temperature", mesh=m, value=T_e_t0, hasOld=True)

theta_e=T_e/T_F
theta_l=T_l/T_F
K_e=K_0*(((theta_e**2+0.16)**(5/4))*(theta_e**2+0.44)*theta_e/((theta_e**2+0.092)**(1/2))*(theta_e**2+eta*theta_l))

eq_e=TransientTerm(coeff=gamma*T_e, var=T_e)==DiffusionTerm(coeff=K_e, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_e)+ImplicitSourceTerm(coeff=G, var=T_l)+S
eq_l=TransientTerm(coeff=C_l, var=T_l)==ImplicitSourceTerm(coeff=G, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_l)
eq=eq_e & eq_l


T_i = Viewer(vars=(T_e, T_l))
#T_i = Viewer(T_e)
#S_list=[]
results_T_e = []
results_T_l = []
t_list=[]
#steps=(int(3*t_p/timeStepDuration))
#print(steps) 
while time()<40e-15:
    #print(time())
    T_e.updateOld()
    T_l.updateOld()
    for i in range(10):
        res=eq.sweep(dt=timeStepDuration)
        print(res)
    #res=eq.solve(dt=timeStepDuration)
    t_list.append(time())
    results_T_l.append(T_l.value)
    results_T_e.append(T_e.value)
    time.setValue(time() + timeStepDuration)
    #S_list.append(S)
    #print(time)
    if __name__=='__main__':
        T_i.plot()
#print(results_T_l)
print(t_list)
#plt.plot(t_list,results_T_l)
#plt.show()`

Thanks for helping.

**Comment by guyer** [comment]
What were you hoping to see? `t_list` holds a single float, but `results_T_l` holds an array of values. matplotlib doesn't know anything about how to plot these against each other.

**Comment by guyer** [comment]
As an aside, your units still need attention. The comment says that `L` is in mm and that `dx` is in m, but those are only comments, so the net result is that your mesh has a million grid points where before it only had 50. It's very unlikely that you need a million grid points.

In general, I wouldn't leave the unit comments as they are. `t_p=10e-15  #fs` implies that `t_p` is 1e-29 s, which I don't think is what you mean. I'd pick a consistent set of units, e.g. mks, and label accordingly.

**Comment by MEskandari47** [comment]
I'm sorry for confusion. I edited the code:

```python
from fipy import *
import matplotlib.pyplot as plt
Lx=1.0e-3#m
dx=1.0e-6 #m
nx=Lx/dx
x_0=Lx/2
T_e_t0=300.0 #Kelvin
G=1E17  #W/m^3/K
t_p=10e-15  #s
d=13e-9  #optical penetration in m
l_b=15e-9  #balestic length in m
w_0=6e-6  #beam waist in m
R=0.95  #reflectivity
J=0.1e+4  #Fluence J/m^2
gamma=70.87  #J/m^3/K^2
C_l=3.46E6  #J/m^3/K
T_F=8.12E4  #K
timeStepDuration=20*t_p
K_0=377.0  #W/m/K
eta=0.139

m=Grid1D(nx=nx, dx=dx)
x = m.cellCenters[0]
time = Variable(0.)
S=((0.94*(1-R)*J)/(t_p*(d+l_b)))*numerix.exp(-2.77*(time/t_p)**2)*numerix.exp(-2*((x-x_0)/w_0)**2)


T_e=CellVariable(name="Electron Temperature", mesh=m, value=T_e_t0, hasOld=True)
T_l=CellVariable(name="Phonon Temperature", mesh=m, value=T_e_t0, hasOld=True)

theta_e=T_e/T_F
theta_l=T_l/T_F
K_e=K_0*(((theta_e**2+0.16)**(5/4))*(theta_e**2+0.44)*theta_e/((theta_e**2+0.092)**(1/2))*(theta_e**2+eta*theta_l))

eq_e=TransientTerm(coeff=gamma*T_e, var=T_e)==DiffusionTerm(coeff=K_e, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_e)+ImplicitSourceTerm(coeff=G, var=T_l)+S
eq_l=TransientTerm(coeff=C_l, var=T_l)==ImplicitSourceTerm(coeff=G, var=T_e)-ImplicitSourceTerm(coeff=G, var=T_l)
eq=eq_e & eq_l
results_T_e = []
results_T_l = []
t_list=[]
while time()<15000e-15:
    #print(time())
    t_list.append(float(time()))
    results_T_l.append(float(T_l.max()))
    results_T_e.append(float(T_e.max()))
    T_e.updateOld()
    T_l.updateOld()
    for i in range(10):
        res=eq.sweep(dt=timeStepDuration)
    time.setValue(time() + timeStepDuration)
print(t_list)
print(results_T_e)
print(results_T_l)
plt.plot(t_list,results_T_e,'r',label="Electron Temperature")
plt.plot(t_list,results_T_l,'b',label="Lattice Temperature")
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.legend(loc="upper left")
plt.show()
```

For plotting T_e and T_l in time, I added 

``` python  
t_list.append(float(time()))
results_T_l.append(float(T_l.max()))
results_T_e.append(float(T_e.max()))
```
and the answer seems true, but I'm not sure why it works!
The graph is below:
![Temp](https://user-images.githubusercontent.com/75238372/101476196-a273ac00-3962-11eb-97a0-5dcc89692854.png)

**Comment by guyer** [comment]
I think this question has been addressed, but if you need further help, please reopen.
