### ISSUE TITLE
Can't solve 2D problem on the 3D surface

### ISSUE THREAD

**Issue by comcon1** [usnistgov/fipy#774]
Dear all!

I can't understand what is the proper way to solve 2D problem on 3D surface. If I load mesh with `Gmsh2D` function, 

```
mesh = fipy.Gmsh2D('hemi.msh')
```

.. the code (as I understand) simply remove Z coordinate. If I load a mesh with `Gmsh2DIn3DSpace` and then, e.g. request faceGrad property the code can't evaluate it:

```
mesh = fipy.Gmsh2DIn3DSpace('hemi.msh')
VAB = fipy.CellVariable(name="A", mesh=mesh, value=1.0)
print(VAB.faceGrad)
```
The error message is:

```
ValueError: operands could not be broadcast together with shapes (2,14234) (3,14234)
```

Is the only way to solve 2D problem is to convert it into thin-layer 3D-problem by the way described in [cahnHiliard.sphere example](https://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.sphere.html)?

**Comment by guyer** [comment]
> Is the only way to solve 2D problem is to convert it into thin-layer 3D-problem by the way described in cahnHiliard.sphere example?

Yes, I think so. FiPy has no way to sense the curvature of a truly 2D surface. I'd have thought that the problem would "work", but be wrong, but I'm not altogether surprised about the `ValueError`.
