### ISSUE TITLE
Solving Fick's second law of diffusion in 1D sphere

### ISSUE THREAD

**Issue by Sasiain** [usnistgov/fipy#780]
Hi everyone!

I'm trying to evaluate Fick's second law of diffusion for a 1D sphere with certain fixed flux boundary conditions, such as: 

![Fick2](https://user-images.githubusercontent.com/79087709/107942712-ea7b0480-6f8b-11eb-8ada-ab7dbaa7934d.PNG)
![Boundary fick](https://user-images.githubusercontent.com/79087709/107943101-7725c280-6f8c-11eb-97ce-8683114554d8.png)

The equation, the input values and the expected results are obtained from [this study.](https://doi.org/10.1016/j.electacta.2019.134797)

Even if I tried to follow the keypoints that are displayed on the FiPy documentation, I didn't get the results I expect. The code I wrote looks at the moment like the following. Any suggestion of what could possibly be wrong would be welcomed. Thank you in advance!

```
from fipy import Viewer, TransientTerm, DiffusionTerm, SphericalGrid1D, CellVariable
from builtins import range

nr = 100 #number of cells on the mesh
r_ca = 8.5e-6 #cathode radius

Iapp = -1*1.656 #Current [A] discharge
F = 96485.33212331001 #Faraday constant
S_ca = 1.1167 #Surface of cathode
D_ca = 1e-14 #Diffusion coef.

csMax_ca = 51410;
csMax_an = 31833; 
Xinit_ca = 0.4952 #[p.u.]
Xinit_an = 0.7522

BoundaryR0 = 0 #Fixed flux at r=0
BoundaryR1_ca = Iapp/(S_ca*F) #Fixed flux at r=r_ca

mesh = SphericalGrid1D(nr=nr, Lr=r_ca) 
X_ca = CellVariable(mesh=mesh, name='Concentration cathode', value=Xinit_ca*csMax_ca) 
X_ca.faceGrad.constrain([BoundaryR1_ca], mesh.facesRight) #Fixed flux boundary condition
X_ca.faceGrad.constrain(BoundaryR0, mesh.facesLeft)

eq_ca = TransientTerm() == DiffusionTerm(coeff=D_ca) # dX/dt = D/r^2 * d/dr(r^2*dX/dr)

SimLen = 1600 #s
tstep = 0.5 #s
Nstep = int(SimLen/tstep)

for step in range(Nstep):
    eq_ca.solve(var=X_ca, dt=tstep)

viewer = Viewer(vars=X_ca/csMax_ca, datamin=0., datamax=1.)
```

**Comment by guyer** [comment]
Not sure why this was closed, but for anyone finding this issue, please see [StackOverflow](https://stackoverflow.com/a/66164424/2019542).
