### ISSUE TITLE
how to solve PFC FiPy imported gmsh, which is converted from .msh Ansys format, error

### ISSUE THREAD

**Issue by alisheikholeslam** [usnistgov/fipy#782]
when I imported converted mesh (.msh Ansys mesh format to gmsh 2 by meshio) by FiPy.Grid3D("....msh") code and run darcy code by ipython ,embedded in PFC ITASCA, the following error appeared. thank you for helping solve this issue
(FiPy in this software is version 3.1)
(Python in PFC is version 2.7)
mesh.vtk file:
[wrote by meshio from vtk.zip](https://github.com/usnistgov/fipy/files/6056811/wrote.by.meshio.from.vtk.zip)

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.
Traceback (most recent call last):
  File "<itasca-code-0-19def0f6e02e>", line 116, in <module>
  File "<itasca-code-0-19def0f6e02e>", line 11, in __init__
  File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\meshes\factoryMeshes.py", line 111, in Grid3D
    if numerix.getShape(dx) == ()   File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\tools\numerix.py", line 242, in getShape
    raise AttributeError, "No attribute 'shape'"
AttributeError: No attribute 'shape'

**Comment by guyer** [comment]
`Grid3D` doesn't read Gmsh meshes. You want [`Gmsh3D`](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.meshes.html#fipy.meshes.gmshMesh.Gmsh3D).
