### ISSUE TITLE
Some questions about radial inflow of cylinder model

### ISSUE THREAD

**Issue by alisheikholeslam** [usnistgov/fipy#789]
I have coupled PFC software by FiPy in python (PFC v5 python v2.7 FiPy v3.1). A converted .msh mesh file is imported by Gmsh3D.
Q1: Is there any way to find out mesh numbers in the cylindrical coordinates automatically? Could I find out the number of upper surface meshes with any code like 'self.mesh.facesTop', when cylinder is hollow and its height is in Z direction? Is 'self.mesh.facesTop' only works for Grid2D, not Gmsh3D?

I have determined boundary (Boundary_ro) wall of cylinder by a created 'list' in python. I have to change this list and 'solver.mesh.getFaceCenters()' to numpy and then to list again to run the code.
Q2: I don't understand why? I think their types become same in this manner. The code is:
```
solver.inlet_mask = np.array(list(map(np.array(Boundary_ro).tolist().__contains__, np.transpose(solver.mesh.getFaceCenters()).tolist())))
```
This problem is also the same for other codes that I mentioned in 'https://stackoverflow.com/questions/66623145/how-to-get-boolean-matrix-for-similar-lists-in-two-different-size-numpy-arrays-o/66634046#66634046'

Besides the aforementioned codes, following code is used too, It shows the same faces for outlet as the other codes, but I didn't understand why this code did not work as outlet when the program runs and takes 0 for flow rate at the beginning of the simulation, which must be a specified flow-rate number.
```
fx, fy, fz = solver.mesh.getFaceCenters()
solver.outlet_mask = np.logical_and.reduce([np.sqrt(fx ** 2 + fy ** 2) < 0.1])
```
The main problem of my coupling process, now, is for applying radial inflow rate to the solver. I have wrote the following code in python and tested it in the PFC software for radial force, and it worked.
```
pc_xyy = np.array(Boundary_ro)                                 # is in numpy type
pc_xyy[:, 2] = 0.0
F = force*(pc_xyy.T / np.linalg.norm(pc_xyy, axis=1)).T
```
For solver.inlet_flow, I tried to do as above but the results in PFC showing that the code I have wrote is not as it must be.
```
class DarcyFlowSolution(object):
    .
    def set_inflow_rate(self, flow_rate):
        pc_xyy = np.array(Boundary_ro)                                 # is in numpy type
        pc_xyy[:, 2] = 0.0
        self.flow_rate = flow_rate*(pc_xyy.T / np.linalg.norm(pc_xyy, axis=1)).T
        self.inlet_area = (self.mesh.scaledFaceAreas*self.inlet_mask).sum()
        self.outlet_area = (self.mesh.scaledFaceAreas*self.outlet_mask).sum()
        self.Uin = flow_rate/self.inlet_area
        inlet_mobility = (self.mobility.getFaceValue() * \
                              self.inlet_mask).sum()/(self.inlet_mask.sum()+0.0)
        self.pressure.faceGrad.constrain(
            ((0,),(-self.Uin/inlet_mobility,),(0,),), self.inlet_mask)
     .

if __name__ == '__main__':
    solver = DarcyFlowSolution()
    .
    solver.set_inflow_rate(flow_rate)                    # where flow_rate is a number
    solver.set_pressure(0.0, solver.outlet_mask)
    .
```
Q3: How to apply inflow_rate of  -1e-5, for example, to each cell faces of outer boundary (cylinder wall)? Is there any other simpler form to do so in FiPy for radial flow?

Q4: Is there any viewer to view imported gmsh3d mesh, determined boundary lists, and the solver applied force or flow rate directions?

**Comment by guyer** [comment]
> Q1: Is there any way to find out mesh numbers in the cylindrical coordinates automatically? Could I find out the number of upper surface meshes with any code like 'self.mesh.facesTop', when cylinder is hollow and its height is in Z direction? Is 'self.mesh.facesTop' only works for Grid2D, not Gmsh3D?

A1: `mesh.facesTop` is [defined](https://github.com/usnistgov/fipy/blob/15d76683005162451b3fc6840aa00d9b0eb35ba1/fipy/meshes/abstractMesh.py#L856) as those faces where `y == max(y)`. It works on any mesh with at least two dimensions.

> Q2: I don't understand why?

 A2: I don't understand why, either. I don't know what a `solver.inlet_mask` or `solver.outlet_mask` is, but I'm guessing something from Itasca? We don't have that code, we don't use that code, we don't support that code.

> Q3: How to apply inflow_rate of -1e-5, for example, to each cell faces of outer boundary (cylinder wall)? Is there any other simpler form to do so in FiPy for radial flow?

A3: This sounds like another question to ask the Itasca developers. What FiPy equations are you solving?

> Q4: Is there any viewer to view imported gmsh3d mesh, determined boundary lists, and the solver applied force or flow rate directions?

A4: FiPy can communicate with [Mayavi](https://docs.enthought.com/mayavi/mayavi/), which is a powerful Vtk viewer. We show an [example](https://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.sphere.html) of rendering in a [custom Mayavi viewer](https://github.com/usnistgov/fipy/blob/master/examples/cahnHilliard/sphereDaemon.py). You can also export with a [`VTKViewer`](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.viewers.vtkViewer.html#fipy.viewers.vtkViewer.vtkViewer.VTKViewer) and render in something like [ParaView](https://www.paraview.org/) or [VisiIt](https://wci.llnl.gov/simulation/computer-codes/visit).

**Comment by alisheikholeslam** [comment]
Thank you dear Dr. Guyer for your frequent advises on my project, so far.
'solver.inlet_mask' is a Boolean numpy array that shows which of mesh faces are inlet faces and which are not. The size of the array is equal to the total number of the mesh faces.
Brief explanation: Aim of the ITASCA original code is to couple PFC by Python to solve solid_fluid coupled problems in microscale, which is achieved by PFC embedded FiPy (PFC is a solid base software and must be coupled or codded to consider  fluid ). The code can be seen in:
http://docs.itascacg.com/pfc600/pfc/docproject/source/manual/optional_features/cfd_option/cfd_darcy.html?highlight=darcy
FiPy application and placement in the code is clarified and summarized by 'Green' font, if you would like to skim.
A1 and A4 were very helpful, thanks. For my last question in finalization of the simulation, i.e. Q3, the problem is how to enter specified flow rate value and directions (as codded above), which, as you mentioned, seems to be related to Itasca developers.

**Comment by guyer** [comment]
`np.sqrt(fx ** 2 + fy ** 2) < 0.1` already is a Boolean numpy array of which faces should be included. What is `np.logical_and.reduce([...])` intended to do?

> For my last question in finalization of the simulation, i.e. Q3, the problem is how to enter specified flow rate value and directions (as codded above), which, as you mentioned, seems to be related to Itasca developers.

The Itasca code you [linked](http://docs.itascacg.com/pfc600/pfc/docproject/source/manual/optional_features/cfd_option/cfd_darcy.html?highlight=darcy) says to call `solver.set_inflow_rate(1e-5)`. 

Your questions are not FiPy questions. They are questions about how to use an Itasca code that's built on top of FiPy. Please seek help from the Itasca developers.

**Comment by alisheikholeslam** [comment]
This equation ```solver.set_inflow_rate(1e-5)``` is for applying flow rate in direction of +Y, not for a radial one.
You are right, this question is more relevant to them. Thank you for your time.
