### ISSUE TITLE
circleQuad example fails with Gmsh > 4.4

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#792]
As noted in #791, examples/diffusion/circleQuad.py fails with Gmsh > 4.4.

The magnitude of the error is about three times larger with Gmsh 4.6. The cell sizes are similar, but the orthogonality is much worse:

|Gmsh 3.0.6|Gmsh 4.6.0|
|-----------|-----------|
|![error_gmsh3 0 6](https://user-images.githubusercontent.com/1830725/114206363-45e0c780-9929-11eb-9369-6b96f4d6063f.png)|![error_gmsh4 6 0](https://user-images.githubusercontent.com/1830725/114206367-46795e00-9929-11eb-97a1-4f086924dfc8.png)|
|![volume_gmsh3 0 6](https://user-images.githubusercontent.com/1830725/114206671-92c49e00-9929-11eb-8acc-8091f963556c.png)|![volume_gmsh4 6 0](https://user-images.githubusercontent.com/1830725/114206678-948e6180-9929-11eb-9f3a-fcb61b37f9ae.png)|
|![nonorthogonality_gmsh3 0 6](https://user-images.githubusercontent.com/1830725/114206787-b12a9980-9929-11eb-8cf3-808e9d5432e0.png)|![nonorthogonality_gmsh4 6 0](https://user-images.githubusercontent.com/1830725/114206792-b2f45d00-9929-11eb-8e8f-1af3acece401.png)|

**Comment by wd15** [comment]
Actually, it passes with version 4.4.1, but fails with 4.6.0.
