### ISSUE TITLE
Gmsh load issue

### ISSUE THREAD

**Issue by addadyy** [usnistgov/fipy#826]
On WSL unbuntu, gmsh version info is given in the standard output, instead of stderr, which cause gmsh version fails to fetch
from the following line (gmshMesh.py: 81):
out, verStr = p.communicate()

Consider check whichever one is empty and set the verStr to be that one? like,
out, err = p.communicate()
verStr = out.decode('ascii').strip() if out else err.decode('ascii').strip()

**Comment by addadyy** [comment]
Hi, i'm using gmsh 4.9.0

**Comment by guyer** [comment]
Fixed by #846
