### ISSUE TITLE
Is Van Leer Convection Term Formulated Conservatively

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#838]
Hi

I was looking through the documentation to see if the various convection terms are formulated conservatively. I noticed that the ExplicitUpwind  and similar terms are formulated conservatively i.e. \nabla \cdot (u \phi), but the First order convection terms are formulated non conservatively i.e., u\cdot \nabla \phi. I am curious about the formulation of the Van Leer term since there is no discussion of this point in the documentation (https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.terms.html). 

Thanks for the help!

**Comment by wd15** [comment]
Regarding the [AdvectionTerm](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.terms.html#module-fipy.terms.advectionTerm) linked above. That particular equation is somewhat of an edge case in FiPy and is used in conjunction with the level set method. It is not a typical FV formulation for a convection term. It is also not a conservative equation anyway. The way the documentation is rendering on the web page is also making it confusing. If you look at the [CentralDifferenceConvectionTerm](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.terms.html#module-fipy.terms.centralDiffConvectionTerm) it has a more typical conservative scheme.

**Comment by pavaninguva** [comment]
Hi @wd15 Thanks for the clarification. It can be a little confusing when people talk about conservative methods. I get that by formulation, FVM is conservative in the sense that total mass is conserved numerically speaking since its based on the fluxes. But in this case, what im specifically referring to is a feature of non-constant coefficient advection equations e.g.,
dc/dt + d(u(x)c)/dx = 0, --(1)
where c is the concentration and u(x) is a spatially dependent velocity. 

Depending on the solver, we could either declare it directly since the fluxes u(x)c|_{i-1/2} and u(x)c|_{i+1/2} are formulated properly. But in other cases, if the convective term is set up such that it solves u(x)*dc/dx, then we might need to expand out the original equation (1) into
dc/dt + u(x)*dc/dx + u'(x)c = 0, 
i.e., include a source term. 

So if the VanLeerConvectionTerm is formulated like the CentralDifferenceConvectionTerm and other ConvectionTerms, then if I had the following equation for example, 
dc/dt + d(u(x)c)/dx = 0, u(x) = u0*x, 
would the following FiPy declaration be correct? 
```
eq1 = TransientTerm(var=c) + VanLeerConvectionTerm(var=c, coeff=(u0*x,)) == 0
```

**Comment by wd15** [comment]
> Hi @wd15 Thanks for the clarification. It can be a little confusing when people talk about conservative methods. I get that by formulation, FVM is conservative in the sense that total mass is conserved numerically speaking since its based on the fluxes. But in this case, what im specifically referring to is a feature of non-constant coefficient advection equations e.g., dc/dt + d(u(x)c)/dx = 0, --(1) where c is the concentration and u(x) is a spatially dependent velocity.
> 
> Depending on the solver, we could either declare it directly since the fluxes u(x)c|_{i-1/2} and u(x)c|_{i+1/2} are formulated properly. But in other cases, if the convective term is set up such that it solves u(x)*dc/dx, then we might need to expand out the original equation (1) into dc/dt + u(x)*dc/dx + u'(x)c = 0, i.e., include a source term.

Right, if we solve the second equation as written using FD or FV then we would likely lose strict conservation when approximating the terms numerically. Obviously, the equation is still conservative in the limit of a perfect accurate solution. In 
FiPy the second term can't really be solved other than with the weird term discussed previously.

> So if the VanLeerConvectionTerm is formulated like the CentralDifferenceConvectionTerm and other ConvectionTerms, then if I had the following equation for example, dc/dt + d(u(x)c)/dx = 0, u(x) = u0*x, would the following FiPy declaration be correct?
> 
> ```
> eq1 = TransientTerm(var=c) + VanLeerConvectionTerm(var=c, coeff=(u0*x,)) == 0
> ```

Yes, that should work. It's good to be clear about the shape and rank of the coefficient. So, I would create the coefficient like this.

    >>> from fipy import Grid1D, FaceVariable, TransientTerm, VanLeerConvectionTerm, CellVariable
    >>> m = Grid1D(nx=3)
    >>> X = m.faceCenters[0]
    >>> X.shape
    (4,)

The following works regardless of the dimension of the mesh.

    >>> coeff = FaceVariable(mesh=m, rank=1)
    >>> u0 = 1.
    >>> coeff[0] = u0 * X
    >>> c = CellVariable(mesh=m)
    >>> eq1 = TransientTerm(var=c) + VanLeerConvectionTerm(var=c, coeff=coeff) == 0
    >>> eq1.solve(dt=1.)

**Comment by pavaninguva** [comment]
Hi @wd15 Thank you so much for the help with implementation! This is really helpful info!
