### ISSUE TITLE
Convection / Diffusion problem (injection of reagent into vessel)

### ISSUE THREAD

**Issue by Noxical** [usnistgov/fipy#843]
Hi,
I want to make a program to inject reagent into a vessel via a lance and then the reagent floods to the top. However problem is that the total amount of injected reagents do not match the injected materials over time. So I inject x moles per second and than calculate the total amount in the vessel. See my code below. Somehow the convection term is messing up the inlet flow at the lance tip and I do not know how to isolate the source term. I have tried to zero the diffusion and convection term at the lance tip (mask) but apparently there is additional problem. So when changing the velocity field the injection rate changes.
Regards

```python
from fipy import *
import numpy as np

mesh  = Gmsh2D('''
SetFactory("OpenCASCADE");
ns = 0.1;
x1 = 0;
y1 = 0;
x2 = 1;
y2 = 2;

Point(1) = {x1, y1, 0, ns};
Point(2) = {x2, y1, 0, ns};
Point(3) = {x2, y2, 0, ns};
Point(4) = {x1, y2, 0, ns};
Point(5) = {x1, 1, 0,  ns};
Point(6) = {0.1, 1, 0, ns};
Point(7) = {0.1, 0.9, 0, ns};
Point(8) = {x1, 0.9, 0, ns};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 5};
Line(5) = {5, 6};
Line(6) = {6, 7};
Line(7) = {7, 8};
Line(8) = {8, 1};

Curve Loop(1) = {1, 2, 3, 4, 5, 6, 7, 8};

Plane Surface(1) = {1};

Physical Surface("liq") = {1};

Physical Line("lance") = {6};
'''% locals())

mask      = mesh.physicalFaces["lance"] 

Volume    = mesh.cellVolumes.sum()

C = CellVariable(name="reagent", mesh=mesh, value=0, hasOld=True)

area      = mesh._faceAreas[mask]

inj_rate  = 1. / (area) # moles/s / m2

diffusion=FaceVariable(mesh=mesh)        
diffusion.setValue(1e-3)
diffusion.setValue(0, where=mask) #no diffusion from lance tip

velocity = FaceVariable(mesh=mesh, value=(0.1,0.5), rank=1)               
velocity.setValue(0, where=mask)

eq_C = (TransientTerm() + ConvectionTerm(velocity) 
        == DiffusionTerm(diffusion) 
        + (mask * inj_rate * mesh.faceNormals).divergence
        )


steps = 10 #time steps

for i in range(steps):
    C.updateOld()
    
    eq_C.solve(C,  dt=1)
    
    Ctot =  Volume * C.cellVolumeAverage  #[S]
   
    vi = Viewer(C, datamin=0., datamax=100.)

    row = []
    row.append(str(i))
    row.append("total moles" + str(Ctot))

    print(row)
```

**Comment by guyer** [comment]
Please explain what you think it should do

**Comment by Noxical** [comment]
1 mol/s of reagent is injected into the vessel via the lance. The reagent is collect in the vessel and will flood to the top where it will stay. So i want to match the injection rate with the cumulated value. 

In next stage the reagent should also react with other components in the vessel, so I can investigate reaction kinetics vs diffusion and convection. However the overall mass balance first needs to be correct. 

When i run the model for 10 sec I would expect 10 moles to be accumulated after 10 sec, but this is not the case. I cannot set the correct boundary conditions.

**Comment by guyer** [comment]
The problem is subtle and unrelated to either your convection or diffusion terms (you can see this be removing the convection and diffusion terms altogether and you see that the system still does not gain 1 mol/s).

You must declare
```python
C = CellVariable(name="reagent", mesh=mesh, value=0., hasOld=True)
```
instead of
```python
C = CellVariable(name="reagent", mesh=mesh, value=0, hasOld=True)
```

`value=0` creates a `CellVariable` of integers
