### ISSUE TITLE
Setting diffusion coefficient using GMSH face definition

### ISSUE THREAD

**Issue by Noxical** [usnistgov/fipy#844]
I want to set the diffusion coefficient / thermal conductivity in a wall based on the specific wall material isolation property.

I cant figure out how to do this using GMSH. My code is attached below. It works only by setting the D value using the X, Y faceCenters. However, I would prefer to use GMSH to specifiy the correct material within the line loop.

from fipy import *
import numpy as np

mesh  = Gmsh2D('''
SetFactory("OpenCASCADE");

ns = 0.01;

x0 = 0;
x1 = 1;
x2 = 0.9;

x3 = 0.8;
x4 = 0.7;

y0 = 0;
y1 = 1;
y2 = 0.1;

y3 = 0.2;
y4 = 0.3;

Point(1) = {x0, y0, 0, ns};
Point(2) = {x1, y0, 0, ns};
Point(3) = {x1, y1, 0, ns};
Point(4) = {x2, y1, 0, ns};
Point(5) = {x2, y2, 0, ns};
Point(6) = {x0, y2, 0, ns};

Point(8) = {x3, y1, 0, ns};
Point(9) = {x3, y3, 0, ns};
Point(10) = {x0, y3, 0, ns};

Point(11) = {x4, y1, 0, ns};
Point(12) = {x4, y4, 0, ns};
Point(13) = {x0, y4, 0, ns};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 5};
Line(5) = {5, 6};
Line(6) = {6, 1};

Line(7) = {4, 8};
Line(8) = {8, 9};
Line(9) = {9, 10};
Line(10) = {10, 6};

Line(11) = {8, 11};
Line(12) = {11, 12};
Line(13) = {12, 13};
Line(14) = {13, 10};

Line Loop(1) = {1,2,3,7,11,12,13,14,10,6};
Plane Surface(1) = {1};
Physical Surface("wall") = {1};

Physical Line("shell") = {1,2,3,4,5,6};

Physical Line("outer") = {1,2};
Physical Line("inner") = {12,13};

'''% locals())

X,Y = mesh.faceCenters
T   = CellVariable(name="isotherm", mesh=mesh, value=1.) 

D=FaceVariable(mesh=mesh, value=1.)   

mask = mesh.physicalFaces["shell"]

D.setValue(0.1, where=mask) # this doesn work

D.setValue(1,  where= (X>0.9) + (Y<0.1))
D.setValue(2,  where= (X<0.9) + (Y>0.1))
             
T.constrain(1400, mesh.physicalFaces['inner'] )
T.constrain(40, mesh.physicalFaces['outer'] )

eq = TransientTerm(var=T) == DiffusionTerm(D, var=T) 

steps = 2  #time steps
dt = 600

for i in range(steps):
 
    eq.solve(var=T, dt=dt)
vi = Viewer(T)

**Comment by guyer** [comment]
Please see the use of [`Physical Surface`](https://gmsh.info/doc/texinfo/gmsh.html#Surfaces) in the [documentation for `Gmsh2D`](https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.meshes.html#fipy.meshes.gmshMesh.Gmsh2D)

**Comment by Noxical** [comment]
Thanks. This solves the problem.
