### ISSUE TITLE
flux boundary condition 1D diffusion 

### ISSUE THREAD

**Issue by Robob1715** [usnistgov/fipy#869]
Hi, 

I am currently learning how to work with fipy and I have run into an issue when trying to run the code below. The problem is stationary 1D diffusion with a flow out of the right boundary: 

```python
nx = 50
dx = 1.
msh = Grid1D(nx=nx, dx=dx)

phi = CellVariable(name="solution variable", mesh=msh, value=0.)


D = FaceVariable(name='diffusion coefficient',mesh=msh, value=1.)
D.constrain(0., msh.facesRight)
flux = 1
boundary =  (msh.facesRight * flux).divergence

(DiffusionTerm(coeff=D) + boundary).solve(var=phi)
viewer = Viewer(vars=phi)
viewer.plot()
```

I keep getting the error message :

> RuntimeError: Factor is exactly singular

But with two Neumann boundary conditions this should be solvable, right (default zero flux on the left, specified flux on the right). What is going wrong? 

Thank you very much for your help.

**Comment by guyer** [comment]
This question was also asked (and at least partially answered) on [StackOverflow](https://stackoverflow.com/q/72373795/2019542). 

@wd15: do you have any suggestions to improve my answer on SO?

**Comment by wd15** [comment]
I don't have anything to add. Using a volume constraint is a great idea for that.
