### ISSUE TITLE
Homogeneous Internal Neumann Boundary Condition for Circle Mesh

### ISSUE THREAD

**Issue by JDS19** [usnistgov/fipy#878]
I am using a circular mesh generated from Gmsh using the same mesh generation method used in the [diffusion in circular mesh example](https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.circle.html). 

Before I go to cases with angular asymmetries, I am trying to model the transient 2D case with circular symmetry to make sure the system behaves how I expect it to. I don't write in any angular dependency, but I notice my solutions seem to have an angular dependence. Before I continue further down a deep dive on what's going on, I want to ask: Does the 2D circular mesh case automatically constrain the gradient at the center of the circle to zero? Or should I try to implement that with an internal boundary condition?
I have tried using smaller tolerances (1e-9 for variables on the scale of 0.01), smaller time steps, and a finer grid, but I still have this issue.

Thank you.

**Comment by guyer** [comment]
If there was an equilateral cell precisely centered on the center of the circular domain, then I would expect its gradient to be zero. Otherwise, I would expect some discretization error. What is the nature of the angular dependence you are observing?

**Comment by JDS19** [comment]
The boundary condition I'm implementing is a flux related to a reaction rate at the mesh exterior. I changed my system to have a constant reaction rate to make the problem more simple, but I still get more depletion of the concentration as you get closer to 5*pi/4 and more generation of the concentration as you get closer to pi/4. This image is taken after about 150 time steps so the system has evolved a fair amount from its initial state of being 0.05 everywhere. 

![pore concentrations - angular dependence](https://user-images.githubusercontent.com/69201170/182933718-9a95c686-6912-4c8f-8713-469da2393903.jpg)

**Comment by guyer** [comment]
Please show some code and some math that the code is intended to implement. I seriously doubt that this is due to any non-idealities in the mesh.

**Comment by JDS19** [comment]
The intended equations are: 
$$\frac{\partial c_R}{\partial t} = D_R \nabla ^2 c_R$$
$$\frac{\partial c_O}{\partial t} = D_O \nabla ^2 c_O$$
At the exterior of the mesh, the boundary conditions are
$D_O\frac{\partial c_O}{\partial r} =  i/F$
And the rate of diffusion of oxidized species to be consumed by the reaction is balanced by the rate of diffusion of reduced species generated from the reaction to move away from the exterior with 
$D_R\frac{\partial c_R}{\partial r}=D_O\frac{\partial c_O}{\partial r}$
Here, $c$ represents a concentration, $O$ and $R$ represent oxidized and reduced forms of a molecule, $i$ is a reaction rate, and $D$ and $F$ are constants. 

The simplified version of the simulation where I assume a constant reaction rate is with this code:
```
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
from fipy import Variable, FaceVariable, CellVariable, TransientTerm, DiffusionTerm, Viewer, Gmsh2D
from fipy.tools import numerix

# Material properties, use AQDS
radius = 0.01 
diam = 2*radius

# We won't care about potentials in this version of the simulation,
# but here they are
E0 = 0.213 # reduction potential vs SHE 
E1_upper = 0.4 # Starting potential for electrode
E1_lower = 0.0 # Ending potential for electrode 

# starting concentrations if we don't set 0 for product
c1_0 = 0.05 # M  
c2_0 = 0.05 # M

DR = 3.8e-6 # diffusion coefficient cm^2/s
DO = DR # assume equal diffusivity for reactant and product 

ct,R,F,T = 0.5, 8.3143, 96485., 293.  
ne, s = 1, 1 # number of electrons and stoichiometric coefficient
k = 5e-6 # reaction rate, cm/s

# Create mesh 
nx = 50
cellSize = diam/nx

# Use these lines to create the mesh with Gmsh code
# for a circle centered at 0 with radius "radius"
mesh = Gmsh2D('''
              cellSize = %(cellSize)g;
              radius = %(radius)g;
              Point(1) = {0, 0, 0, cellSize};
              Point(2) = {-radius, 0, 0, cellSize};
              Point(3) = {0, radius, 0, cellSize};
              Point(4) = {radius, 0, 0, cellSize};
              Point(5) = {0, -radius, 0, cellSize};
              Circle(6) = {2, 1, 3};
              Circle(7) = {3, 1, 4};
              Circle(8) = {4, 1, 5};
              Circle(9) = {5, 1, 2};
              Line Loop(10) = {6, 7, 8, 9};
              Plane Surface(11) = {10};
              ''' % locals()) 

# Create unknowns
cR = CellVariable(name="Reduced Species",mesh=mesh,hasOld=True)
cO = CellVariable(name="Oxidized Species",mesh=mesh,hasOld=True)

# Set initial conditions
cO.setValue(c1_0) 
cR.setValue(c2_0)

# Set potential and current density
E1 = E1_upper
# For simple case, try constant current
i = -0.5 # mA

# Set boundary conditions
# Homogeneous Neumann BC's are automatically applied (dc/dr = 0 at center?)
cO.faceGrad.constrain(i/DO/F,where=mesh.exteriorFaces)
# Rate of diffusion of reactant to surface is balanced by product away from surface
cR.faceGrad.constrain(-cO.faceGrad*DO/DR,where=mesh.exteriorFaces)

# Set up equations
eqO = (TransientTerm(var=cO) == DiffusionTerm(coeff=DO,var=cO))
eqR = (TransientTerm(var=cR) == DiffusionTerm(coeff=DR,var=cR))

viewerR = Viewer(vars=cR, datamin=0.04, datamax=0.06)
viewerR.plotMesh()
plt.title('Electrode Pore')
plt.xlabel('[cm]')
plt.ylabel('[cm]')

viewerO = Viewer(vars=cO, datamin=0.04, datamax=0.06)
viewerO.plotMesh()
plt.title('Electrode Pore')
plt.xlabel('[cm]')
plt.ylabel('[cm]')

 # scan at 10 mV/s; in this case, we won't care about potential, 
# but it still sets the time iterations I'm interested in
v = -0.01
dt = 0.01 # s
dt_max = (diam/nx)**2/DO

# Make sure step size is smaller than diffusion timescale
if dt > dt_max:
    dt = 0.8*dt_max

# Store values of interest
store_cO, store_cR, store_current = [], [], []
store_cO.append(cO)
store_cR.append(cR)
store_current.append(i)
t = []
t.append(0.0)
store_E1 = []
store_E1.append(E1)
residuals_O, residuals_R = [], []
tol = 1e-9

counter = 0

while E1 >= E1_lower:
    cO.updateOld()
    cR.updateOld()
    resO_step, resR_step = [], []
    # Initiate large residuals so we start solving
    # Solve the equations with tolerance tol.
    resO, resR = 50, 50
    while np.max([resO,resR]) > tol:
        resR = eqR.sweep(var=cR,dt=dt)
        resO = eqO.sweep(var=cO,dt=dt)
        # Store residuals in this sweep
        resO_step.append(resO)
        resR_step.append(resR)
    # Store residuals in this timestep
    residuals_O.append(resO_step)
    residuals_R.append(resR_step)
    
    viewerR.plot()
    # viewerO.plot()
    
    # Store solutions
    store_cO.append(cO)
    store_cR.append(cR)
    
    # Sweep potential
    E1 += v*dt
    
    # Commenting out because trying constant current:
    # i.setValue( F*k*(cR.faceValue*numerix.exp(betaR*(E1-equil.faceValue))-
    #                  cO.faceValue*numerix.exp(betaO*(E1-equil.faceValue))) )
    # store_current[:,counter+1] = i
    # store_current.append(i)
    store_E1.append(E1)
    t.append(t[-1]+dt)
    
    print(f'Time: {t[-1]:.4} seconds')
    
    # View potential & scan every 15 steps
    if counter % 15 == 0:
        # viewer.plot()
        print(f'Potential at {E1:.4f} between {E1_upper} & {E1_lower} with rate {v}')

    # Reset boundary conditions
    # Homogeneous Neumann BC's are automatically applied
    cO.faceGrad.constrain(i/DO/F,where=mesh.exteriorFaces)
    cR.faceGrad.constrain(-cO.faceGrad*DO/DR,where=mesh.exteriorFaces)
    counter += 1
```
Python version is 3.8.3, Fipy version 3.4.3

My guess would be there's something wrong with how I'm making the mesh, but I tried to replicate the circle mesh diffusion example.

**Comment by guyer** [comment]
> ```python
> # Set boundary conditions
> # Homogeneous Neumann BC's are automatically applied (dc/dr = 0 at center?)
> cO.faceGrad.constrain(i/DO/F,where=mesh.exteriorFaces)
> ```

This assigns `cO.faceGrad` to a scalar, which means the x and y values get the same scalar value. This is the source of the anisotropy you see. Instead, write:

```python
# Set boundary conditions
# Homogeneous Neumann BC's are automatically applied (dc/dr = 0 at center?)
cO.faceGrad.constrain(i*mesh.faceNormals/DO/F,where=mesh.exteriorFaces)
```



> ```python
> # Rate of diffusion of reactant to surface is balanced by product away from surface
> cR.faceGrad.constrain(-cO.faceGrad*DO/DR,where=mesh.exteriorFaces)
> ```

This seems to be OK, but I would be cautious about the stability of assigning one constraint to be the value of another.


At the end of the while loop:
> ```python
>     # Reset boundary conditions
>     # Homogeneous Neumann BC's are automatically applied
>     cO.faceGrad.constrain(i/DO/F,where=mesh.exteriorFaces)
>     cR.faceGrad.constrain(-cO.faceGrad*DO/DR,where=mesh.exteriorFaces)
> ```
Don't do this. It accomplishes nothing and just slows things down as FiPy tries to apply a longer and longer list of constraints at each exterior face.

**Comment by JDS19** [comment]
Amazing, thank you! The anisotropy is gone! 

I have one more question: If I set $i$ as a FaceVariable instead, and $i$ gets updated to a new value at each time step, should I redefine the constraints in that case? Or does the constraint know to stay tied to the current value of the FaceVariable?

**Comment by guyer** [comment]
You should never redefine constraints. If you define the constraint in terms of a `Variable` object and then update the value of the `Variable` object, the constraint will update automatically. That's the whole point of `Variable` objects.

**Comment by JDS19** [comment]
Got it. Thank you!
