### ISSUE TITLE
How to plot temperature vs depth

### ISSUE THREAD

**Issue by Sandip433** [usnistgov/fipy#941]
Hi , I am using fipy to solve these coupled equations 
[TTM1.pdf](https://github.com/usnistgov/fipy/files/12323183/TTM1.pdf)
. Here the temperature has two independent variable, time ( t ) and depth ( z ). I can plot temperature vs time using this code 
[TWO.TEMPERATURE.MODEL.txt](https://github.com/usnistgov/fipy/files/12323194/TWO.TEMPERATURE.MODEL.txt)
. But I could not plot temperature vs depth. Can anybody help me ?

**Comment by guyer** [comment]
```python
viewer = Viewer(vars=(T_e, T_p))
viewer.plot()
```

**Comment by Sandip433** [comment]
Yes, I wanted to save the data and plot according to my choice. Using this portion of code I save the data T( t = 0, z = 0) to T( t= t1) 
`with open('a.txt','wt') as f:
    print('time->>',t_list,'\n''\n''\n''\n''ELECTRON TEMPERATURE->>',results_T_e,'\n''\n''\n''\n''PHONON TEMPERATURE->>',results_T_p,file=f)
`
After some digging I found that I can save the data of T( t = t1 , z= 0 ) to T( t = t1, z = nx*dx) using this code 
`TSVViewer(vars=( T_e,T_p)).plot(filename="b.txt")`
Thanks for the help
