### ISSUE TITLE
future.standard_library breaking python 3.12 compatibility

### ISSUE THREAD

**Issue by boatmorrow** [usnistgov/fipy#997]
future.standard_library imports the imp module which is gone in python 3.12.  So, future.standard_library is not really python 3.12 compatible.

[issue tracker](https://github.com/PythonCharmers/python-future/issues/625)

This means fipy breaks in python 3.12 at the import of the entire future.standard_library.  I'm thinking a work around could be, to be more selective about what parts of future are imported?

**Comment by guyer** [comment]
I'm impressed you got FiPy to install with Python 3.12 at all. I've fixed this particular issue on #1023. That won't be merged to master until I can expunge Python 2.7 (RealSoonNow (tm)) (versioneer.py cannot be compatible with Python 2.7 and Python 3.12).
